"""Auto-generated synchronous facade for `HelperClient`.

Do not edit this file directly.

It is generated from `api.helpers.HelperClient` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from typing import Any

from pydantic import BaseModel

from hassette.api.helpers import HelperDomain
from hassette.resources.base import Resource
from hassette.resources.lifecycle import mark_ready
from hassette.types.types import LOG_LEVEL_TYPE

if typing.TYPE_CHECKING:
    from hassette import Hassette
    from hassette.api.helpers import HelperClient


class HelperClientSyncFacade(Resource):
    """Synchronous facade for the helper CRUD client.

    This class provides synchronous methods that wrap the asynchronous methods of the
    HelperClient class, allowing for blocking calls in a synchronous context.

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``HelperClient`` directly when operating within an event loop.
    """

    _helpers: "HelperClient"

    def __init__(self, hassette: "Hassette", *, helpers: "HelperClient", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._helpers = helpers

    async def on_initialize(self) -> None:
        mark_ready(self, reason="Synchronous HelperClient facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.api

    def list(self, domain: HelperDomain) -> list[Any]:
        """List all stored helpers for a given domain.

        Args:
            domain: The helper domain to list (e.g. "input_boolean", "counter").

        Returns:
            List of domain-specific Record instances representing stored configs.
        """
        return self.task_bucket.run_sync(self._helpers.list(domain))  # pyright: ignore[reportCallIssue, reportArgumentType]

    def create(self, params: BaseModel) -> BaseModel:
        """Create a new helper.

        Args:
            params: Parameters for the new helper. The concrete type determines the domain
                and the return type via overload resolution.

        Returns:
            The stored record returned by Home Assistant.
        """
        return self.task_bucket.run_sync(self._helpers.create(params))  # pyright: ignore[reportCallIssue, reportArgumentType]

    def update(self, helper_id: str, params: BaseModel) -> BaseModel:
        """Update an existing helper.

        Args:
            helper_id: The ID of the helper to update.
            params: Fields to update (unset fields are left unchanged). The concrete type
                determines the domain and the return type via overload resolution.

        Returns:
            The updated stored record.
        """
        return self.task_bucket.run_sync(self._helpers.update(helper_id, params))  # pyright: ignore[reportCallIssue, reportArgumentType]

    def delete(self, domain: HelperDomain, helper_id: str) -> None:
        """Delete a helper.

        Args:
            domain: The helper domain (e.g. "input_boolean", "counter").
            helper_id: The ID of the helper to delete.
        """
        return self.task_bucket.run_sync(self._helpers.delete(domain, helper_id))  # pyright: ignore[reportCallIssue, reportArgumentType]

    def increment(self, entity_id: str) -> None:
        """Increment a counter entity's current value (live state, not stored config).

        Args:
            entity_id: The entity ID of the counter (e.g. ``"counter.motion_count"``).
        """
        return self.task_bucket.run_sync(self._helpers.increment(entity_id))

    def decrement(self, entity_id: str) -> None:
        """Decrement a counter entity's current value (live state, not stored config).

        Args:
            entity_id: The entity ID of the counter (e.g. ``"counter.motion_count"``).
        """
        return self.task_bucket.run_sync(self._helpers.decrement(entity_id))

    def reset(self, entity_id: str) -> None:
        """Reset a counter entity's value to its configured initial (live state, not stored config).

        Args:
            entity_id: The entity ID of the counter (e.g. ``"counter.motion_count"``).
        """
        return self.task_bucket.run_sync(self._helpers.reset(entity_id))
