"""Generic sync facade generation for Api, Bus, and Scheduler."""

import ast
import textwrap
from pathlib import Path

from hassette_codegen.sync_facade.ast_utils import (
    desync_docstring,
    format_signature_and_call,
    is_delegatable,
    is_wrappable,
    safe_parse,
    unwrap_coroutine_return,
)

HEADER = '''"""Auto-generated synchronous facade for `Api`.

Do not edit this file directly.

It is generated from `api.Api` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Generator
from enum import StrEnum
from typing import Any

import aiohttp
from whenever import Date, PlainDateTime, ZonedDateTime

from hassette.const.misc import FalseySentinel
from hassette.models.helpers import (
    CounterRecord,
    CreateCounterParams,
    CreateInputBooleanParams,
    CreateInputButtonParams,
    CreateInputDatetimeParams,
    CreateInputNumberParams,
    CreateInputSelectParams,
    CreateInputTextParams,
    CreateTimerParams,
    InputBooleanRecord,
    InputButtonRecord,
    InputDatetimeRecord,
    InputNumberRecord,
    InputSelectRecord,
    InputTextRecord,
    TimerRecord,
    UpdateCounterParams,
    UpdateInputBooleanParams,
    UpdateInputButtonParams,
    UpdateInputDatetimeParams,
    UpdateInputNumberParams,
    UpdateInputSelectParams,
    UpdateInputTextParams,
    UpdateTimerParams,
)
from hassette.models.history import HistoryEntry
from hassette.models.services import ServiceResponse
from hassette.resources.base import Resource
from hassette.types.types import LOG_LEVEL_TYPE

if typing.TYPE_CHECKING:
    from hassette import Api, Hassette
    from hassette.events.hass.raw import HassStateDict
    from hassette.models.entities import EntityT
    from hassette.models.states.base import BaseState

'''


CLASS_HEADER = '''
class ApiSyncFacade(Resource):
    """Synchronous facade for the API service.

    This class provides synchronous methods that wrap the asynchronous methods of the Api class,
    allowing for blocking calls in a synchronous context.

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``Api`` directly when operating within an event loop.
    """

    _api: "Api"

    def __init__(self, hassette: "Hassette", *, api: "Api", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._api = api

    async def on_initialize(self) -> None:
        self.mark_ready(reason="Synchronous API facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.api

'''


BUS_HEADER = '''"""Auto-generated synchronous facade for `Bus`.

Do not edit this file directly.

It is generated from `bus.Bus` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Mapping
from typing import Any, Unpack

from hassette.bus.listeners import Subscription
from hassette.bus.options import Options
from hassette.const import NOT_PROVIDED
from hassette.resources.base import Resource
from hassette.types import ComparisonCondition
from hassette.types.enums import ResourceStatus
from hassette.types.types import LOG_LEVEL_TYPE

if typing.TYPE_CHECKING:
    from collections.abc import Sequence

    from hassette import Bus, Hassette
    from hassette.bus.listeners import Listener
    from hassette.types import ChangeType, HandlerType, Predicate
    from hassette.types.types import BusErrorHandlerType

'''


BUS_CLASS_HEADER = '''
class BusSyncFacade(Resource):
    """Synchronous facade for the event bus.

    This class provides synchronous methods that wrap the asynchronous registration methods of
    the Bus class, allowing listeners to be registered from synchronous code (for example, an
    ``AppSync`` lifecycle hook running in a worker thread).

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``Bus`` directly when operating within an event loop.
    """

    _bus: "Bus"

    def __init__(self, hassette: "Hassette", *, bus: "Bus", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._bus = bus

    async def on_initialize(self) -> None:
        self.mark_ready(reason="Synchronous Bus facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.bus_service

'''


SCHEDULER_HEADER = '''"""Auto-generated synchronous facade for `Scheduler`.

Do not edit this file directly.

It is generated from `scheduler.Scheduler` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Mapping
from typing import Any, Literal

from whenever import ZonedDateTime

from hassette.resources.base import Resource
from hassette.scheduler.classes import ScheduledJob
from hassette.types.types import LOG_LEVEL_TYPE

if typing.TYPE_CHECKING:
    from hassette import Hassette, Scheduler
    from hassette.types import JobCallable, TriggerProtocol
    from hassette.types.types import SchedulerErrorHandlerType

'''


SCHEDULER_CLASS_HEADER = '''
class SchedulerSyncFacade(Resource):
    """Synchronous facade for the scheduler.

    This class provides synchronous methods that wrap the asynchronous scheduling methods of
    the Scheduler class, allowing jobs to be scheduled from synchronous code (for example, an
    ``AppSync`` lifecycle hook running in a worker thread).

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``Scheduler`` directly when operating within an event loop.
    """

    _scheduler: "Scheduler"

    def __init__(self, hassette: "Hassette", *, scheduler: "Scheduler", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._scheduler = scheduler

    async def on_initialize(self) -> None:
        self.mark_ready(reason="Synchronous Scheduler facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.scheduler_service

'''


def gen_wrapper(func: ast.FunctionDef | ast.AsyncFunctionDef, wrapped_attr: str = "_api") -> str:
    """Emit a sync wrapper method that delegates to ``self.<wrapped_attr>`` via run_sync.

    For de-asynced plain-def methods whose return annotation is ``Coroutine[Any, Any, T]``,
    the generated wrapper emits ``-> T`` (the unwrapped inner type) rather than the raw
    ``Coroutine[...]`` annotation — the sync wrapper returns the resolved value, not the
    coroutine, and ``Coroutine`` is not imported in the generated file's header.
    """
    sig, call = format_signature_and_call(func)
    name = func.name
    # Unwrap Coroutine[Any, Any, T] → T for de-asynced plain-def methods so the generated
    # sync wrapper carries the correct return type and avoids an undefined-name ruff error.
    unwrapped = unwrap_coroutine_return(func)
    if unwrapped is not None:
        returns = f" -> {ast.unparse(unwrapped)}"
    elif func.returns:
        returns = f" -> {ast.unparse(func.returns)}"
    else:
        returns = ""

    doc = ast.get_docstring(func)
    if doc:
        doc = desync_docstring(doc)
        doc_str = textwrap.indent('"""' + doc + '"""', " " * 8)
        doc_block = f"\n{doc_str}\n\n"
    else:
        doc_block = "\n"

    body = (
        f"    def {name}({sig}){returns}:{doc_block}"
        f"        return self.task_bucket.run_sync(self.{wrapped_attr}.{name}({call}))\n"
    )
    return body


def gen_delegate(func: ast.FunctionDef, wrapped_attr: str) -> str:
    """Emit a sync delegate method that passes through to ``self.<wrapped_attr>``."""
    sig, call = format_signature_and_call(func)
    name = func.name
    returns = f" -> {ast.unparse(func.returns)}" if func.returns else ""

    doc = ast.get_docstring(func)
    if doc:
        doc = desync_docstring(doc)
        doc_str = textwrap.indent('"""' + doc + '"""', " " * 8)
        doc_block = f"\n{doc_str}\n\n"
    else:
        doc_block = "\n"

    body = f"    def {name}({sig}){returns}:{doc_block}        return self.{wrapped_attr}.{name}({call})\n"
    return body


def _generate_facade(source_path: Path, class_name: str, *, header: str, class_header: str, wrapped_attr: str) -> str:
    """Generate a synchronous facade for ``class_name`` defined in ``source_path``.

    Each public async method becomes a sync wrapper that delegates to
    ``self.<wrapped_attr>.<method>(...)`` via ``task_bucket.run_sync``. ``header`` and
    ``class_header`` are the hand-maintained module imports and class definition; the
    method wrappers are appended verbatim. If a method introduces a type the header does
    not import, the generated module fails to import — surfacing the missing import via
    the drift gate, exactly as the ``ApiSyncFacade`` header is maintained today.
    """
    source = source_path.read_text(encoding="utf8")
    module = safe_parse(source, str(source_path))

    target_class: ast.ClassDef | None = None
    for node in module.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            target_class = node
            break

    if target_class is None:
        raise SystemExit(f"Could not find class `{class_name}` in {source_path}")

    wrappers = [gen_wrapper(node, wrapped_attr) for node in target_class.body if is_wrappable(node)]
    delegates = [gen_delegate(node, wrapped_attr) for node in target_class.body if is_delegatable(node)]

    return header + class_header + "\n".join(wrappers + delegates)


def generate_sync(api_path: Path) -> str:
    """Generate the ApiSyncFacade source from api.py."""
    return _generate_facade(api_path, "Api", header=HEADER, class_header=CLASS_HEADER, wrapped_attr="_api")


def generate_sync_bus(bus_path: Path) -> str:
    """Generate the BusSyncFacade source from bus.py."""
    return _generate_facade(bus_path, "Bus", header=BUS_HEADER, class_header=BUS_CLASS_HEADER, wrapped_attr="_bus")


def generate_sync_scheduler(scheduler_path: Path) -> str:
    """Generate the SchedulerSyncFacade source from scheduler.py."""
    return _generate_facade(
        scheduler_path,
        "Scheduler",
        header=SCHEDULER_HEADER,
        class_header=SCHEDULER_CLASS_HEADER,
        wrapped_attr="_scheduler",
    )
