"""Generic sync facade generation for Api, Bus, and Scheduler."""

import ast
import textwrap
from collections.abc import Callable
from pathlib import Path

from hassette_codegen.sync_facade.ast_utils import (
    desync_docstring,
    format_return_annotation,
    format_signature_and_call,
    is_delegatable,
    is_wrappable,
    safe_parse,
)

HEADER = '''"""Auto-generated synchronous facade for `Api`.

Do not edit this file directly.

It is generated from `api.Api` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Generator
from enum import StrEnum
from typing import Any

import aiohttp
from whenever import Date, PlainDateTime, ZonedDateTime

from hassette.api.sync_helpers import HelperClientSyncFacade
from hassette.const.misc import FalseySentinel
from hassette.models.history import HistoryEntry
from hassette.models.services import ServiceResponse
from hassette.resources.base import Resource
from hassette.resources.lifecycle import mark_ready
from hassette.types.types import LOG_LEVEL_TYPE

if typing.TYPE_CHECKING:
    from hassette import Api, Hassette
    from hassette.events.hass.raw import HassStateDict
    from hassette.models.entities import EntityT
    from hassette.models.states.base import BaseState

'''


CLASS_HEADER = '''
class ApiSyncFacade(Resource):
    """Synchronous facade for the API service.

    This class provides synchronous methods that wrap the asynchronous methods of the Api class,
    allowing for blocking calls in a synchronous context.

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``Api`` directly when operating within an event loop.
    """

    _api: "Api"

    def __init__(self, hassette: "Hassette", *, api: "Api", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._api = api
        self.helpers = self.add_child(HelperClientSyncFacade, helpers=self._api.helpers)

    async def on_initialize(self) -> None:
        mark_ready(self, reason="Synchronous API facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.api

'''


BUS_HEADER = '''"""Auto-generated synchronous facade for `Bus`.

Do not edit this file directly.

It is generated from `bus.Bus` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Mapping
from typing import Any, Unpack

from hassette.bus.listeners import Subscription
from hassette.bus.options import Options
from hassette.bus.sync_events import BusSyncEventShortcuts
from hassette.const import NOT_PROVIDED
from hassette.resources.base import Resource
from hassette.resources.lifecycle import mark_ready
from hassette.types import ComparisonCondition
from hassette.types.types import LOG_LEVEL_TYPE, IfExistsPolicy, WhereClause

if typing.TYPE_CHECKING:
    from collections.abc import Sequence

    from hassette import Bus, Hassette
    from hassette.bus.listeners import Listener
    from hassette.types import ChangeType, HandlerType, Predicate
    from hassette.types.enums import BackpressurePolicy, ExecutionMode
    from hassette.types.types import BusErrorHandlerType

'''


BUS_CLASS_HEADER = '''
class BusSyncFacade(BusSyncEventShortcuts):
    """Synchronous facade for the event bus.

    This class provides synchronous methods that wrap the asynchronous registration methods of
    the Bus class, allowing listeners to be registered from synchronous code (for example, an
    ``AppSync`` lifecycle hook running in a worker thread).

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``Bus`` directly when operating within an event loop.

    The named-event shortcuts (``on_homeassistant_start``, ``on_app_running``, and friends) are
    generated onto ``BusSyncEventShortcuts`` in ``bus/sync_events.py`` and inherited here.
    """

    def __init__(self, hassette: "Hassette", *, bus: "Bus", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._bus = bus

    async def on_initialize(self) -> None:
        mark_ready(self, reason="Synchronous Bus facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.bus_service

'''


BUS_EVENT_SHORTCUTS = frozenset(
    {
        "on_component_loaded",
        "on_service_registered",
        "on_homeassistant_restart",
        "on_homeassistant_start",
        "on_homeassistant_stop",
        "on_hassette_service_status",
        "on_hassette_service_failed",
        "on_hassette_service_crashed",
        "on_hassette_service_started",
        "on_websocket_connected",
        "on_websocket_disconnected",
        "on_app_state_changed",
        "on_app_running",
        "on_app_stopping",
    }
)
"""`Bus` methods whose sync wrappers are emitted into `bus/sync_events.py` instead of `bus/sync.py`.

Every one is a named-event shortcut over `Bus.on()` — a thin convenience around a fixed topic.
They carry long argument lists and long docstrings, and together they are more than half of the
generated facade, which pushed `bus/sync.py` past the repo's 800-line file-size threshold. Keeping
them in a separate generated module splits the facade along the seam a reader would draw anyway:
the core registration API in `sync.py`, the per-event shortcuts in `sync_events.py`.

A new `Bus` shortcut is not added here automatically — it lands in `sync.py` until its name is
added to this set.
"""


BUS_EVENT_SHORTCUTS_HEADER = '''"""Auto-generated synchronous named-event shortcuts for `Bus`.

Do not edit this file directly.

It is generated from `bus.Bus` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Mapping
from typing import Any, Unpack

from hassette.bus.listeners import Subscription
from hassette.bus.options import Options
from hassette.resources.base import Resource
from hassette.types.enums import ResourceStatus
from hassette.types.types import WhereClause

if typing.TYPE_CHECKING:
    from hassette import Bus
    from hassette.types import HandlerType
    from hassette.types.types import BusErrorHandlerType

'''


# Inheritance, not the `.helpers` composition used by ApiSyncFacade/RecordingSyncFacade: those wrap a
# real async-side sub-resource (`Api.helpers`), so a nested `api.sync.helpers.x()` call reads the same
# on both sides. `Bus` has no sub-resource behind its named-event shortcuts, so composition would
# invent a `bus.sync.events.x()` surface that has no async counterpart — a breaking change to the
# facade's public API for a file-size fix.
BUS_EVENT_SHORTCUTS_CLASS_HEADER = '''
class BusSyncEventShortcuts(Resource):
    """Synchronous named-event shortcuts for the event bus.

    An intermediate base class rather than a resource in its own right: ``BusSyncFacade``
    subclasses it and supplies ``_bus``, the constructor, and the lifecycle hooks. These
    wrappers live in their own generated module so ``bus/sync.py`` stays under the repo's
    file-size threshold; callers reach every method here through ``bus.sync``.
    """

    _bus: "Bus"

'''


SCHEDULER_HEADER = '''"""Auto-generated synchronous facade for `Scheduler`.

Do not edit this file directly.

It is generated from `scheduler.Scheduler` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import asyncio
import typing
from collections.abc import Mapping
from typing import Any, Literal

from whenever import ZonedDateTime

from hassette.resources.base import Resource
from hassette.resources.lifecycle import mark_ready
from hassette.scheduler.classes import Job
from hassette.types.types import LOG_LEVEL_TYPE, IfExistsPolicy

if typing.TYPE_CHECKING:
    from collections.abc import Sequence

    from hassette import Hassette, Scheduler
    from hassette.types import JobCallable, TriggerProtocol
    from hassette.types.enums import ExecutionMode
    from hassette.types.types import SchedulerErrorHandlerType, SchedulerPredicate

'''


SCHEDULER_CLASS_HEADER = '''
class SchedulerSyncFacade(Resource):
    """Synchronous facade for the scheduler.

    This class provides synchronous methods that wrap the asynchronous scheduling methods of
    the Scheduler class, allowing jobs to be scheduled from synchronous code (for example, an
    ``AppSync`` lifecycle hook running in a worker thread).

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``Scheduler`` directly when operating within an event loop.
    """

    _scheduler: "Scheduler"

    def __init__(self, hassette: "Hassette", *, scheduler: "Scheduler", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._scheduler = scheduler

    async def on_initialize(self) -> None:
        mark_ready(self, reason="Synchronous Scheduler facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.scheduler_service

'''


HELPERS_HEADER = '''"""Auto-generated synchronous facade for `HelperClient`.

Do not edit this file directly.

It is generated from `api.helpers.HelperClient` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import builtins
import typing
from typing import Any

from pydantic import BaseModel

from hassette.api.helpers import HelperDomain
from hassette.models.helpers import (
    CounterRecord,
    CreateCounterParams,
    CreateInputBooleanParams,
    CreateInputButtonParams,
    CreateInputDatetimeParams,
    CreateInputNumberParams,
    CreateInputSelectParams,
    CreateInputTextParams,
    CreateTimerParams,
    InputBooleanRecord,
    InputButtonRecord,
    InputDatetimeRecord,
    InputNumberRecord,
    InputSelectRecord,
    InputTextRecord,
    TimerRecord,
    UpdateCounterParams,
    UpdateInputBooleanParams,
    UpdateInputButtonParams,
    UpdateInputDatetimeParams,
    UpdateInputNumberParams,
    UpdateInputSelectParams,
    UpdateInputTextParams,
    UpdateTimerParams,
)
from hassette.resources.base import Resource
from hassette.resources.lifecycle import mark_ready
from hassette.types.types import LOG_LEVEL_TYPE

if typing.TYPE_CHECKING:
    from hassette import Hassette
    from hassette.api.helpers import HelperClient

'''


HELPERS_CLASS_HEADER = '''
class HelperClientSyncFacade(Resource):
    """Synchronous facade for the helper CRUD client.

    This class provides synchronous methods that wrap the asynchronous methods of the
    HelperClient class, allowing for blocking calls in a synchronous context.

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``HelperClient`` directly when operating within an event loop.
    """

    _helpers: "HelperClient"

    def __init__(self, hassette: "Hassette", *, helpers: "HelperClient", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._helpers = helpers

    async def on_initialize(self) -> None:
        mark_ready(self, reason="Synchronous HelperClient facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.api

'''


def gen_wrapper(
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    wrapped_attr: str = "_api",
    overloaded_names: frozenset[str] | None = None,
) -> str:
    """Emit a sync wrapper method that delegates to ``self.<wrapped_attr>`` via run_sync.

    For de-asynced plain-def methods whose return annotation is ``Coroutine[Any, Any, T]``,
    the generated wrapper emits ``-> T`` (the unwrapped inner type) rather than the raw
    ``Coroutine[...]`` annotation — the sync wrapper returns the resolved value, not the
    coroutine, and ``Coroutine`` is not imported in the generated file's header.
    """
    sig, call = format_signature_and_call(func)
    name = func.name
    returns = format_return_annotation(func)

    doc = ast.get_docstring(func)
    if doc:
        doc = desync_docstring(doc)
        doc_str = textwrap.indent('"""' + doc + '"""', " " * 8)
        doc_block = f"\n{doc_str}\n\n"
    else:
        doc_block = "\n"

    suppress = (
        "  # pyright: ignore[reportCallIssue, reportArgumentType]"
        if overloaded_names and name in overloaded_names
        else ""
    )
    body = (
        f"    def {name}({sig}){returns}:{doc_block}"
        f"        return self.task_bucket.run_sync(self.{wrapped_attr}.{name}({call})){suppress}\n"
    )
    return body


def gen_delegate(func: ast.FunctionDef, wrapped_attr: str) -> str:
    """Emit a sync delegate method that passes through to ``self.<wrapped_attr>``."""
    sig, call = format_signature_and_call(func)
    name = func.name
    returns = format_return_annotation(func)

    doc = ast.get_docstring(func)
    if doc:
        doc = desync_docstring(doc)
        doc_str = textwrap.indent('"""' + doc + '"""', " " * 8)
        doc_block = f"\n{doc_str}\n\n"
    else:
        doc_block = "\n"

    body = f"    def {name}({sig}){returns}:{doc_block}        return self.{wrapped_attr}.{name}({call})\n"
    return body


def _keep_all(name: str) -> bool:
    """Default ``keep`` filter: emit every eligible method."""
    return True


def _find_class(module: ast.Module, class_name: str) -> ast.ClassDef | None:
    """Return the top-level class named ``class_name`` in ``module``, or ``None``."""
    for node in module.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            return node
    return None


def _generate_facade(
    source_path: Path,
    class_name: str,
    *,
    header: str,
    class_header: str,
    wrapped_attr: str,
    keep: Callable[[str], bool] | None = None,
) -> str:
    """Generate a synchronous facade for ``class_name`` defined in ``source_path``.

    Each public async method becomes a sync wrapper that delegates to
    ``self.<wrapped_attr>.<method>(...)`` via ``task_bucket.run_sync``. ``header`` and
    ``class_header`` are the hand-maintained module imports and class definition; the
    method wrappers are appended verbatim. If a method introduces a type the header does
    not import, the generated module fails to import — surfacing the missing import via
    the drift gate, exactly as the ``ApiSyncFacade`` header is maintained today.

    ``keep`` filters which method names are emitted, so one source class can be split across
    two generated modules (see ``BUS_EVENT_SHORTCUTS``). It defaults to emitting everything.
    """
    source = source_path.read_text(encoding="utf8")
    module = safe_parse(source, str(source_path))

    target_class = _find_class(module, class_name)
    if target_class is None:
        raise SystemExit(f"Could not find class `{class_name}` in {source_path}")

    overloaded_names = frozenset(
        node.name
        for node in target_class.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and any(
            (isinstance(d, ast.Name) and d.id == "overload") or (isinstance(d, ast.Attribute) and d.attr == "overload")
            for d in node.decorator_list
        )
    )

    if keep is None:
        keep = _keep_all

    wrappers = [
        gen_wrapper(node, wrapped_attr, overloaded_names)
        for node in target_class.body
        if is_wrappable(node) and keep(node.name)
    ]
    delegates = [
        gen_delegate(node, wrapped_attr) for node in target_class.body if is_delegatable(node) and keep(node.name)
    ]

    return header + class_header + "\n".join(wrappers + delegates)


def generate_sync(api_path: Path) -> str:
    """Generate the ApiSyncFacade source from api.py."""
    return _generate_facade(api_path, "Api", header=HEADER, class_header=CLASS_HEADER, wrapped_attr="_api")


def generate_sync_helpers(helpers_path: Path) -> str:
    """Generate the HelperClientSyncFacade source from helpers.py."""
    return _generate_facade(
        helpers_path, "HelperClient", header=HELPERS_HEADER, class_header=HELPERS_CLASS_HEADER, wrapped_attr="_helpers"
    )


def generate_sync_bus(bus_path: Path) -> str:
    """Generate the BusSyncFacade source from bus.py, minus the named-event shortcuts."""
    return _generate_facade(
        bus_path,
        "Bus",
        header=BUS_HEADER,
        class_header=BUS_CLASS_HEADER,
        wrapped_attr="_bus",
        keep=lambda name: name not in BUS_EVENT_SHORTCUTS,
    )


def generate_sync_bus_events(bus_path: Path) -> str:
    """Generate the BusSyncEventShortcuts source — the named-event half of the Bus facade.

    Raises SystemExit if ``BUS_EVENT_SHORTCUTS`` names a method ``Bus`` no longer defines: a
    renamed shortcut would otherwise drift back into ``sync.py`` with nothing to say so.
    """
    module = safe_parse(bus_path.read_text(encoding="utf8"), str(bus_path))
    bus_class = _find_class(module, "Bus")
    defined = (
        {node.name for node in bus_class.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))}
        if bus_class is not None
        else set()
    )
    missing = sorted(BUS_EVENT_SHORTCUTS - defined)
    if missing:
        raise SystemExit(f"BUS_EVENT_SHORTCUTS lists methods that `Bus` does not define: {missing}")

    return _generate_facade(
        bus_path,
        "Bus",
        header=BUS_EVENT_SHORTCUTS_HEADER,
        class_header=BUS_EVENT_SHORTCUTS_CLASS_HEADER,
        wrapped_attr="_bus",
        keep=BUS_EVENT_SHORTCUTS.__contains__,
    )


def generate_sync_scheduler(scheduler_path: Path) -> str:
    """Generate the SchedulerSyncFacade source from scheduler.py."""
    return _generate_facade(
        scheduler_path,
        "Scheduler",
        header=SCHEDULER_HEADER,
        class_header=SCHEDULER_CLASS_HEADER,
        wrapped_attr="_scheduler",
    )
