"""RecordingSyncFacade generation orchestrator."""

import ast
import sys
from pathlib import Path

from hassette_codegen.sync_facade.ast_utils import (
    LIFECYCLE_METHODS,
    _safe_parse,
    is_overload,
)
from hassette_codegen.sync_facade.recording_imports import (
    _build_precise_import_block,
    _collect_annotation_symbols,
    _collect_module_level_import_map,
    _collect_referenced_symbols,
    _collect_type_checking_import_map,
)
from hassette_codegen.sync_facade.recording_transform import (
    gen_recording_method,
    gen_recording_stub,
    is_not_implemented_only,
)

_RECORDING_CLASS_HEADER = '''\
class RecordingSyncFacade:  # pyright: ignore[reportUnusedClass]
    """Synchronous recording facade for RecordingApi.

    Instances are created by RecordingApi.__init__ and share the parent's
    `calls` list via the `_parent` reference. Users access it via `harness.api_recorder.sync`
    (which is `RecordingApi.sync`).

    This file is generated by codegen/src/hassette_codegen/sync_facade/ — do not edit by hand.
    """

    _parent: "RecordingApi"

    def __init__(self, parent: "RecordingApi") -> None:
        self._parent = parent

    # NOTE: __getattr__ raises AttributeError for names starting with `_`, including `_parent`.
    # If `_parent` lookup falls through here (e.g., during mock construction before __init__
    # completes, or in a subclass that skips super().__init__), the error will be
    # AttributeError: _parent — which is by design; partial construction is an error.
    def __getattr__(self, name: str) -> Any:
        """Raise NotImplementedError for public attributes not defined on RecordingSyncFacade.

        Private attributes fall through to the default AttributeError so that Python
        machinery works correctly. All known public methods from ``ApiSyncFacade``
        are explicitly generated (either body-copied from RecordingApi or stubbed
        with NotImplementedError). This fallback catches any public attribute that
        is not a generated method — typically a typo or a brand-new method on
        ``ApiSyncFacade`` that the CI drift gate is about to flag.
        """
        if name.startswith("_"):
            raise AttributeError(name)

        raise NotImplementedError(STUB_MSG_GENERIC.format(name=name))
'''

# Template for the module header of the generated recording facade file.
# {imports} is replaced with the dynamically-derived import block.
# {type_checking_imports} is replaced with the TYPE_CHECKING import block.
_RECORDING_MODULE_HEADER_TEMPLATE = '''\
"""Synchronous recording facade for RecordingApi.

Do not edit this file directly.

It is generated from RecordingApi by codegen/src/hassette_codegen/sync_facade/.
"""

import typing
from typing import Any

{imports}

if typing.TYPE_CHECKING:
    from hassette.test_utils.recording_api import RecordingApi
{type_checking_imports}\
# Stub message templates — imported by tests to avoid brittle substring matches.
# Must stay byte-identical with the constants in codegen/src/hassette_codegen/sync_facade/.
STUB_MSG_STATE_CONVERSION = (
    "RecordingApi.sync.{{name}} is not implemented on the test facade. "
    "Call `harness.api_recorder.sync.get_state(entity_id)` and read the returned state directly."
)
STUB_MSG_GENERIC = (
    "RecordingApi.sync.{{name}} is not implemented. "
    "Seed state via AppTestHarness.set_state() for read methods, "
    "or use a full integration test for methods requiring a live HA connection."
)

'''


def generate_sync_recording(api_path: Path, recording_api_path: Path) -> str:
    """Generate the full RecordingSyncFacade source.

    Imports are derived via ``_collect_referenced_symbols`` +
    ``_build_precise_import_block`` directly. This pair is **lenient** about
    unknown symbols (it skips any name that doesn't appear in the symbol map)
    because body-copied method bodies reference many lowercase symbols that are
    local variables, parameters, or comprehension targets — not imports. The
    strict variant ``_derive_recording_imports_strict`` is reserved for unit
    tests that need to assert the error path; the post-generation
    ``ruff check`` + ``py_compile`` steps are the safety net for genuinely
    missing imports in production.

    Args:
        api_path: Path to src/hassette/api/api.py (source of truth for method list).
        recording_api_path: Path to src/hassette/test_utils/recording_api.py.

    Returns:
        Complete Python source string for the generated sync_facade.py.
    """
    # Parse Api to get the ordered method list
    api_source = api_path.read_text(encoding="utf8")
    api_module = _safe_parse(api_source, str(api_path))

    api_class: ast.ClassDef | None = None
    for node in api_module.body:
        if isinstance(node, ast.ClassDef) and node.name == "Api":
            api_class = node
            break
    if api_class is None:
        raise SystemExit("Could not find class `Api` in api.py")

    # Collect all public async methods on Api (ordered, no overloads, no lifecycle)
    api_methods: list[ast.AsyncFunctionDef] = [
        node
        for node in api_class.body
        if isinstance(node, ast.AsyncFunctionDef) and not is_overload(node) and node.name not in LIFECYCLE_METHODS
    ]

    # Parse RecordingApi
    recording_source = recording_api_path.read_text(encoding="utf8")
    recording_module = _safe_parse(recording_source, str(recording_api_path))

    recording_class: ast.ClassDef | None = None
    for node in recording_module.body:
        if isinstance(node, ast.ClassDef) and node.name == "RecordingApi":
            recording_class = node
            break
    if recording_class is None:
        raise SystemExit("Could not find class `RecordingApi` in recording_api.py")

    # Build map of async method name → AST node for RecordingApi
    recording_async_map: dict[str, ast.AsyncFunctionDef] = {}
    for node in recording_class.body:
        if isinstance(node, ast.AsyncFunctionDef):
            recording_async_map[node.name] = node

    # Collect ALL async method names (for the peer-call static check)
    async_method_names: set[str] = set(recording_async_map.keys())

    # Build the symbol map from both recording_api.py and api.py imports.
    # api.py imports cover stub signatures (PlainDateTime, ZonedDateTime, StrEnum, etc.)
    recording_symbol_map = _collect_module_level_import_map(recording_source)
    api_symbol_map = _collect_module_level_import_map(api_source)
    # Merge: recording_api takes precedence (it's the primary source)
    combined_symbol_map = {**api_symbol_map, **recording_symbol_map}

    # Also collect TYPE_CHECKING imports from both files (symbols only available at type-check time)
    recording_tc_map = _collect_type_checking_import_map(recording_source)
    api_tc_map = _collect_type_checking_import_map(api_source)
    combined_tc_map = {**api_tc_map, **recording_tc_map}

    # Symbols that are always provided by the fixed header (no need to derive dynamically)
    fixed_header_symbols: set[str] = {"Any", "typing", "TYPE_CHECKING", "RecordingApi"}

    # Generate each method; track body nodes for import derivation.
    generated_methods: list[str] = []
    all_body_nodes: list[ast.stmt] = []
    all_runtime_annotation_symbols: set[str] = set()
    all_string_ref_symbols: set[str] = set()

    for api_func in api_methods:
        method_name = api_func.name
        rec_func = recording_async_map.get(method_name)

        # Determine whether to body-copy or stub.
        # RecordingApi methods that only call not_implemented are treated as stubs.
        use_body_copy = rec_func is not None and not is_not_implemented_only(rec_func)

        if use_body_copy:
            assert rec_func is not None
            # Collect annotation symbols from the recording_api signature
            runtime_syms, string_syms = _collect_annotation_symbols(rec_func)
            all_runtime_annotation_symbols |= runtime_syms
            all_string_ref_symbols |= string_syms
            # Body-copy from RecordingApi
            method_src, body_nodes = gen_recording_method(rec_func, async_method_names)
            generated_methods.append(method_src)
            all_body_nodes.extend(body_nodes)
        else:
            # Stub — use the Api signature for the stub type annotations
            runtime_syms, string_syms = _collect_annotation_symbols(api_func)
            all_runtime_annotation_symbols |= runtime_syms
            all_string_ref_symbols |= string_syms
            method_src = gen_recording_stub(api_func)
            generated_methods.append(method_src)

    # Collect all symbols that need to be imported at runtime
    body_symbols = _collect_referenced_symbols(all_body_nodes)
    needed_symbols = (body_symbols | all_runtime_annotation_symbols) - fixed_header_symbols

    # Build a precise import block — only the symbols actually needed, not whole multi-symbol lines
    import_block = _build_precise_import_block(needed_symbols, combined_symbol_map)

    # Build the TYPE_CHECKING block for forward-reference symbols not available at runtime.
    # These are string annotations (quoted types) that only need to be resolvable for type checkers.
    # Also handle symbols from TYPE_CHECKING blocks in source files (like HassStateDict, EntityT).
    # RecordingApi is always included (needed for the class header forward ref, handled in template).
    type_checking_symbols = all_string_ref_symbols - fixed_header_symbols - needed_symbols
    # Build additional TYPE_CHECKING lines from the TC symbol maps
    type_checking_extra_lines: list[str] = []
    for sym in sorted(type_checking_symbols):
        if sym in combined_tc_map:
            # Build a single-symbol import line for this type-checking-only symbol
            precise = _build_precise_import_block({sym}, combined_tc_map)
            if precise:
                type_checking_extra_lines.append(f"    {precise}")
        elif sym in combined_symbol_map:
            # Fall back to runtime symbol map (might be a type not tagged as TC-only)
            precise = _build_precise_import_block({sym}, combined_symbol_map)
            if precise:
                type_checking_extra_lines.append(f"    {precise}")
    type_checking_imports = ("\n" + "\n".join(type_checking_extra_lines) + "\n") if type_checking_extra_lines else "\n"

    # Optional: warn about signature default mismatches. Only applies to body-copied
    # methods — stub-tier methods inherit their signature from Api and never carry
    # RecordingApi defaults, so a "mismatch" there is a false positive that trains
    # developers to ignore the warning entirely.
    for api_func in api_methods:
        if api_func.name in recording_async_map:
            rec_func_check = recording_async_map[api_func.name]
            if is_not_implemented_only(rec_func_check):
                continue
            api_defaults = [ast.unparse(d) for d in api_func.args.defaults]
            rec_defaults = [ast.unparse(d) for d in rec_func_check.args.defaults]
            if api_defaults != rec_defaults:
                print(
                    f"Warning: default mismatch for `{api_func.name}`: "
                    f"Api defaults={api_defaults!r}, RecordingApi defaults={rec_defaults!r}",
                    file=sys.stderr,
                )

    methods_str = "\n".join(generated_methods)

    return (
        _RECORDING_MODULE_HEADER_TEMPLATE.format(
            imports=import_block,
            type_checking_imports=type_checking_imports,
        )
        + _RECORDING_CLASS_HEADER
        + "\n"
        + methods_str
    )
