[hassette]
dev_mode = true
allow_startup_if_app_precheck_fails = true
startup_timeout_seconds = 20
app_startup_timeout_seconds = 40
app_shutdown_timeout_seconds = 20
resource_shutdown_timeout_seconds = 20
task_cancellation_timeout_seconds = 10
run_sync_timeout_seconds = 12
websocket_authentication_timeout_seconds = 20
websocket_response_timeout_seconds = 10
websocket_connection_timeout_seconds = 10
websocket_total_timeout_seconds = 60
websocket_heartbeat_interval_seconds = 60
scheduler_min_delay_seconds = 2
scheduler_max_delay_seconds = 60
scheduler_default_delay_seconds = 30
file_watcher_debounce_milliseconds = 6000
file_watcher_step_milliseconds = 1000
state_proxy_poll_interval_seconds = 15
