[hassette]
dev_mode = false
allow_startup_if_app_precheck_fails = false
startup_timeout_seconds = 10
app_startup_timeout_seconds = 20
app_shutdown_timeout_seconds = 10
resource_shutdown_timeout_seconds = 10
task_cancellation_timeout_seconds = 5
run_sync_timeout_seconds = 6
websocket_authentication_timeout_seconds = 10
websocket_response_timeout_seconds = 5
websocket_connection_timeout_seconds = 5
websocket_total_timeout_seconds = 30
websocket_heartbeat_interval_seconds = 30
scheduler_min_delay_seconds = 1
scheduler_max_delay_seconds = 30
scheduler_default_delay_seconds = 15
file_watcher_debounce_milliseconds = 3000
file_watcher_step_milliseconds = 500
state_proxy_poll_interval_seconds = 30
