[hassette]
dev_mode = true
allow_startup_if_app_precheck_fails = true
state_proxy_poll_interval_seconds = 15

[hassette.lifecycle]
startup_timeout_seconds = 20
app_startup_timeout_seconds = 40
app_shutdown_timeout_seconds = 20
resource_shutdown_timeout_seconds = 20
task_cancellation_timeout_seconds = 10
run_sync_timeout_seconds = 12

[hassette.websocket]
authentication_timeout_seconds = 20
response_timeout_seconds = 30
connection_timeout_seconds = 10
total_timeout_seconds = 80
heartbeat_interval_seconds = 60

[hassette.scheduler]
min_delay_seconds = 2
max_delay_seconds = 60
default_delay_seconds = 30

[hassette.file_watcher]
debounce_milliseconds = 6000
step_milliseconds = 1000
