services:
  test-homeassistant:
    user: "0:0"

  hassette:
    # Reuse same build/image from docker-compose.yml
    volumes:
      # Mount your local source tree into the container
      - ./src:/app/src:cached

      # Mount config/data
      - ./tests/data:/config
      - ./tests/data:/data

    environment:
      - HASSETTE__LOG_LEVEL=debug
      - HASSETTE__CONFIG_DIR=/config
      - HASSETTE__DATA_DIR=/data
      - HASSETTE__APP_DIR=/apps
      - HASSETTE__BASE_URL=http://test-homeassistant:8123
      # Make Python look at /app/src first
      - PYTHONPATH=/app/src

    depends_on:
      test-homeassistant:
        condition: service_healthy

    entrypoint: ["/app/.venv/bin/python", "-m", "hassette"]
    command: ["run"]
