/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Return the full system status. Always HTTP 200 while the process can serve.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live */
        get: operations["get_live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ready
         * @description Return readiness status. 200 only when aggregate status is 'ok', else 503.
         */
        get: operations["get_ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Apps */
        get: operations["get_apps_api_apps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/manifests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Manifests */
        get: operations["get_app_manifests_api_apps_manifests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Manifest */
        get: operations["get_app_manifest_api_apps__app_key__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start App */
        post: operations["start_app_api_apps__app_key__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop App */
        post: operations["stop_app_api_apps__app_key__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload App */
        post: operations["reload_app_api_apps__app_key__reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App Config
         * @description Return the app configuration with schema-driven masking for the given app key.
         *
         *     Secret fields are masked by type: any field declared ``SecretStr`` is replaced
         *     by a masked placeholder; plain ``str`` fields are never masked by name.
         *     The ``config_schema`` is fully inlined (no ``$ref`` nodes remain).
         *
         *     Masking needs the app's config schema. It comes from the running instance when the
         *     app is active, otherwise from the app class if it has already been loaded. When no
         *     schema can be obtained (a disabled app whose class was never loaded, or a class whose
         *     schema generation fails), every string value is masked as a safe floor so no secret
         *     leaks — the masked path is the only path.
         */
        get: operations["get_app_config_api_apps__app_key__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App Source
         * @description Return the source code of the app file for the given app key.
         */
        get: operations["get_app_source_api_apps__app_key__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Logs
         * @description Return recent log records from the database with optional filtering.
         */
        get: operations["get_logs_api_logs_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Log Level
         * @description Change a logger's effective level at runtime without restarting.
         *
         *     The change takes effect immediately for both structlog and stdlib callers on that logger.
         */
        put: operations["set_log_level_api_logs_level_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Execution Logs
         * @description Return all log records for a single execution, with retention-expired detection.
         *
         *     For UUIDv7 execution IDs, the embedded timestamp is extracted directly without a
         *     database lookup. For historical UUIDv4 IDs, the database is queried to determine
         *     whether retention has expired.
         *
         *     Returns 422 if the execution_id is not a valid UUID. Returns an empty record list
         *     with ``retention_expired=True`` if logs have been purged by retention policy.
         */
        get: operations["get_execution_logs_api_executions__execution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bus/listeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Listener Metrics */
        get: operations["get_listener_metrics_api_bus_listeners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return the complete Hassette configuration as a JSON schema plus current values.
         *
         *     ``config_schema`` is the fully-inlined JSON schema derived from the
         *     ``HassetteConfig`` class (all ``$ref``/``$defs`` resolved server-side).
         *     ``config_values`` is the current configuration serialized to JSON with
         *     any ``SecretStr`` field replaced by a masked placeholder — the plaintext
         *     value is never sent over the wire. Every field and nested group is present;
         *     nothing is omitted.
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Telemetry Status
         * @description Health check for the telemetry database.
         *
         *     Runs a representative query against the unified ``executions`` table.
         *     Returns 503 with ``degraded: true`` when the database is
         *     unavailable; 200 with ``degraded: false`` when healthy.
         */
        get: operations["telemetry_status_api_telemetry_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/app/{app_key}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Health
         * @description Health strip metrics for a single app instance.
         */
        get: operations["app_health_api_telemetry_app__app_key__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/app/{app_key}/listeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Listeners
         * @description Listener metrics with human-readable handler summaries.
         */
        get: operations["app_listeners_api_telemetry_app__app_key__listeners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/app/{app_key}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Activity
         * @description Recent handler invocations and job executions for a single app, merged and sorted by time.
         */
        get: operations["app_activity_api_telemetry_app__app_key__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/app/{app_key}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Jobs
         * @description Job summaries for a single app instance, enriched with live heap data.
         *
         *     Live fields (``next_run``, ``fire_at``, ``jitter``) are joined
         *     from the live scheduler heap by ``db_id``. On heap failure the DB rows are
         *     returned without enrichment (degraded but functional; logged warning, no 500).
         */
        get: operations["app_jobs_api_telemetry_app__app_key__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Executions
         * @description Combined execution list (handler invocations and job executions).
         *
         *     Filter by ``kind=handler`` or ``kind=job`` to restrict to one type.
         *     Each record includes a ``kind`` field that discriminates the execution type.
         */
        get: operations["list_executions_api_telemetry_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/listener/{listener_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listener Executions
         * @description Execution history for a specific listener (handler invocations).
         */
        get: operations["listener_executions_api_telemetry_listener__listener_id__executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/job/{job_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Executions
         * @description Execution history for a specific job.
         */
        get: operations["job_executions_api_telemetry_job__job_id__executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/dashboard/app-grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard App Grid
         * @description Per-app health data for the dashboard grid.
         *
         *     Always uses ``source_tier='app'`` — framework actors are shown via FrameworkHealth,
         *     not the manifest-driven app grid.
         */
        get: operations["dashboard_app_grid_api_telemetry_dashboard_app_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Jobs
         * @description All scheduled jobs across all apps, enriched with live heap data.
         *
         *     Live fields (``next_run``, ``fire_at``, ``jitter``) are joined
         *     from the live scheduler heap by ``db_id``.  On heap failure the DB rows are
         *     returned without enrichment (degraded but functional; logged warning, no 500).
         *
         *     The heap snapshot is taken once — not per app — to avoid fan-out overhead.
         */
        get: operations["all_jobs_api_scheduler_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/jobs/{job_id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Job
         * @description Manually trigger a scheduled job to run immediately.
         *
         *     Looks up the job on the live scheduler heap by ``job_id`` (the job's ``db_id``). Returns
         *     202 and dispatches the job through the same ``run_job_with_guard()`` path as a scheduled
         *     fire, recording the execution with ``trigger_mode="manual"``. Returns 409 when the job
         *     is not currently triggerable (already fired, mid-execution from its scheduled fire, or its
         *     owning app is not running) or when a ``SINGLE``-mode job is currently executing.
         *
         *     A still-pending one-shot job (``After``/``Once`` trigger) is dequeued from the heap
         *     before dispatch to prevent a second scheduled fire at its original time.
         */
        post: operations["trigger_job_api_scheduler_jobs__job_id__trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionResponse
         * @description Response for app mutation endpoints (start/stop/reload).
         */
        ActionResponse: {
            /**
             * Status
             * @default accepted
             * @constant
             */
            status: "accepted";
            /** App Key */
            app_key: string;
            /** Action */
            action: string;
        };
        /**
         * ActivityBucket
         * @description A single time-window bucket for the sparkline chart.
         */
        ActivityBucket: {
            /** Ok */
            ok: number;
            /** Err */
            err: number;
        };
        /**
         * ActivityFeedEntry
         * @description A single activity entry for the cross-app recent activity feed.
         */
        ActivityFeedEntry: {
            /** Row Id */
            row_id: string;
            status: components["schemas"]["ExecutionStatus"];
            /** Timestamp */
            timestamp: number;
            /** App Key */
            app_key: string;
            /** Handler Name */
            handler_name: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Type */
            error_type?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "handler" | "job";
        };
        /**
         * AppConfigResponse
         * @description Response model for GET /apps/{app_key}/config.
         */
        AppConfigResponse: {
            /** App Key */
            app_key: string;
            /** Filename */
            filename: string;
            /** Class Name */
            class_name: string;
            /** Enabled */
            enabled: boolean;
            /** Autostart */
            autostart: boolean;
            /** App Config */
            app_config: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            }[];
            /** Config Schema */
            config_schema?: {
                [key: string]: unknown;
            } | null;
            /** Framework Fields */
            framework_fields: string[];
        };
        /**
         * AppHealthResponse
         * @description Health metrics for a single app instance.
         */
        AppHealthResponse: {
            /** Error Rate */
            error_rate: number;
            /**
             * Error Rate Class
             * @enum {string}
             */
            error_rate_class: "good" | "warn" | "bad";
            /** Handler Avg Duration */
            handler_avg_duration: number;
            /** Job Avg Duration */
            job_avg_duration: number;
            /** Last Activity Ts */
            last_activity_ts: number | null;
            /**
             * Health Status
             * @enum {string}
             */
            health_status: "excellent" | "good" | "warning" | "critical";
        };
        /** AppInstanceResponse */
        AppInstanceResponse: {
            /** App Key */
            app_key: string;
            /** Index */
            index: number;
            /** Instance Name */
            instance_name: string;
            /** Class Name */
            class_name: string;
            status: components["schemas"]["ResourceStatus"];
            /** Error Message */
            error_message?: string | null;
            /** Error Traceback */
            error_traceback?: string | null;
            /** Owner Id */
            owner_id?: string | null;
        };
        /** AppManifestListResponse */
        AppManifestListResponse: {
            /** Total */
            total: number;
            /** Running */
            running: number;
            /** Failed */
            failed: number;
            /** Stopped */
            stopped: number;
            /** Disabled */
            disabled: number;
            /** Blocked */
            blocked: number;
            /** Manifests */
            manifests: components["schemas"]["AppManifestResponse"][];
            /** Only App */
            only_app?: string | null;
        };
        /** AppManifestResponse */
        AppManifestResponse: {
            /** App Key */
            app_key: string;
            /** Class Name */
            class_name: string;
            /** Display Name */
            display_name: string;
            /** Filename */
            filename: string;
            /** Enabled */
            enabled: boolean;
            /** Auto Loaded */
            auto_loaded: boolean;
            /**
             * Autostart
             * @default true
             */
            autostart: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "disabled" | "blocked" | "running" | "failed" | "stopped";
            /** Block Reason */
            block_reason?: string | null;
            /**
             * Instance Count
             * @description Tracked instances (running/failed). 0 = none tracked (stopped/disabled).
             * @default 0
             */
            instance_count: number;
            /** Instances */
            instances?: components["schemas"]["AppInstanceResponse"][];
            /** Error Message */
            error_message?: string | null;
            /** Error Traceback */
            error_traceback?: string | null;
            /**
             * Recent Invocations 1H
             * @description Total handler invocations in the last hour across all instances.
             * @default 0
             */
            recent_invocations_1h: number;
        };
        /**
         * AppSourceResponse
         * @description Response model for GET /apps/{app_key}/source.
         */
        AppSourceResponse: {
            /** App Key */
            app_key: string;
            /** Filename */
            filename: string;
            /** Content */
            content: string;
            /** Line Count */
            line_count: number;
        };
        /** AppStatusResponse */
        AppStatusResponse: {
            /** Total */
            total: number;
            /** Running */
            running: number;
            /** Failed */
            failed: number;
            /** Apps */
            apps: components["schemas"]["AppInstanceResponse"][];
            /** Only App */
            only_app?: string | null;
        };
        /**
         * BackpressurePolicy
         * @description What a listener does when the *global* dispatch semaphore is saturated.
         *
         *     The semaphore is shared by all listeners across all apps — saturation means
         *     the whole bus is at capacity, not that this listener alone is busy. This is
         *     distinct from per-listener rate controls (``debounce``, ``throttle``, ``mode``),
         *     which operate inside the handler invoker after a dispatch slot is acquired.
         * @enum {string}
         */
        BackpressurePolicy: "block" | "drop_newest";
        /**
         * BootIssueResponse
         * @description A boot-time issue entry in the system status response.
         */
        BootIssueResponse: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "err" | "warn";
            /** Label */
            label: string;
            /** Detail */
            detail: string;
        };
        /**
         * ConfigSchemaResponse
         * @description Complete Hassette configuration as a JSON schema plus current values.
         *
         *     ``config_schema`` is the fully-inlined JSON schema (all ``$ref``/``$defs`` resolved)
         *     derived from ``HassetteConfig.model_json_schema()``.  ``config_values`` is the current
         *     configuration serialized to JSON with ``SecretStr`` fields replaced by a masked
         *     placeholder.  Every field and nested group is present — nothing is omitted.
         */
        ConfigSchemaResponse: {
            /** Config Schema */
            config_schema: {
                [key: string]: unknown;
            };
            /** Config Values */
            config_values: {
                [key: string]: unknown;
            };
        };
        /**
         * DashboardAppGridEntry
         * @description Per-app health entry for the dashboard grid.
         */
        DashboardAppGridEntry: {
            /** App Key */
            app_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "disabled" | "blocked" | "running" | "failed" | "stopped";
            /** Display Name */
            display_name: string;
            /**
             * Instance Count
             * @description Tracked instances (running/failed). 0 = none tracked (stopped/disabled).
             * @default 0
             */
            instance_count: number;
            /** Handler Count */
            handler_count: number;
            /** Job Count */
            job_count: number;
            /** Total Invocations */
            total_invocations: number;
            /** Total Errors */
            total_errors: number;
            /**
             * Total Timed Out
             * @default 0
             */
            total_timed_out: number;
            /** Total Executions */
            total_executions: number;
            /** Total Job Errors */
            total_job_errors: number;
            /**
             * Total Job Timed Out
             * @default 0
             */
            total_job_timed_out: number;
            /** Avg Duration Ms */
            avg_duration_ms: number;
            /** Last Activity Ts */
            last_activity_ts: number | null;
            /**
             * Health Status
             * @enum {string}
             */
            health_status: "excellent" | "good" | "warning" | "critical";
            /** Error Rate */
            error_rate: number;
            /**
             * Error Rate Class
             * @enum {string}
             */
            error_rate_class: "good" | "warn" | "bad";
            /** Activity Buckets */
            activity_buckets?: components["schemas"]["ActivityBucket"][];
            /** Last Error Message */
            last_error_message?: string | null;
            /** Last Error Type */
            last_error_type?: string | null;
            /** Last Error Ts */
            last_error_ts?: number | null;
        };
        /**
         * DashboardAppGridResponse
         * @description Dashboard app grid with per-app health data.
         */
        DashboardAppGridResponse: {
            /** Apps */
            apps: components["schemas"]["DashboardAppGridEntry"][];
        };
        /**
         * Execution
         * @description Unified execution record returned by queries against the ``executions`` table.
         *
         *     Replaces the split ``HandlerInvocation`` / ``JobExecution`` models.
         *     ``kind`` discriminates between handler invocations and job executions.
         *     Handler-only fields (``trigger_context_id``, ``trigger_origin``) default to
         *     ``None`` for job executions.
         */
        Execution: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "handler" | "job";
            /** Listener Id */
            listener_id?: number | null;
            /** Job Id */
            job_id?: number | null;
            /** Execution Start Ts */
            execution_start_ts: number;
            /** Duration Ms */
            duration_ms: number;
            status: components["schemas"]["ExecutionStatus"];
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /** Error Type */
            error_type: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Traceback */
            error_traceback?: string | null;
            /** Execution Id */
            execution_id?: string | null;
            /** Trigger Context Id */
            trigger_context_id?: string | null;
            /** Trigger Origin */
            trigger_origin?: string | null;
            /** Trigger Mode */
            trigger_mode?: string | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Attempt Number
             * @default 1
             */
            attempt_number: number;
            /**
             * Args Json
             * @default []
             */
            args_json: string;
            /**
             * Kwargs Json
             * @default {}
             */
            kwargs_json: string;
            /**
             * Thread Leaked
             * @default false
             */
            thread_leaked: boolean;
        };
        /**
         * ExecutionMode
         * @description Overlap behavior for a listener when a trigger fires while a prior invocation still runs.
         * @enum {string}
         */
        ExecutionMode: "single" | "restart" | "queued" | "parallel";
        /**
         * ExecutionStatus
         * @description Status values for handler invocations and job executions.
         *
         *     Covers all values allowed by the CHECK constraints in migrations 001 and 005.
         *     Pydantic v2 coerces plain strings to enum members on construction and
         *     serialises back to plain strings in JSON responses.
         * @enum {string}
         */
        ExecutionStatus: "success" | "error" | "cancelled" | "timed_out" | "skipped";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobSummary
         * @description Per-job summary returned by ``get_job_summary()``.
         *
         *     ``failed`` counts only ``'error'`` status; ``timed_out``, ``cancelled``, and ``skipped``
         *     are tracked separately.
         *     Invariant: ``successful + failed + cancelled + timed_out + skipped == total_executions``.
         */
        JobSummary: {
            /** Job Id */
            job_id: number;
            /** App Key */
            app_key: string;
            /** Instance Index */
            instance_index: number;
            /** Job Name */
            job_name: string;
            /** Handler Method */
            handler_method: string;
            /** Trigger Type */
            trigger_type: string | null;
            /**
             * Trigger Label
             * @default
             */
            trigger_label: string;
            /** Trigger Detail */
            trigger_detail?: string | null;
            /** Args Json */
            args_json: string;
            /** Kwargs Json */
            kwargs_json: string;
            /** Source Location */
            source_location: string;
            /** Registration Source */
            registration_source: string | null;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /** Predicate Description */
            predicate_description?: string | null;
            /** Human Description */
            human_description?: string | null;
            /** Total Executions */
            total_executions: number;
            /** Successful */
            successful: number;
            /** Failed */
            failed: number;
            /**
             * Cancelled
             * @default 0
             */
            cancelled: number;
            /**
             * Timed Out
             * @default 0
             */
            timed_out: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Thread Leaked
             * @default 0
             */
            thread_leaked: number;
            /** Last Executed At */
            last_executed_at: number | null;
            /** Total Duration Ms */
            total_duration_ms: number;
            /** Avg Duration Ms */
            avg_duration_ms: number;
            /** Group */
            group?: string | null;
            /** Next Run */
            next_run?: number | null;
            /** Fire At */
            fire_at?: number | null;
            /** Jitter */
            jitter?: number | null;
            /** Last Error Message */
            last_error_message?: string | null;
            /** Last Error Type */
            last_error_type?: string | null;
            /** Last Error Ts */
            last_error_ts?: number | null;
            /** Last Error Traceback */
            last_error_traceback?: string | null;
            /** Min Duration Ms */
            min_duration_ms?: number | null;
            /** Max Duration Ms */
            max_duration_ms?: number | null;
            /** @default single */
            mode: components["schemas"]["ExecutionMode"];
            /**
             * Suppressed Count
             * @default 0
             */
            suppressed_count: number;
            /**
             * Dropped Count
             * @default 0
             */
            dropped_count: number;
        };
        /**
         * JobTriggerResponse
         * @description Response for POST /api/scheduler/jobs/{job_id}/trigger.
         *
         *     Separate from ``ActionResponse`` (which has ``app_key``/``action`` but no ``job_id``) —
         *     the trigger response identifies the job, not an app action.
         */
        JobTriggerResponse: {
            /**
             * Status
             * @default accepted
             * @constant
             */
            status: "accepted";
            /** Job Id */
            job_id: number;
            /** Job Name */
            job_name: string;
        };
        /**
         * ListenerWithSummary
         * @description Listener metrics enriched with human-readable handler summary.
         */
        ListenerWithSummary: {
            /** Listener Id */
            listener_id: number;
            /** App Key */
            app_key: string;
            /**
             * Instance Index
             * @default 0
             */
            instance_index: number;
            /** Topic */
            topic: string;
            /**
             * Listener Kind
             * @default event
             * @enum {string}
             */
            listener_kind: "state change" | "service call" | "event";
            /** Handler Method */
            handler_method: string;
            /** Total Invocations */
            total_invocations: number;
            /** Successful */
            successful: number;
            /** Failed */
            failed: number;
            /** Di Failures */
            di_failures: number;
            /** Cancelled */
            cancelled: number;
            /**
             * Avg Duration Ms
             * @default 0
             */
            avg_duration_ms: number;
            /** Min Duration Ms */
            min_duration_ms?: number | null;
            /** Max Duration Ms */
            max_duration_ms?: number | null;
            /**
             * Total Duration Ms
             * @default 0
             */
            total_duration_ms: number;
            /** Predicate Description */
            predicate_description?: string | null;
            /** Human Description */
            human_description?: string | null;
            /** Debounce */
            debounce?: number | null;
            /** Throttle */
            throttle?: number | null;
            /**
             * Once
             * @default 0
             */
            once: number;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** Last Invoked At */
            last_invoked_at?: number | null;
            /** Last Error Message */
            last_error_message?: string | null;
            /** Last Error Type */
            last_error_type?: string | null;
            /** Last Error Traceback */
            last_error_traceback?: string | null;
            /**
             * Timed Out
             * @default 0
             */
            timed_out: number;
            /**
             * Thread Leaked
             * @default 0
             */
            thread_leaked: number;
            /**
             * Source Location
             * @default
             */
            source_location: string;
            /** Registration Source */
            registration_source?: string | null;
            /**
             * Handler Summary
             * @default
             */
            handler_summary: string;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /**
             * Immediate
             * @default 0
             */
            immediate: number;
            /** Duration */
            duration?: number | null;
            /** Entity Id */
            entity_id?: string | null;
            /** @default single */
            mode: components["schemas"]["ExecutionMode"];
            /**
             * Suppressed Count
             * @default 0
             */
            suppressed_count: number;
            /**
             * Dropped Count
             * @default 0
             */
            dropped_count: number;
            /**
             * Backpressure Dropped Count
             * @default 0
             */
            backpressure_dropped_count: number;
            /** @default block */
            backpressure: components["schemas"]["BackpressurePolicy"];
        };
        /**
         * LivenessResponse
         * @description Response model for GET /api/health/live.
         */
        LivenessResponse: {
            /**
             * Status
             * @default live
             * @constant
             */
            status: "live";
        };
        /** LogEntryResponse */
        LogEntryResponse: {
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: number;
            /**
             * Level
             * @enum {string}
             */
            level: "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL";
            /** Logger Name */
            logger_name: string;
            /** Func Name */
            func_name?: string | null;
            /** Lineno */
            lineno?: number | null;
            /** Message */
            message: string;
            /** Exc Info */
            exc_info?: string | null;
            /** App Key */
            app_key?: string | null;
            /** Execution Id */
            execution_id?: string | null;
            /** Instance Name */
            instance_name?: string | null;
            /** Instance Index */
            instance_index?: number | null;
            /** Source Tier */
            source_tier?: ("app" | "framework") | null;
        };
        /**
         * LogLevelRequest
         * @description Request body for PUT /api/logs/level.
         */
        LogLevelRequest: {
            /** Logger */
            logger: string;
            /** Level */
            level: string;
        };
        /**
         * LogLevelResponse
         * @description Response for PUT /api/logs/level.
         */
        LogLevelResponse: {
            /** Logger */
            logger: string;
            /** Effective Level */
            effective_level: string;
        };
        /**
         * LogsByExecutionResponse
         * @description Response for GET /api/executions/{execution_id}.
         */
        LogsByExecutionResponse: {
            /** Records */
            records: components["schemas"]["LogEntryResponse"][];
            /** Truncated */
            truncated: boolean;
            /** Retention Expired */
            retention_expired: boolean;
        };
        /**
         * ReadinessResponse
         * @description Response model for GET /api/health/ready.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "starting";
            /** Ready */
            ready: boolean;
        };
        /**
         * ResourceStatus
         * @description Enumeration for resource status.
         * @enum {string}
         */
        ResourceStatus: "not_started" | "starting" | "running" | "stopping" | "stopped" | "failed" | "crashed" | "exhausted_dead" | "exhausted_cooling";
        /**
         * ServiceInfoResponse
         * @description Structured info for one internal service.
         */
        ServiceInfoResponse: {
            /** Name */
            name: string;
            status: components["schemas"]["ResourceStatus"];
            /**
             * Role
             * @default
             */
            role: string;
            /** Ready Phase */
            ready_phase?: string | null;
            /** Retry At */
            retry_at?: number | null;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "starting";
            /** Websocket Connected */
            websocket_connected: boolean;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Entity Count */
            entity_count: number;
            /** App Count */
            app_count: number;
            /** Services */
            services?: components["schemas"]["ServiceInfoResponse"][];
            /**
             * Version
             * @default
             */
            version: string;
            /** Boot Issues */
            boot_issues?: components["schemas"]["BootIssueResponse"][];
            /**
             * Log Records Dropped
             * @default 0
             */
            log_records_dropped: number;
        };
        /**
         * TelemetryStatusResponse
         * @description Health check response for the telemetry database.
         */
        TelemetryStatusResponse: {
            /** Degraded */
            degraded: boolean;
            /**
             * Dropped Overflow
             * @default 0
             */
            dropped_overflow: number;
            /**
             * Dropped Exhausted
             * @default 0
             */
            dropped_exhausted: number;
            /**
             * Dropped Shutdown
             * @default 0
             */
            dropped_shutdown: number;
            /**
             * Error Handler Failures
             * @default 0
             */
            error_handler_failures: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    get_live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    get_ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    get_apps_api_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStatusResponse"];
                };
            };
        };
    };
    get_app_manifests_api_apps_manifests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppManifestListResponse"];
                };
            };
        };
    };
    get_app_manifest_api_apps__app_key__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppManifestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_app_api_apps__app_key__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_app_api_apps__app_key__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_app_api_apps__app_key__reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_config_api_apps__app_key__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_source_api_apps__app_key__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_api_logs_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                app_key?: string | null;
                level?: string | null;
                since?: number | null;
                execution_id?: string | null;
                source_tier?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_log_level_api_logs_level_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogLevelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogLevelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_logs_api_executions__execution_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsByExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_listener_metrics_api_bus_listeners_get: {
        parameters: {
            query?: {
                app_key?: string | null;
                /** @description App instance index. Defaults to 0. Multi-instance apps have indices 0..N-1. */
                instance_index?: number;
                since?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: "app" | "framework" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerWithSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSchemaResponse"];
                };
            };
        };
    };
    telemetry_status_api_telemetry_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryStatusResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryStatusResponse"];
                };
            };
        };
    };
    app_health_api_telemetry_app__app_key__health_get: {
        parameters: {
            query?: {
                /** @description App instance index. Defaults to 0. Multi-instance apps have indices 0..N-1. */
                instance_index?: number;
                since?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: "app" | "framework" | "all";
            };
            header?: never;
            path: {
                /** @description Use `__hassette__` to query framework-internal actor telemetry. */
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_listeners_api_telemetry_app__app_key__listeners_get: {
        parameters: {
            query?: {
                /** @description App instance index. Defaults to 0. Multi-instance apps have indices 0..N-1. */
                instance_index?: number;
                since?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: "app" | "framework" | "all";
            };
            header?: never;
            path: {
                /** @description Use `__hassette__` to query framework-internal actor telemetry. */
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerWithSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_activity_api_telemetry_app__app_key__activity_get: {
        parameters: {
            query?: {
                /** @description App instance index. None returns activity across all instances. */
                instance_index?: number | null;
                limit?: number;
                since?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: "app" | "framework" | "all";
            };
            header?: never;
            path: {
                /** @description Use `__hassette__` to query framework-internal actor telemetry. */
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityFeedEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_jobs_api_telemetry_app__app_key__jobs_get: {
        parameters: {
            query?: {
                /** @description App instance index. Defaults to 0. Multi-instance apps have indices 0..N-1. */
                instance_index?: number;
                since?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: "app" | "framework" | "all";
            };
            header?: never;
            path: {
                /** @description Use `__hassette__` to query framework-internal actor telemetry. */
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_executions_api_telemetry_executions_get: {
        parameters: {
            query?: {
                /** @description Filter by kind: 'handler' or 'job'. */
                kind?: ("handler" | "job") | null;
                limit?: number;
                since?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listener_executions_api_telemetry_listener__listener_id__executions_get: {
        parameters: {
            query?: {
                limit?: number;
                since?: number | null;
            };
            header?: never;
            path: {
                listener_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_executions_api_telemetry_job__job_id__executions_get: {
        parameters: {
            query?: {
                limit?: number;
                since?: number | null;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_app_grid_api_telemetry_dashboard_app_grid_get: {
        parameters: {
            query?: {
                since?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardAppGridResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_jobs_api_scheduler_jobs_get: {
        parameters: {
            query?: {
                since?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: "app" | "framework" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_job_api_scheduler_jobs__job_id__trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobTriggerResponse"];
                };
            };
            /** @description Job is not currently triggerable or is already executing */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
