/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Apps */
        get: operations["get_apps_api_apps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/manifests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Manifests */
        get: operations["get_app_manifests_api_apps_manifests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start App */
        post: operations["start_app_api_apps__app_key__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop App */
        post: operations["stop_app_api_apps__app_key__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{app_key}/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload App */
        post: operations["reload_app_api_apps__app_key__reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Services */
        get: operations["get_services_api_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recent Events */
        get: operations["get_recent_events_api_events_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_api_logs_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bus/listeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Listener Metrics */
        get: operations["get_listener_metrics_api_bus_listeners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Return sanitized hassette configuration (allowlisted fields only).
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Telemetry Status
         * @description Health check for the telemetry database.
         *
         *     Runs a representative query exercising the listeners -> handler_invocations
         *     join path. Returns 503 with ``degraded: true`` when the database is
         *     unavailable; 200 with ``degraded: false`` when healthy.
         */
        get: operations["telemetry_status_api_telemetry_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sessions
         * @description List recent sessions with lifecycle data.
         */
        get: operations["sessions_api_telemetry_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/app/{app_key}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Health
         * @description Health strip metrics for a single app instance.
         */
        get: operations["app_health_api_telemetry_app__app_key__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/app/{app_key}/listeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Listeners
         * @description Listener metrics with human-readable handler summaries.
         */
        get: operations["app_listeners_api_telemetry_app__app_key__listeners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/app/{app_key}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Jobs
         * @description Job summaries for a single app instance, enriched with live heap data.
         *
         *     Live fields (``next_run``, ``fire_at``, ``jitter``, ``cancelled``) are joined
         *     from the live scheduler heap by ``db_id``. On heap failure the DB rows are
         *     returned without enrichment (degraded but functional; logged warning, no 500).
         */
        get: operations["app_jobs_api_telemetry_app__app_key__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/handler/{listener_id}/invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handler Invocations
         * @description Invocation history for a specific handler.
         */
        get: operations["handler_invocations_api_telemetry_handler__listener_id__invocations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/job/{job_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Executions
         * @description Execution history for a specific job.
         */
        get: operations["job_executions_api_telemetry_job__job_id__executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Kpis
         * @description Global KPI metrics for the dashboard strip.
         */
        get: operations["dashboard_kpis_api_telemetry_dashboard_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/dashboard/app-grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard App Grid
         * @description Per-app health data for the dashboard grid.
         *
         *     Always uses ``source_tier='app'`` — framework actors are shown via FrameworkHealth,
         *     not the manifest-driven app grid.
         */
        get: operations["dashboard_app_grid_api_telemetry_dashboard_app_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/dashboard/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Errors
         * @description Recent errors for the dashboard error feed.
         */
        get: operations["dashboard_errors_api_telemetry_dashboard_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/dashboard/framework-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Framework Summary
         * @description Framework error counts for the System Health badge.
         *
         *     Always scoped to the last 24 hours. When session_id is provided,
         *     further narrows to errors from that session.
         */
        get: operations["dashboard_framework_summary_api_telemetry_dashboard_framework_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionResponse
         * @description Response for app mutation endpoints (start/stop/reload).
         */
        ActionResponse: {
            /** Status */
            status: string;
            /** App Key */
            app_key: string;
            /** Action */
            action: string;
        };
        /**
         * AppHealthResponse
         * @description Health metrics for a single app instance.
         */
        AppHealthResponse: {
            /** Error Rate */
            error_rate: number;
            /** Error Rate Class */
            error_rate_class: string;
            /** Handler Avg Duration */
            handler_avg_duration: number;
            /** Job Avg Duration */
            job_avg_duration: number;
            /** Last Activity Ts */
            last_activity_ts: number | null;
            /** Health Status */
            health_status: string;
        };
        /** AppInstanceResponse */
        AppInstanceResponse: {
            /** App Key */
            app_key: string;
            /** Index */
            index: number;
            /** Instance Name */
            instance_name: string;
            /** Class Name */
            class_name: string;
            /** Status */
            status: string;
            /** Error Message */
            error_message?: string | null;
            /** Error Traceback */
            error_traceback?: string | null;
            /** Owner Id */
            owner_id?: string | null;
        };
        /** AppManifestListResponse */
        AppManifestListResponse: {
            /** Total */
            total: number;
            /** Running */
            running: number;
            /** Failed */
            failed: number;
            /** Stopped */
            stopped: number;
            /** Disabled */
            disabled: number;
            /** Blocked */
            blocked: number;
            /** Manifests */
            manifests: components["schemas"]["AppManifestResponse"][];
            /** Only App */
            only_app?: string | null;
        };
        /** AppManifestResponse */
        AppManifestResponse: {
            /** App Key */
            app_key: string;
            /** Class Name */
            class_name: string;
            /** Display Name */
            display_name: string;
            /** Filename */
            filename: string;
            /** Enabled */
            enabled: boolean;
            /** Auto Loaded */
            auto_loaded: boolean;
            /** Status */
            status: string;
            /** Block Reason */
            block_reason?: string | null;
            /**
             * Instance Count
             * @description Tracked instances (running/failed). 0 = none tracked (stopped/disabled).
             * @default 0
             */
            instance_count: number;
            /** Instances */
            instances?: components["schemas"]["AppInstanceResponse"][];
            /** Error Message */
            error_message?: string | null;
            /** Error Traceback */
            error_traceback?: string | null;
        };
        /** AppStatusResponse */
        AppStatusResponse: {
            /** Total */
            total: number;
            /** Running */
            running: number;
            /** Failed */
            failed: number;
            /** Apps */
            apps: components["schemas"]["AppInstanceResponse"][];
            /** Only App */
            only_app?: string | null;
        };
        /**
         * ConfigResponse
         * @description Sanitized configuration response (allowlisted fields only).
         */
        ConfigResponse: {
            /**
             * Dev Mode
             * @default false
             */
            dev_mode: boolean;
            /**
             * Log Level
             * @default INFO
             */
            log_level: string;
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Run Web Api
             * @default true
             */
            run_web_api: boolean;
            /**
             * Run Web Ui
             * @default true
             */
            run_web_ui: boolean;
            /**
             * Web Api Host
             * @default 0.0.0.0
             */
            web_api_host: string;
            /**
             * Web Api Port
             * @default 8126
             */
            web_api_port: number;
            /** Web Api Cors Origins */
            web_api_cors_origins?: string[];
            /**
             * Web Api Event Buffer Size
             * @default 500
             */
            web_api_event_buffer_size: number;
            /**
             * Web Api Log Buffer Size
             * @default 2000
             */
            web_api_log_buffer_size: number;
            /**
             * Web Api Job History Size
             * @default 1000
             */
            web_api_job_history_size: number;
            /**
             * Web Api Log Level
             * @default INFO
             */
            web_api_log_level: string;
            /**
             * Autodetect Apps
             * @default true
             */
            autodetect_apps: boolean;
            /**
             * Startup Timeout Seconds
             * @default 10
             */
            startup_timeout_seconds: number;
            /**
             * App Startup Timeout Seconds
             * @default 20
             */
            app_startup_timeout_seconds: number;
            /**
             * App Shutdown Timeout Seconds
             * @default 10
             */
            app_shutdown_timeout_seconds: number;
            /**
             * Watch Files
             * @default true
             */
            watch_files: boolean;
            /**
             * File Watcher Debounce Milliseconds
             * @default 3000
             */
            file_watcher_debounce_milliseconds: number;
            /**
             * Scheduler Min Delay Seconds
             * @default 1
             */
            scheduler_min_delay_seconds: number;
            /**
             * Scheduler Max Delay Seconds
             * @default 30
             */
            scheduler_max_delay_seconds: number;
            /**
             * Scheduler Default Delay Seconds
             * @default 15
             */
            scheduler_default_delay_seconds: number;
            /**
             * Asyncio Debug Mode
             * @default false
             */
            asyncio_debug_mode: boolean;
            /**
             * Allow Reload In Prod
             * @default false
             */
            allow_reload_in_prod: boolean;
            /**
             * Web Ui Hot Reload
             * @default false
             */
            web_ui_hot_reload: boolean;
        };
        /**
         * DashboardAppGridEntry
         * @description Per-app health entry for the dashboard grid.
         */
        DashboardAppGridEntry: {
            /** App Key */
            app_key: string;
            /** Status */
            status: string;
            /** Display Name */
            display_name: string;
            /**
             * Instance Count
             * @description Tracked instances (running/failed). 0 = none tracked (stopped/disabled).
             * @default 0
             */
            instance_count: number;
            /** Handler Count */
            handler_count: number;
            /** Job Count */
            job_count: number;
            /** Total Invocations */
            total_invocations: number;
            /** Total Errors */
            total_errors: number;
            /** Total Executions */
            total_executions: number;
            /** Total Job Errors */
            total_job_errors: number;
            /** Avg Duration Ms */
            avg_duration_ms: number;
            /** Last Activity Ts */
            last_activity_ts: number | null;
            /** Health Status */
            health_status: string;
            /** Error Rate */
            error_rate: number;
            /** Error Rate Class */
            error_rate_class: string;
        };
        /**
         * DashboardAppGridResponse
         * @description Dashboard app grid with per-app health data.
         */
        DashboardAppGridResponse: {
            /** Apps */
            apps: components["schemas"]["DashboardAppGridEntry"][];
        };
        /**
         * DashboardErrorsResponse
         * @description Recent errors for the dashboard error feed.
         */
        DashboardErrorsResponse: {
            /** Errors */
            errors: (components["schemas"]["HandlerErrorEntry"] | components["schemas"]["JobErrorEntry"])[];
        };
        /**
         * DashboardKpisResponse
         * @description Global KPI metrics for the dashboard strip.
         */
        DashboardKpisResponse: {
            /** Total Handlers */
            total_handlers: number;
            /** Total Jobs */
            total_jobs: number;
            /** Total Invocations */
            total_invocations: number;
            /** Total Executions */
            total_executions: number;
            /** Total Errors */
            total_errors: number;
            /** Total Job Errors */
            total_job_errors: number;
            /** Avg Handler Duration Ms */
            avg_handler_duration_ms: number;
            /** Avg Job Duration Ms */
            avg_job_duration_ms: number;
            /** Error Rate */
            error_rate: number;
            /** Error Rate Class */
            error_rate_class: string;
            /** Uptime Seconds */
            uptime_seconds?: number | null;
        };
        /**
         * FrameworkSummaryResponse
         * @description Framework KPI counts for the System Health badge.
         */
        FrameworkSummaryResponse: {
            /** Total Errors */
            total_errors: number;
            /** Total Job Errors */
            total_job_errors: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandlerErrorEntry */
        HandlerErrorEntry: {
            /**
             * Kind
             * @default handler
             * @constant
             */
            kind: "handler";
            /** Listener Id */
            listener_id: number | null;
            /** Topic */
            topic: string | null;
            /** Handler Method */
            handler_method: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Type */
            error_type: string | null;
            /** Execution Start Ts */
            execution_start_ts: number;
            /** App Key */
            app_key: string | null;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /** Error Traceback */
            error_traceback?: string | null;
        };
        /**
         * HandlerInvocation
         * @description Single invocation record returned by ``get_handler_invocations()``.
         */
        HandlerInvocation: {
            /** Execution Start Ts */
            execution_start_ts: number;
            /** Duration Ms */
            duration_ms: number;
            /** Status */
            status: string;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /** Error Type */
            error_type: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Traceback */
            error_traceback?: string | null;
        };
        /** JobErrorEntry */
        JobErrorEntry: {
            /**
             * Kind
             * @default job
             * @constant
             */
            kind: "job";
            /** Job Id */
            job_id: number | null;
            /** Job Name */
            job_name: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Type */
            error_type: string | null;
            /** Execution Start Ts */
            execution_start_ts: number;
            /** App Key */
            app_key: string | null;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /** Error Traceback */
            error_traceback?: string | null;
        };
        /**
         * JobExecution
         * @description Single execution record returned by ``get_job_executions()``.
         */
        JobExecution: {
            /** Execution Start Ts */
            execution_start_ts: number;
            /** Duration Ms */
            duration_ms: number;
            /** Status */
            status: string;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /** Error Type */
            error_type: string | null;
            /** Error Message */
            error_message: string | null;
            /** Error Traceback */
            error_traceback?: string | null;
        };
        /**
         * JobSummary
         * @description Per-job summary returned by ``get_job_summary()``.
         *
         *     ``failed`` counts only ``'error'`` status; ``timed_out`` is tracked separately.
         *     Invariant: ``successful + failed + cancelled + timed_out == total_executions``.
         */
        JobSummary: {
            /** Job Id */
            job_id: number;
            /** App Key */
            app_key: string;
            /** Instance Index */
            instance_index: number;
            /** Job Name */
            job_name: string;
            /** Handler Method */
            handler_method: string;
            /** Trigger Type */
            trigger_type: string | null;
            /**
             * Trigger Label
             * @default
             */
            trigger_label: string;
            /** Trigger Detail */
            trigger_detail?: string | null;
            /** Args Json */
            args_json: string;
            /** Kwargs Json */
            kwargs_json: string;
            /** Source Location */
            source_location: string;
            /** Registration Source */
            registration_source: string | null;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
            /** Total Executions */
            total_executions: number;
            /** Successful */
            successful: number;
            /** Failed */
            failed: number;
            /**
             * Timed Out
             * @default 0
             */
            timed_out: number;
            /** Last Executed At */
            last_executed_at: number | null;
            /** Total Duration Ms */
            total_duration_ms: number;
            /** Avg Duration Ms */
            avg_duration_ms: number;
            /** Group */
            group?: string | null;
            /** Next Run */
            next_run?: number | null;
            /** Fire At */
            fire_at?: number | null;
            /** Jitter */
            jitter?: number | null;
            /**
             * Cancelled
             * @default false
             */
            cancelled: boolean;
        };
        /**
         * ListenerWithSummary
         * @description Listener metrics enriched with human-readable handler summary.
         */
        ListenerWithSummary: {
            /** Listener Id */
            listener_id: number;
            /** App Key */
            app_key: string;
            /**
             * Instance Index
             * @default 0
             */
            instance_index: number;
            /** Topic */
            topic: string;
            /** Handler Method */
            handler_method: string;
            /** Total Invocations */
            total_invocations: number;
            /** Successful */
            successful: number;
            /** Failed */
            failed: number;
            /** Di Failures */
            di_failures: number;
            /** Cancelled */
            cancelled: number;
            /**
             * Avg Duration Ms
             * @default 0
             */
            avg_duration_ms: number;
            /**
             * Min Duration Ms
             * @default 0
             */
            min_duration_ms: number;
            /**
             * Max Duration Ms
             * @default 0
             */
            max_duration_ms: number;
            /**
             * Total Duration Ms
             * @default 0
             */
            total_duration_ms: number;
            /** Predicate Description */
            predicate_description?: string | null;
            /** Human Description */
            human_description?: string | null;
            /** Debounce */
            debounce?: number | null;
            /** Throttle */
            throttle?: number | null;
            /**
             * Once
             * @default 0
             */
            once: number;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** Last Invoked At */
            last_invoked_at?: number | null;
            /** Last Error Message */
            last_error_message?: string | null;
            /** Last Error Type */
            last_error_type?: string | null;
            /**
             * Source Location
             * @default
             */
            source_location: string;
            /** Registration Source */
            registration_source?: string | null;
            /**
             * Handler Summary
             * @default
             */
            handler_summary: string;
            /**
             * Source Tier
             * @default app
             * @enum {string}
             */
            source_tier: "app" | "framework";
        };
        /** LogEntryResponse */
        LogEntryResponse: {
            /** Seq */
            seq: number;
            /** Timestamp */
            timestamp: number;
            /** Level */
            level: string;
            /** Logger Name */
            logger_name: string;
            /** Func Name */
            func_name: string;
            /** Lineno */
            lineno: number;
            /** Message */
            message: string;
            /** Exc Info */
            exc_info?: string | null;
            /** App Key */
            app_key?: string | null;
        };
        /**
         * SessionRecord
         * @description Single session record returned by ``get_session_list()``.
         */
        SessionRecord: {
            /** Id */
            id: number;
            /** Started At */
            started_at: number;
            /** Stopped At */
            stopped_at: number | null;
            /** Status */
            status: string;
            /** Error Type */
            error_type: string | null;
            /** Error Message */
            error_message: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Dropped Overflow
             * @default 0
             */
            dropped_overflow: number;
            /**
             * Dropped Exhausted
             * @default 0
             */
            dropped_exhausted: number;
            /**
             * Dropped No Session
             * @default 0
             */
            dropped_no_session: number;
            /**
             * Dropped Shutdown
             * @default 0
             */
            dropped_shutdown: number;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Status */
            status: string;
            /** Websocket Connected */
            websocket_connected: boolean;
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Entity Count */
            entity_count: number;
            /** App Count */
            app_count: number;
            /** Services Running */
            services_running: string[];
        };
        /**
         * TelemetryStatusResponse
         * @description Health check response for the telemetry database.
         */
        TelemetryStatusResponse: {
            /** Degraded */
            degraded: boolean;
            /**
             * Dropped Overflow
             * @default 0
             */
            dropped_overflow: number;
            /**
             * Dropped Exhausted
             * @default 0
             */
            dropped_exhausted: number;
            /**
             * Dropped No Session
             * @default 0
             */
            dropped_no_session: number;
            /**
             * Dropped Shutdown
             * @default 0
             */
            dropped_shutdown: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    get_apps_api_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStatusResponse"];
                };
            };
        };
    };
    get_app_manifests_api_apps_manifests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppManifestListResponse"];
                };
            };
        };
    };
    start_app_api_apps__app_key__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_app_api_apps__app_key__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_app_api_apps__app_key__reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_services_api_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_recent_events_api_events_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_api_logs_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                app_key?: string | null;
                level?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_listener_metrics_api_bus_listeners_get: {
        parameters: {
            query?: {
                app_key?: string | null;
                instance_index?: number;
                session_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerWithSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    telemetry_status_api_telemetry_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryStatusResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryStatusResponse"];
                };
            };
        };
    };
    sessions_api_telemetry_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_health_api_telemetry_app__app_key__health_get: {
        parameters: {
            query?: {
                instance_index?: number;
                session_id?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: ("app" | "framework" | "all") | null;
            };
            header?: never;
            path: {
                /** @description Use `__hassette__` to query framework-internal actor telemetry. */
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppHealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_listeners_api_telemetry_app__app_key__listeners_get: {
        parameters: {
            query?: {
                instance_index?: number;
                session_id?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: ("app" | "framework" | "all") | null;
            };
            header?: never;
            path: {
                /** @description Use `__hassette__` to query framework-internal actor telemetry. */
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerWithSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_jobs_api_telemetry_app__app_key__jobs_get: {
        parameters: {
            query?: {
                instance_index?: number;
                session_id?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: ("app" | "framework" | "all") | null;
            };
            header?: never;
            path: {
                /** @description Use `__hassette__` to query framework-internal actor telemetry. */
                app_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    handler_invocations_api_telemetry_handler__listener_id__invocations_get: {
        parameters: {
            query?: {
                limit?: number;
                session_id?: number | null;
            };
            header?: never;
            path: {
                listener_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandlerInvocation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_executions_api_telemetry_job__job_id__executions_get: {
        parameters: {
            query?: {
                limit?: number;
                session_id?: number | null;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobExecution"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_kpis_api_telemetry_dashboard_kpis_get: {
        parameters: {
            query?: {
                session_id?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: ("app" | "framework" | "all") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardKpisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_app_grid_api_telemetry_dashboard_app_grid_get: {
        parameters: {
            query?: {
                session_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardAppGridResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_errors_api_telemetry_dashboard_errors_get: {
        parameters: {
            query?: {
                session_id?: number | null;
                /** @description Filter by source tier. 'app' excludes framework internals. 'framework' returns only internal actors. 'all' returns everything. */
                source_tier?: ("app" | "framework" | "all") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardErrorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_framework_summary_api_telemetry_dashboard_framework_summary_get: {
        parameters: {
            query?: {
                session_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
