name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? Be specific.
      placeholder: "When I do X, Y happens instead of Z."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Configure ...
        2. Start Hassette
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or log output if available.
    validations:
      required: true

  - type: input
    id: hassette-version
    attributes:
      label: Hassette Version
      placeholder: "e.g., 0.5.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "e.g., 3.12.1"
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      placeholder: "e.g., 2025.12.0 (leave blank if N/A)"

  - type: input
    id: os
    attributes:
      label: OS / Platform
      placeholder: "e.g., Ubuntu 24.04, Docker, macOS 15"

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Config snippets, logs, screenshots, or anything else that helps.
