name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to add?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why would it be useful?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should it work? Include code examples if helpful.
      render: python

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you thought about?

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this feature is done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2

  - type: dropdown
    id: contribute
    attributes:
      label: Would you be willing to contribute this feature?
      options:
        - "Yes, I can implement it"
        - "I can help test it"
        - "Just suggesting"
    validations:
      required: true
