services:
  hassette:
    image: ghcr.io/nodejsmith/hassette:latest-py3.13
    environment:
      HASSETTE_DOCKER_INSTALL_DEPS: "1"
    volumes:
      - ./config:/config
      - data:/data
      - uv_cache:/uv_cache

volumes:
  uv_cache:
  data:
