"""Unit tests for app_manifests repository: manifest_insert_params() and upsert_app_manifest().

Manifest metadata survives process restarts via a dedicated app_manifests table and upsert path.
"""

import asyncio
from pathlib import Path
from unittest.mock import MagicMock

import aiosqlite

from hassette.core.telemetry.query_service import TelemetryQueryService
from hassette.core.telemetry.repository import TelemetryRepository, manifest_insert_params
from hassette.test_utils import create_app_manifest


async def _table_columns(db: aiosqlite.Connection, table: str) -> set[str]:
    cursor = await db.execute(f"PRAGMA table_info({table})")
    rows = await cursor.fetchall()
    return {row["name"] for row in rows}


def _make_manifest_query_service(telemetry_db: aiosqlite.Connection) -> TelemetryQueryService:
    """Build a TelemetryQueryService with its read connection pointed at telemetry_db.

    Bypasses Resource.__init__ (matches the make_bus_service/make_scheduler_service
    bypass pattern in this directory's conftest.py) since exercising the query methods
    doesn't need the full Resource lifecycle -- only self.hassette.database_service.read_db
    and self.hassette.config.database.read_timeout_seconds are read by execute().
    """
    query_service = TelemetryQueryService.__new__(TelemetryQueryService)
    stub = MagicMock()
    stub.config.database.read_timeout_seconds = 5.0
    stub.database_service.read_db = telemetry_db
    query_service.hassette = stub
    return query_service


def test_manifest_insert_params_produces_correct_dict(tmp_path: Path) -> None:
    """manifest_insert_params() maps AppManifest fields to the UPSERT param dict, coercing bools to int."""
    manifest = create_app_manifest("test", tmp_path, enabled=False)
    manifest.autostart = False
    manifest.auto_loaded = True

    params = manifest_insert_params(manifest)

    assert params == {
        "app_key": manifest.app_key,
        "class_name": manifest.class_name,
        "display_name": manifest.display_name,
        "filename": manifest.filename,
        "enabled": 0,
        "autostart": 0,
        "auto_loaded": 1,
    }
    assert isinstance(params["enabled"], int)
    assert not isinstance(params["enabled"], bool)


async def test_manifest_insert_params_schema_parity(
    telemetry_db: aiosqlite.Connection,
    tmp_path: Path,
) -> None:
    """manifest_insert_params() keys must match the app_manifests UPSERT column set.

    Excludes id (autogenerated) and created_at/updated_at (column defaults / explicit
    refresh on conflict, never supplied as INSERT params) -- catches schema drift between
    the param builder and the migration at test time, matching the pattern used for
    listener_insert_params/job_insert_params in tests/unit/core/test_param_builders.py.
    """
    manifest = create_app_manifest("parity", tmp_path)
    params = manifest_insert_params(manifest)

    table_cols = await _table_columns(telemetry_db, "app_manifests")
    expected_keys = table_cols - {"id", "created_at", "updated_at"}
    assert set(params) == expected_keys


async def test_upsert_app_manifest_creates_new_row(
    telemetry_repo: TelemetryRepository,
    telemetry_db: aiosqlite.Connection,
    tmp_path: Path,
) -> None:
    """upsert_app_manifest() inserts a new row and returns a valid positive integer ID."""
    manifest = create_app_manifest("new", tmp_path)

    manifest_id = await telemetry_repo.upsert_app_manifest(manifest)

    assert isinstance(manifest_id, int)
    assert manifest_id > 0

    cursor = await telemetry_db.execute(
        "SELECT app_key, class_name, display_name, filename FROM app_manifests WHERE id = ?", (manifest_id,)
    )
    row = await cursor.fetchone()
    assert row is not None
    assert row["app_key"] == manifest.app_key
    assert row["class_name"] == manifest.class_name
    assert row["display_name"] == manifest.display_name
    assert row["filename"] == manifest.filename


async def test_upsert_app_manifest_updates_existing_row_preserves_id(
    telemetry_repo: TelemetryRepository,
    telemetry_db: aiosqlite.Connection,
    tmp_path: Path,
) -> None:
    """Re-upserting the same app_key updates the row in place and preserves the row ID."""
    manifest = create_app_manifest("update", tmp_path)
    first_id = await telemetry_repo.upsert_app_manifest(manifest)

    manifest.display_name = "Renamed App"
    second_id = await telemetry_repo.upsert_app_manifest(manifest)

    assert second_id == first_id

    cursor = await telemetry_db.execute("SELECT display_name FROM app_manifests WHERE id = ?", (first_id,))
    row = await cursor.fetchone()
    assert row is not None
    assert row["display_name"] == "Renamed App"

    cursor = await telemetry_db.execute(
        "SELECT COUNT(*) AS count FROM app_manifests WHERE app_key = ?", (manifest.app_key,)
    )
    row = await cursor.fetchone()
    assert row["count"] == 1, "Upsert should produce a single row, not two inserts"


async def test_upsert_app_manifest_refreshes_updated_at_on_conflict(
    telemetry_repo: TelemetryRepository,
    telemetry_db: aiosqlite.Connection,
    tmp_path: Path,
) -> None:
    """updated_at is refreshed on conflict, not frozen at the first insert's value.

    Column DEFAULT expressions only fire on INSERT, not on DO UPDATE SET -- this guards
    against the DO UPDATE SET clause silently omitting the explicit updated_at refresh.
    """
    manifest = create_app_manifest("touch", tmp_path)
    manifest_id = await telemetry_repo.upsert_app_manifest(manifest)

    cursor = await telemetry_db.execute("SELECT updated_at FROM app_manifests WHERE id = ?", (manifest_id,))
    row = await cursor.fetchone()
    assert row is not None
    first_updated_at = row["updated_at"]

    await asyncio.sleep(0.05)

    manifest.display_name = "Touched App"
    await telemetry_repo.upsert_app_manifest(manifest)

    cursor = await telemetry_db.execute("SELECT updated_at FROM app_manifests WHERE id = ?", (manifest_id,))
    row = await cursor.fetchone()
    assert row is not None
    second_updated_at = row["updated_at"]

    assert second_updated_at != first_updated_at, (
        "updated_at should change on re-upsert, not stay frozen at insert time"
    )


async def test_get_all_app_manifests_returns_all_rows(
    telemetry_repo: TelemetryRepository,
    telemetry_db: aiosqlite.Connection,
    tmp_path: Path,
) -> None:
    """get_all_app_manifests() returns every persisted manifest row as a dict."""
    manifest_a = create_app_manifest("a", tmp_path)
    manifest_b = create_app_manifest("b", tmp_path)
    await telemetry_repo.upsert_app_manifest(manifest_a)
    await telemetry_repo.upsert_app_manifest(manifest_b)

    query_service = _make_manifest_query_service(telemetry_db)
    rows = await query_service.get_all_app_manifests()

    app_keys = {row["app_key"] for row in rows}
    assert app_keys == {manifest_a.app_key, manifest_b.app_key}


async def test_get_app_manifest_returns_single_row_or_none(
    telemetry_repo: TelemetryRepository,
    telemetry_db: aiosqlite.Connection,
    tmp_path: Path,
) -> None:
    """get_app_manifest() returns the matching row for a known app_key, None otherwise."""
    manifest = create_app_manifest("solo", tmp_path)
    await telemetry_repo.upsert_app_manifest(manifest)

    query_service = _make_manifest_query_service(telemetry_db)

    found = await query_service.get_app_manifest(manifest.app_key)
    assert found is not None
    assert found["app_key"] == manifest.app_key
    assert found["class_name"] == manifest.class_name

    missing = await query_service.get_app_manifest("does_not_exist")
    assert missing is None
