"""Wire contract for the Hassette HTTP and WebSocket API."""

from hassette_wire.apps import (
    ActionResponse,
    AppConfigResponse,
    AppInstanceResponse,
    AppManifestListResponse,
    AppManifestResponse,
    AppSourceResponse,
    AppStatusResponse,
)
from hassette_wire.auth import MAX_SESSION_TOKEN_LENGTH, SessionRequest, SessionResponse
from hassette_wire.cli_format import CliFormat, CliFormatStyle
from hassette_wire.config import ConfigSchemaResponse
from hassette_wire.enums import BackpressurePolicy, ExecutionMode, ExecutionStatus, ManifestStatus, ResourceStatus
from hassette_wire.health import (
    BootIssueResponse,
    LivenessResponse,
    ReadinessResponse,
    ServiceInfoResponse,
    SystemStatusResponse,
)
from hassette_wire.literals import (
    LOG_LEVEL_TYPE,
    ErrorRateClass,
    HealthStatus,
    ListenerKind,
    QuerySourceTier,
    SourceTier,
    SystemHealthStatus,
)
from hassette_wire.logs import LogEntryResponse, LogLevelRequest, LogLevelResponse, LogsByExecutionResponse
from hassette_wire.telemetry import (
    ActivityBucket,
    ActivityFeedEntry,
    AppHealthResponse,
    DashboardAppGridEntry,
    DashboardAppGridResponse,
    Execution,
    JobSummary,
    JobTriggerResponse,
    ListenerWithSummary,
    TelemetryStatusResponse,
)
from hassette_wire.ws import (
    AppManifestsChangedData,
    AppManifestsChangedWsMessage,
    AppStatusChangedData,
    AppStatusChangedWsMessage,
    ConnectedPayload,
    ConnectedWsMessage,
    ConnectivityData,
    ConnectivityWsMessage,
    ExecutionCompletedData,
    ExecutionCompletedWsMessage,
    LogHintWsMessage,
    ServiceStatusData,
    ServiceStatusWsMessage,
    WsServerMessage,
)

__all__ = [
    "LOG_LEVEL_TYPE",
    "MAX_SESSION_TOKEN_LENGTH",
    "ActionResponse",
    "ActivityBucket",
    "ActivityFeedEntry",
    "AppConfigResponse",
    "AppHealthResponse",
    "AppInstanceResponse",
    "AppManifestListResponse",
    "AppManifestResponse",
    "AppManifestsChangedData",
    "AppManifestsChangedWsMessage",
    "AppSourceResponse",
    "AppStatusChangedData",
    "AppStatusChangedWsMessage",
    "AppStatusResponse",
    "BackpressurePolicy",
    "BootIssueResponse",
    "CliFormat",
    "CliFormatStyle",
    "ConfigSchemaResponse",
    "ConnectedPayload",
    "ConnectedWsMessage",
    "ConnectivityData",
    "ConnectivityWsMessage",
    "DashboardAppGridEntry",
    "DashboardAppGridResponse",
    "ErrorRateClass",
    "Execution",
    "ExecutionCompletedData",
    "ExecutionCompletedWsMessage",
    "ExecutionMode",
    "ExecutionStatus",
    "HealthStatus",
    "JobSummary",
    "JobTriggerResponse",
    "ListenerKind",
    "ListenerWithSummary",
    "LivenessResponse",
    "LogEntryResponse",
    "LogHintWsMessage",
    "LogLevelRequest",
    "LogLevelResponse",
    "LogsByExecutionResponse",
    "ManifestStatus",
    "QuerySourceTier",
    "ReadinessResponse",
    "ResourceStatus",
    "ServiceInfoResponse",
    "ServiceStatusData",
    "ServiceStatusWsMessage",
    "SessionRequest",
    "SessionResponse",
    "SourceTier",
    "SystemHealthStatus",
    "SystemStatusResponse",
    "TelemetryStatusResponse",
    "WsServerMessage",
]
