"""Auto-generated synchronous named-event shortcuts for `Bus`.

Do not edit this file directly.

It is generated from `bus.Bus` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Mapping
from typing import Any, Unpack

from hassette.bus.listeners import Subscription
from hassette.bus.options import Options
from hassette.resources.base import Resource
from hassette.types.enums import ResourceStatus
from hassette.types.types import WhereClause

if typing.TYPE_CHECKING:
    from hassette import Bus
    from hassette.types import HandlerType
    from hassette.types.types import BusErrorHandlerType


class BusSyncEventShortcuts(Resource):
    """Synchronous named-event shortcuts for the event bus.

    An intermediate base class rather than a resource in its own right: ``BusSyncFacade``
    subclasses it and supplies ``_bus``, the constructor, and the lifecycle hooks. These
    wrappers live in their own generated module so ``bus/sync.py`` stays under the repo's
    file-size threshold; callers reach every method here through ``bus.sync``.
    """

    _bus: "Bus"

    def on_component_loaded(
        self,
        component: str | None = None,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to component loaded events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            component: The component to filter load events (e.g., "light").
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_component_loaded(
                component, handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_service_registered(
        self,
        domain: str | None = None,
        service: str | None = None,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to service registered events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            domain: The domain to filter service registrations (e.g., "light").
            service: The service to filter service registrations (e.g., "turn_on").
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_service_registered(
                domain, service, handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_homeassistant_restart(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to Home Assistant restart events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_homeassistant_restart(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_homeassistant_start(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to Home Assistant start events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_homeassistant_start(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_homeassistant_stop(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to Home Assistant stop events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_homeassistant_stop(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_hassette_service_status(
        self,
        status: ResourceStatus | None = None,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service status events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            status: The status to filter events (e.g., ResourceStatus.STARTED).
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. A stable string identifier for this listener. Forms part of the
                natural key ``(app_key, instance_index, name, topic)`` used for upsert
                deduplication across restarts. Omitting it entirely raises ``TypeError`` (no
                default value); passing an empty string raises ``ListenerNameRequiredError``
                at call time.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_status(
                status, handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_hassette_service_failed(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service failed events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. A stable string identifier for this listener. Forms part of the
                natural key ``(app_key, instance_index, name, topic)`` used for upsert
                deduplication across restarts. Omitting it entirely raises ``TypeError`` (no
                default value); passing an empty string raises ``ListenerNameRequiredError``
                at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_failed(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_hassette_service_crashed(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service crashed events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_crashed(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_hassette_service_started(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service started events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_started(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_websocket_connected(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to websocket connected events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_websocket_connected(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_websocket_disconnected(
        self,
        *,
        handler: "HandlerType",
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to websocket disconnected events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_websocket_disconnected(
                handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_app_state_changed(
        self,
        *,
        handler: "HandlerType",
        app_key: str | None = None,
        status: ResourceStatus | None = None,
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to app instance state change events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            handler: The function to call when the event matches.
            app_key: Filter events for a specific app key.
            status: Filter events for a specific status.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_app_state_changed(
                handler=handler,
                app_key=app_key,
                status=status,
                where=where,
                kwargs=kwargs,
                name=name,
                on_error=on_error,
                **opts,
            )
        )

    def on_app_running(
        self,
        *,
        handler: "HandlerType",
        app_key: str | None = None,
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to app instances reaching RUNNING status.

        Args:
            handler: The function to call when the event matches.
            app_key: Filter events for a specific app key.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_app_running(
                handler=handler, app_key=app_key, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_app_stopping(
        self,
        *,
        handler: "HandlerType",
        app_key: str | None = None,
        where: WhereClause = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to app instances entering STOPPING status.

        Args:
            handler: The function to call when the event matches.
            app_key: Filter events for a specific app key.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable name for this listener. Omitting it entirely raises
                ``TypeError`` (no default value); passing an empty string raises
                ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener.
        """
        return self.task_bucket.run_sync(
            self._bus.on_app_stopping(
                handler=handler, app_key=app_key, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )
