"""Auto-generated synchronous facade for `Bus`.

Do not edit this file directly.

It is generated from `bus.Bus` by `codegen/src/hassette_codegen/sync_facade/`.
"""

import typing
from collections.abc import Mapping
from typing import Any, Unpack

from hassette.bus.listeners import Subscription
from hassette.bus.options import Options
from hassette.const import NOT_PROVIDED
from hassette.resources.base import Resource
from hassette.types import ComparisonCondition
from hassette.types.enums import ResourceStatus
from hassette.types.types import LOG_LEVEL_TYPE, IfExistsPolicy

if typing.TYPE_CHECKING:
    from collections.abc import Sequence

    from hassette import Bus, Hassette
    from hassette.bus.listeners import Listener
    from hassette.types import ChangeType, HandlerType, Predicate
    from hassette.types.enums import BackpressurePolicy, ExecutionMode
    from hassette.types.types import BusErrorHandlerType


class BusSyncFacade(Resource):
    """Synchronous facade for the event bus.

    This class provides synchronous methods that wrap the asynchronous registration methods of
    the Bus class, allowing listeners to be registered from synchronous code (for example, an
    ``AppSync`` lifecycle hook running in a worker thread).

    These methods must not be called from within the event loop; doing so raises a RuntimeError.
    Use the asynchronous methods on ``Bus`` directly when operating within an event loop.
    """

    _bus: "Bus"

    def __init__(self, hassette: "Hassette", *, bus: "Bus", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._bus = bus

    async def on_initialize(self) -> None:
        self.mark_ready(reason="Synchronous Bus facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        return self.hassette.config.logging.bus_service

    def add_listener(self, listener: "Listener", *, if_exists: IfExistsPolicy = "error") -> Subscription:
        """Add a pre-built listener to the bus.

        This is the direct entry point for callers that construct a ``Listener``
        externally. The normal registration flow (``on_state_change``, ``on()``,
        etc.) goes through ``_on_internal`` instead.

        Args:
            listener: The pre-built listener to add.
            if_exists: Behavior when a listener with the same natural key already exists.
                ``"error"`` (default) raises ``DuplicateListenerError``.
                ``"skip"`` returns a subscription to the existing listener when configs match.
                ``"replace"`` cancels the existing listener and registers the new one.

        Returns:
            A subscription to the added listener (or the existing listener on skip).

        Raises:
            ListenerNameRequiredError: If the listener has no ``name`` (required for all DB-registered
                listeners, including once-listeners; cancel-listeners bypass this path entirely).
            DuplicateListenerError: If the listener's natural key is already registered and
                ``if_exists="error"``."""

        return self.task_bucket.run_sync(self._bus.add_listener(listener, if_exists=if_exists))

    def emit(self, topic: str, data: object) -> None:
        """Broadcast data to all subscribers of the given topic.

        Subscribers annotated with ``D.EventData[T]`` receive ``data`` pre-extracted.
        If the internal event stream is closed (during shutdown), the event is silently dropped."""

        return self.task_bucket.run_sync(self._bus.emit(topic, data))

    def on(
        self,
        *,
        topic: str,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        once: bool = False,
        debounce: float | None = None,
        throttle: float | None = None,
        timeout: float | None = None,
        timeout_disabled: bool = False,
        mode: "ExecutionMode | str | None" = None,
        backpressure: "BackpressurePolicy | str | None" = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        if_exists: IfExistsPolicy = "error",
    ) -> Subscription:
        """Subscribe to an event topic with optional filtering and modifiers.

        This is the public registration method for raw topic subscriptions.
        Registration completes before the call returns — ``sub.listener.db_id`` is a valid
        integer immediately on return.

        Args:
            topic: The event topic to listen to.
            handler: The function to call when the event matches.
            where: Optional predicates to filter events. These can be custom callables or predefined predicates from
                `hassette.event_handling.predicates`. They will receive the full event for evaluation.
            kwargs: Keyword arguments to pass to the handler.
            once: If True, the handler will be called only once and then removed.
            debounce: If set, applies a debounce to the handler.
            throttle: If set, applies a throttle to the handler.
            timeout: Per-listener timeout in seconds. Overrides the global event_handler_timeout_seconds config.
                None means fall through to the config default.
            timeout_disabled: When True, disables timeout enforcement for this listener regardless of config.
            mode: Overlap behavior when a trigger fires while a prior invocation still runs —
                ``"single"``, ``"restart"``, ``"queued"``, or ``"parallel"``. When omitted, the
                effective default is tier-aware: ``parallel`` for framework listeners, ``single``
                for app listeners. Suppressed/dropped counts are live-only diagnostics, reset on
                restart.
            backpressure: Saturation policy when the global dispatch concurrency semaphore is full.
                ``"block"`` (default) waits for a slot; ``"drop_newest"`` skips the event immediately
                and records one drop on the listener. When omitted, the effective default is ``block``.
            name: Required. Stable string identifier for this listener. Forms part of the natural
                key ``(app_key, instance_index, name, topic)`` used for upsert deduplication across
                restarts. Omitting it raises ``ListenerNameRequiredError`` at call time.
            on_error: Optional per-listener error handler.
            if_exists: Behavior when a listener with the same natural key already exists.
                ``"error"`` (default) raises ``DuplicateListenerError``. ``"skip"`` returns the
                existing listener's subscription when the configurations match, and raises
                ``ValueError`` if the configuration has drifted. ``"replace"`` cancels the
                existing listener and registers the new one in its place.

        Returns:
            A subscription object. ``sub.cancel()`` removes the listener.
            ``sub.listener.db_id`` is a valid integer immediately on return.

        Raises:
            ListenerNameRequiredError: If ``name`` is not provided.
            DuplicateListenerError: If a listener with the same ``(name, topic)`` is already
                registered and ``if_exists="error"`` (the default).
            ValueError: If ``if_exists="skip"`` and a listener with the same ``(name, topic)``
                exists but with a different configuration (the message lists the changed fields)."""

        return self.task_bucket.run_sync(
            self._bus.on(
                topic=topic,
                handler=handler,
                where=where,
                kwargs=kwargs,
                once=once,
                debounce=debounce,
                throttle=throttle,
                timeout=timeout,
                timeout_disabled=timeout_disabled,
                mode=mode,
                backpressure=backpressure,
                name=name,
                on_error=on_error,
                if_exists=if_exists,
            )
        )

    def on_state_change(
        self,
        entity_id: str,
        *,
        handler: "HandlerType",
        changed: bool | ComparisonCondition = True,
        changed_from: "ChangeType" = NOT_PROVIDED,
        changed_to: "ChangeType" = NOT_PROVIDED,
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        immediate: bool = False,
        duration: float | None = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to state changes for a specific entity.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            entity_id: The entity ID to filter events for (e.g., "media_player.living_room_speaker").
            handler: The function to call when the event matches.
            changed: Whether to filter only events where the state changed. If a ComparisonCondition is provided, it
                will be used to compare the old and new state values.
            changed_from: A value or callable that will be used to filter state changes *from* this value.
            changed_to: A value or callable that will be used to filter state changes *to* this value.
            where: Additional predicates to filter events (e.g. ValueIs) or custom callables. These will receive the
                full event for evaluation.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. A stable string identifier for this listener. Forms part of the natural
                key ``(app_key, instance_index, name, topic)`` used for upsert deduplication across
                restarts. Omitting it raises ``ListenerNameRequiredError`` at call time.
            **opts: Additional options. Accepts ``once``, ``debounce``, ``throttle``, ``timeout``,
                ``timeout_disabled``, ``if_exists``, ``mode``, and ``backpressure``.

                ``mode`` controls overlap behavior when a trigger fires while a prior invocation
                is still running: ``"single"`` drops the re-fire (the default for app handlers),
                ``"restart"`` cancels and replaces, ``"queued"`` serializes in arrival order
                (bounded at 10 pending), ``"parallel"`` runs concurrently. When omitted, the
                tier-aware default applies: ``"single"`` for app handlers, ``"parallel"`` for
                framework-internal listeners. An explicit ``mode=`` always wins. Suppressed
                (``single``) and dropped (``queued`` cap) events log at DEBUG only.
                Suppressed/dropped counts are live-only diagnostics, reset on restart.
                See `Execution Modes <https://hassette.dev/core-concepts/bus/execution-modes/>`_.

                ``backpressure`` controls what this listener does when the dispatch concurrency
                semaphore is saturated: ``"block"`` (default) waits for a slot, unchanged from
                today; ``"drop_newest"`` skips the event immediately rather than waiting. It gates
                at the dispatch acquire point (global bus saturation), orthogonal to
                ``mode``/``debounce``/``throttle``.

        Returns:
            A subscription object. ``sub.listener.db_id`` is set immediately. ``sub.cancel()``
            removes the listener from routing.

        Raises:
            ListenerNameRequiredError: If ``name`` is not provided.
            DuplicateListenerError: If a listener with the same ``(name, topic)`` is already
                registered on this bus in the current session and ``if_exists="error"``
                (the default)."""

        return self.task_bucket.run_sync(
            self._bus.on_state_change(
                entity_id,
                handler=handler,
                changed=changed,
                changed_from=changed_from,
                changed_to=changed_to,
                where=where,
                kwargs=kwargs,
                immediate=immediate,
                duration=duration,
                name=name,
                on_error=on_error,
                **opts,
            )
        )

    def on_attribute_change(
        self,
        entity_id: str,
        attr: str,
        *,
        handler: "HandlerType",
        changed: bool | ComparisonCondition = True,
        changed_from: "ChangeType" = NOT_PROVIDED,
        changed_to: "ChangeType" = NOT_PROVIDED,
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        immediate: bool = False,
        duration: float | None = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to state change events for a specific entity's attribute.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            entity_id: The entity ID to filter events for (e.g., "media_player.living_room_speaker").
            attr: The attribute name to filter changes on (e.g., "volume").
            handler: The function to call when the event matches.
            changed: Whether to filter only events where the attribute changed. If a ComparisonCondition is provided,
                it will be used to compare the old and new attribute values.
            changed_from: A value or callable that will be used to filter attribute changes *from* this value.
            changed_to: A value or callable that will be used to filter attribute changes *to* this value.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable string identifier. Omitting it raises ``ListenerNameRequiredError``.
            **opts: Additional options. Accepts ``once``, ``debounce``, ``throttle``, ``timeout``,
                ``timeout_disabled``, ``if_exists``, ``mode``, and ``backpressure``.

                ``mode`` controls overlap behavior when a trigger fires while a prior invocation
                is still running: ``"single"`` drops the re-fire (the default for app handlers),
                ``"restart"`` cancels and replaces, ``"queued"`` serializes in arrival order
                (bounded at 10 pending), ``"parallel"`` runs concurrently. Suppressed/dropped
                counts are live-only diagnostics, reset on restart.

                ``backpressure`` controls what this listener does when the dispatch concurrency
                semaphore is saturated: ``"block"`` (default) waits for a slot, unchanged from
                today; ``"drop_newest"`` skips the event immediately rather than waiting. It gates
                at the dispatch acquire point (global bus saturation), orthogonal to
                ``mode``/``debounce``/``throttle``.

        Returns:
            A subscription object. ``sub.listener.db_id`` is set immediately.

        Raises:
            ListenerNameRequiredError: If ``name`` is not provided.
            DuplicateListenerError: If a listener with the same ``(name, topic)`` is already
                registered and ``if_exists="error"`` (the default)."""

        return self.task_bucket.run_sync(
            self._bus.on_attribute_change(
                entity_id,
                attr,
                handler=handler,
                changed=changed,
                changed_from=changed_from,
                changed_to=changed_to,
                where=where,
                kwargs=kwargs,
                immediate=immediate,
                duration=duration,
                name=name,
                on_error=on_error,
                **opts,
            )
        )

    def on_call_service(
        self,
        domain: str | None = None,
        service: str | None = None,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | Mapping[str, ChangeType] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to service call events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            domain: The domain to filter service calls (e.g., "light").
            service: The service to filter service calls (e.g., "turn_on").
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. Stable string identifier for this listener. Omitting it raises
                ``ListenerNameRequiredError`` at call time.
            **opts: Additional options. Accepts ``once``, ``debounce``, ``throttle``, ``timeout``,
                ``timeout_disabled``, ``if_exists``, ``mode``, and ``backpressure``.

                ``mode`` controls overlap behavior when a trigger fires while a prior invocation
                is still running: ``"single"`` drops the re-fire (the default for app handlers),
                ``"restart"`` cancels and replaces, ``"queued"`` serializes in arrival order
                (bounded at 10 pending), ``"parallel"`` runs concurrently. Suppressed/dropped
                counts are live-only diagnostics, reset on restart.

                ``backpressure`` controls what this listener does when the dispatch concurrency
                semaphore is saturated: ``"block"`` (default) waits for a slot, unchanged from
                today; ``"drop_newest"`` skips the event immediately rather than waiting. It gates
                at the dispatch acquire point (global bus saturation), orthogonal to
                ``mode``/``debounce``/``throttle``.

        Returns:
            A subscription object. ``sub.listener.db_id`` is set immediately.

        Raises:
            ListenerNameRequiredError: If ``name`` is not provided.
            DuplicateListenerError: If a listener with the same ``(name, topic)`` is already
                registered and ``if_exists="error"`` (the default)."""

        return self.task_bucket.run_sync(
            self._bus.on_call_service(
                domain, service, handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_component_loaded(
        self,
        component: str | None = None,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to component loaded events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            component: The component to filter load events (e.g., "light").
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_component_loaded(
                component, handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_service_registered(
        self,
        domain: str | None = None,
        service: str | None = None,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to service registered events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            domain: The domain to filter service registrations (e.g., "light").
            service: The service to filter service registrations (e.g., "turn_on").
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_service_registered(
                domain, service, handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_homeassistant_restart(
        self,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to Home Assistant restart events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(self._bus.on_homeassistant_restart(handler, where, kwargs, name, **opts))

    def on_homeassistant_start(
        self,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to Home Assistant start events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(self._bus.on_homeassistant_start(handler, where, kwargs, name, **opts))

    def on_homeassistant_stop(
        self,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to Home Assistant stop events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(self._bus.on_homeassistant_stop(handler, where, kwargs, name, **opts))

    def on_hassette_service_status(
        self,
        status: ResourceStatus | None = None,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service status events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            status: The status to filter events (e.g., ResourceStatus.STARTED).
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. A stable string identifier for this listener. Forms part of the
                natural key ``(app_key, instance_index, name, topic)`` used for upsert
                deduplication across restarts. Omitting it raises ``ListenerNameRequiredError``
                at call time.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_status(
                status, handler=handler, where=where, kwargs=kwargs, name=name, on_error=on_error, **opts
            )
        )

    def on_hassette_service_failed(
        self,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service failed events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Required. A stable string identifier for this listener. Forms part of the
                natural key ``(app_key, instance_index, name, topic)`` used for upsert
                deduplication across restarts. Omitting it raises ``ListenerNameRequiredError``
                at call time.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_failed(handler=handler, where=where, kwargs=kwargs, name=name, **opts)
        )

    def on_hassette_service_crashed(
        self,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service crashed events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_crashed(handler=handler, where=where, kwargs=kwargs, name=name, **opts)
        )

    def on_hassette_service_started(
        self,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to hassette service started events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_hassette_service_started(handler=handler, where=where, kwargs=kwargs, name=name, **opts)
        )

    def on_websocket_connected(
        self,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to websocket connected events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_websocket_connected(handler=handler, where=where, kwargs=kwargs, name=name, **opts)
        )

    def on_websocket_disconnected(
        self,
        *,
        handler: "HandlerType",
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to websocket disconnected events.

        Args:
            handler: The function to call when the event matches.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_websocket_disconnected(handler=handler, where=where, kwargs=kwargs, name=name, **opts)
        )

    def on_app_state_changed(
        self,
        *,
        handler: "HandlerType",
        app_key: str | None = None,
        status: ResourceStatus | None = None,
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        on_error: "BusErrorHandlerType | None" = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to app instance state change events.

        Registration completes before the call returns.
        ``sub.listener.db_id`` is a valid integer immediately on return.

        Args:
            handler: The function to call when the event matches.
            app_key: Filter events for a specific app key.
            status: Filter events for a specific status.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_app_state_changed(
                handler=handler,
                app_key=app_key,
                status=status,
                where=where,
                kwargs=kwargs,
                name=name,
                on_error=on_error,
                **opts,
            )
        )

    def on_app_running(
        self,
        *,
        handler: "HandlerType",
        app_key: str | None = None,
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to app instances reaching RUNNING status.

        Args:
            handler: The function to call when the event matches.
            app_key: Filter events for a specific app key.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_app_running(handler=handler, app_key=app_key, where=where, kwargs=kwargs, name=name, **opts)
        )

    def on_app_stopping(
        self,
        *,
        handler: "HandlerType",
        app_key: str | None = None,
        where: "Predicate | Sequence[Predicate] | None" = None,
        kwargs: Mapping[str, Any] | None = None,
        name: str | None = None,
        **opts: Unpack[Options],
    ) -> Subscription:
        """Subscribe to app instances entering STOPPING status.

        Args:
            handler: The function to call when the event matches.
            app_key: Filter events for a specific app key.
            where: Additional predicates to filter events.
            kwargs: Keyword arguments to pass to the handler.
            name: Stable name for this listener. Required on all DB-registered listeners.
            **opts: Additional options like `once`, `debounce`, `throttle`, `mode`, and `backpressure`.

        Returns:
            A subscription object that can be used to manage the listener."""

        return self.task_bucket.run_sync(
            self._bus.on_app_stopping(handler=handler, app_key=app_key, where=where, kwargs=kwargs, name=name, **opts)
        )

    def on_error(self, handler: "BusErrorHandlerType") -> None:
        """Register an app-level error handler for this bus.

        The handler is called when any listener on this bus raises an exception
        (including ``TimeoutError``) and the listener does not have its own
        per-registration error handler.

        This is an app-level fallback — it is resolved at dispatch time, not at listener
        registration time. A later call to ``on_error()`` replaces any previously registered
        handler.

        Note: error handlers are spawned as fire-and-forget tasks. Handlers spawned near
        app shutdown may be cancelled before they complete. Do not rely on error handlers
        for delivery-critical alerting during system teardown.

        Args:
            handler: A sync or async callable that accepts a :class:`~hassette.bus.error_context.BusErrorContext`."""

        return self._bus.on_error(handler)

    def remove_listener(self, listener: "Listener") -> None:
        """Remove a listener from the bus and persist cancellation to the database.

        Pops the natural key from the in-memory registry, removes the listener from routing
        (via BusService), and — when ``db_id`` is set — spawns ``mark_listener_cancelled``
        on ``bus_service.task_bucket`` so the write survives resource shutdown, mirroring
        ``Scheduler.cancel_job``.

        BusService.remove_listener also fires _on_listener_removed, but that callback only
        spawns mark_listener_cancelled when the key is still present (once-fire path). Because
        this method pops the key first, the callback's spawn is skipped — avoiding a double write."""

        return self._bus.remove_listener(listener)

    def remove_all_listeners(self) -> None:
        """Remove all listeners owned by this bus's owner."""

        return self._bus.remove_all_listeners()

    def get_listeners(self) -> list["Listener"]:
        """Get all listeners owned by this bus's owner."""

        return self._bus.get_listeners()
