"""Characterization tests for tools/check_wire_compat.py.

Runs the real ``oasdiff`` binary against minimal OpenAPI fixture pairs under
``tests/unit/tools/fixtures/wire_compat/`` — the exact per-check filtering and the
reversed/forward argument order are the thing under test, and mocking ``oasdiff``'s output would
just re-assert whatever the mock was told to return. Skipped when ``oasdiff`` isn't on PATH
(installed via mise locally; installed via ``go install`` in the frontend CI job — see
``.github/workflows/tests.yml``).
"""

import json
import shutil
import subprocess
from pathlib import Path

import pytest
from check_wire_compat import (
    DEFAULT_IGNORE_FILE,
    format_ignore_line,
    list_release_tags,
    main,
    resolve_latest_release_tag,
    select_forward_blocking_findings,
)

pytestmark = pytest.mark.skipif(shutil.which("oasdiff") is None, reason="oasdiff not found on PATH")

FIXTURES = Path(__file__).parent / "fixtures" / "wire_compat"


def _run(name: str, ignore_file: Path = DEFAULT_IGNORE_FILE) -> int:
    d = FIXTURES / name
    return main(head_openapi_path=d / "head.json", release_openapi_path=d / "release.json", ignore_file=ignore_file)


def _init_throwaway_repo(repo_dir: Path) -> Path:
    """Create a throwaway git repo at ``repo_dir`` with a committed ``frontend/openapi.json``.

    Returns the ``frontend`` directory so callers can overwrite ``openapi.json`` for later commits.
    """
    frontend_dir = repo_dir / "frontend"
    frontend_dir.mkdir()
    (frontend_dir / "openapi.json").write_text("{}")
    subprocess.run(["git", "init", "-q", "-b", "main"], cwd=repo_dir, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo_dir, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo_dir, check=True, capture_output=True)
    subprocess.run(["git", "add", "-A"], cwd=repo_dir, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "initial"], cwd=repo_dir, check=True, capture_output=True)
    return frontend_dir


def test_new_required_response_property_fails() -> None:
    """A response property that didn't exist in the release and is required at HEAD is blocked."""
    assert _run("new_required_property") != 0


def test_optional_response_property_became_required_fails() -> None:
    """A response property that was optional in the release and is required at HEAD is blocked."""
    assert _run("optional_became_required") != 0


def test_removed_response_property_fails() -> None:
    """A required response property present in the release and removed at HEAD is blocked."""
    assert _run("removed_response_property") != 0


def test_removed_endpoint_fails() -> None:
    """An endpoint present in the release and removed at HEAD is blocked."""
    assert _run("removed_endpoint") != 0


def test_removed_webhook_fails() -> None:
    """A webhook present in the release and removed at HEAD is blocked.

    This is a components-scoped finding (``webhook-removed``, ``section: "components"``) — oasdiff
    reports no ``operation``/``path`` for it at all, unlike every other fixture here. It exists to
    prove the check doesn't crash on a finding shaped like this.
    """
    assert _run("removed_webhook") != 0


def test_new_optional_response_property_passes() -> None:
    """A new, non-required response property at HEAD is not blocked."""
    assert _run("new_optional_property") == 0


def test_new_endpoint_passes() -> None:
    """A brand-new endpoint at HEAD is not blocked."""
    assert _run("new_endpoint") == 0


def test_new_enum_value_passes() -> None:
    """A new allowed enum value on an existing response property at HEAD is not blocked.

    Enum/Literal value growth is the old-client/new-server hazard hassette-client's lenient
    parsing owns, not this check — see ``FORWARD_ALLOWED_ERR_CHECK_IDS``.
    """
    assert _run("new_enum_value") == 0


def test_removed_enum_value_fails() -> None:
    """An enum value present in the release and removed at HEAD is blocked, so an enum rename is too.

    oasdiff rates this INFO by default; ``SEVERITY_OVERRIDES`` raises it, since a caller comparing
    against the removed value silently stops matching.
    """
    assert _run("removed_enum_value") != 0


def test_removed_response_property_passes_when_listed_in_ignore_file(tmp_path: Path) -> None:
    """A deliberate break passes once its exact oasdiff finding is listed in the ignore file.

    The ignore line is generated by ``format_ignore_line`` — the same function the failing check
    prints for a developer to paste — so the test proves that line actually matches what
    ``--err-ignore`` expects, not just that the format doc claims it does.
    """
    d = FIXTURES / "ignored_removed_property"
    # This same fixture pair fails without an ignore entry — the forward run is where the
    # removed-property finding surfaces (see test_removed_response_property_fails).
    assert main(head_openapi_path=d / "head.json", release_openapi_path=d / "release.json") != 0

    result = subprocess.run(
        ["oasdiff", "breaking", str(d / "release.json"), str(d / "head.json"), "--format", "json"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    findings = json.loads(result.stdout)
    blocking = select_forward_blocking_findings(findings)
    assert blocking, f"expected a blocking finding in:\n{result.stdout}"

    ignore_file = tmp_path / "wire_compat_ignore.txt"
    ignore_file.write_text(format_ignore_line(blocking[0]) + "\n")

    exit_code = main(
        head_openapi_path=d / "head.json", release_openapi_path=d / "release.json", ignore_file=ignore_file
    )
    assert exit_code == 0


def test_removed_webhook_passes_when_listed_in_ignore_file(tmp_path: Path) -> None:
    """A components-scoped deliberate break (no operation/path) also passes once ignored.

    Proves ``format_ignore_line``'s ``components <description>`` form — used when a finding has no
    operation/path — actually suppresses the finding via ``--err-ignore``, not just the
    ``METHOD /path <description>`` form the other ignore test covers.
    """
    d = FIXTURES / "removed_webhook"
    result = subprocess.run(
        ["oasdiff", "breaking", str(d / "release.json"), str(d / "head.json"), "--format", "json"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    findings = json.loads(result.stdout)
    blocking = select_forward_blocking_findings(findings)
    assert blocking, f"expected a blocking finding in:\n{result.stdout}"
    assert format_ignore_line(blocking[0]).startswith("components "), blocking[0]

    ignore_file = tmp_path / "wire_compat_ignore.txt"
    ignore_file.write_text(format_ignore_line(blocking[0]) + "\n")

    exit_code = main(
        head_openapi_path=d / "head.json", release_openapi_path=d / "release.json", ignore_file=ignore_file
    )
    assert exit_code == 0


def test_missing_release_tag_fails_with_a_named_message(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """When no `v*` tag exists anywhere in the repo, the check fails loudly instead of skipping."""
    _init_throwaway_repo(tmp_path)

    exit_code = main(repo_root=tmp_path)

    assert exit_code != 0
    assert "v*" in capsys.readouterr().err


def test_unreachable_release_tag_fails_with_a_named_message(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """A `v*` tag that exists in the repo but isn't reachable from HEAD counts as no tag.

    A branch forked before a release must not be compared against a tag it can't see yet — that
    would report the release's later additions as removals. Here the tag lives on a sibling branch
    that HEAD (``main``) never merged, so it must be treated the same as no tag at all.
    """
    frontend_dir = _init_throwaway_repo(tmp_path)

    subprocess.run(["git", "checkout", "-q", "-b", "other"], cwd=tmp_path, check=True, capture_output=True)
    (frontend_dir / "openapi.json").write_text('{"changed": true}')
    subprocess.run(["git", "commit", "-a", "-m", "second"], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(["git", "tag", "v1.0.0"], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(["git", "checkout", "-q", "main"], cwd=tmp_path, check=True, capture_output=True)

    exit_code = main(repo_root=tmp_path)

    assert exit_code != 0
    assert "v*" in capsys.readouterr().err


def test_highest_reachable_tag_wins(tmp_path: Path) -> None:
    """When multiple `v*` tags are reachable from HEAD, the highest version wins, not tag-creation order."""
    _init_throwaway_repo(tmp_path)
    subprocess.run(["git", "tag", "v1.0.0"], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(["git", "tag", "v1.10.0"], cwd=tmp_path, check=True, capture_output=True)

    assert resolve_latest_release_tag(tmp_path) == "v1.10.0"


def test_pre_release_and_non_pep440_tags_are_skipped(tmp_path: Path) -> None:
    """Git's version sort ranks v1.1.0rc1 and v1.1.0.dev1 above v1.1.0; only final releases count."""
    _init_throwaway_repo(tmp_path)
    for tag in ("v1.0.0", "v1.1.0", "v1.1.0rc1", "v1.1.0.dev1", "v1.2.0-beta", "vnext"):
        subprocess.run(["git", "tag", tag], cwd=tmp_path, check=True, capture_output=True)

    assert list_release_tags(tmp_path) == ["v1.1.0", "v1.0.0"]
