"""Characterization tests for tools/check_duplicate_code.py.

Pin the pure logic — union-find clustering, the docstring/import boilerplate exemption, the
codegen-directory/marker exclusion, the `dup-ignore-start`/`dup-ignore-end` escape hatch (including
its error paths), and PMD XML parsing — without invoking the real PMD binary or network.
"""

import xml.etree.ElementTree as ET
from collections.abc import Callable
from pathlib import Path

import check_duplicate_code
import pytest
from check_duplicate_code import (
    CODEGEN_DIRS,
    CPD_NS,
    Fragment,
    IgnoreMarkerError,
    build_edges,
    cluster,
    duplication_blocks,
    find_violations,
    fragment_from_file_element,
    ignore_ranges,
    is_codegen_dir,
    is_dup_ignore_file,
    is_dup_ignored,
    is_excluded_file,
    is_generated_marker_file,
    is_ignored_glob,
    is_too_short,
    scanned_files,
    validate_markers,
)


@pytest.fixture
def write_file(tmp_path: Path) -> Callable[[str, str], Path]:
    """Return a helper that writes content to a named file under tmp_path."""

    def _write(name: str, content: str) -> Path:
        target = tmp_path / name
        target.write_text(content)
        return target

    return _write


def test_cluster_chains_pairwise_edges_into_one_component() -> None:
    a, b, c = Fragment(Path("a.py"), 1, 5), Fragment(Path("b.py"), 1, 5), Fragment(Path("c.py"), 1, 5)
    components = cluster([(a, b), (b, c)])
    assert len(components) == 1
    assert set(components[0]) == {a, b, c}


def test_cluster_keeps_disjoint_edges_separate() -> None:
    a, b, c, d = (
        Fragment(Path("a.py"), 1, 5),
        Fragment(Path("b.py"), 1, 5),
        Fragment(Path("c.py"), 1, 5),
        Fragment(Path("d.py"), 1, 5),
    )
    components = cluster([(a, b), (c, d)])
    assert len(components) == 2
    assert {frozenset(comp) for comp in components} == {frozenset({a, b}), frozenset({c, d})}


def test_is_too_short_below_min_lines() -> None:
    assert is_too_short(Fragment(Path("a.py"), 1, 3)) is True


def test_is_too_short_at_min_lines() -> None:
    assert is_too_short(Fragment(Path("a.py"), 1, 5)) is False


def test_is_codegen_dir_matches_generated_model_directories() -> None:
    assert is_codegen_dir(CODEGEN_DIRS[0] / "light.py") is True


def test_is_codegen_dir_does_not_match_ordinary_source() -> None:
    assert is_codegen_dir(CODEGEN_DIRS[0].parent / "app.py") is False


def test_is_generated_marker_file_detects_banner(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("generated.py", '"""Do not edit this file directly."""\n')
    assert is_generated_marker_file(path) is True


def test_is_generated_marker_file_absent(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("normal.py", '"""A normal module."""\n')
    assert is_generated_marker_file(path) is False


def test_is_dup_ignore_file_python(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("ignored.py", "# dup-ignore-file: HA helper models share fields by API design\nx = 1\n")
    is_dup_ignore_file.cache_clear()
    assert is_dup_ignore_file(path) is True


def test_is_dup_ignore_file_typescript(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("ignored.ts", "// dup-ignore-file: MSW handlers mirror route structure\nexport {};\n")
    is_dup_ignore_file.cache_clear()
    assert is_dup_ignore_file(path) is True


def test_is_dup_ignore_file_false_for_ordinary(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("normal.py", "x = 1\n")
    is_dup_ignore_file.cache_clear()
    assert is_dup_ignore_file(path) is False


def test_is_dup_ignore_file_requires_reason(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("bad.py", "# dup-ignore-file:\n")
    is_dup_ignore_file.cache_clear()
    with pytest.raises(IgnoreMarkerError, match="requires a reason"):
        is_dup_ignore_file(path)


def test_is_excluded_file_true_for_generated_marker(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("generated.py", "# Do not edit this file directly\n")
    assert is_excluded_file(path) is True


def test_is_excluded_file_true_for_self() -> None:
    self_path = Path(check_duplicate_code.__file__)
    assert is_excluded_file(self_path) is True


def test_is_dup_ignore_file_false_for_self() -> None:
    """The tool's docstring contains a literal ``# dup-ignore-file: <reason>`` example.

    The regex would match it, but is_dup_ignore_file explicitly excludes its own source
    so the docstring example never accidentally suppresses the tool's own findings.
    """
    is_dup_ignore_file.cache_clear()
    self_path = Path(check_duplicate_code.__file__)
    assert is_dup_ignore_file(self_path) is False


def test_is_excluded_file_false_for_ordinary_file(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("normal.py", "x = 1\n")
    assert is_excluded_file(path) is False


@pytest.mark.parametrize(
    "rel_path",
    [
        "frontend/src/api/generated-types.ts",
        "frontend/src/api/ws-types.ts",
        "frontend/src/foo.d.ts",
        "frontend/src/api/foo.generated.ts",
        "tests/snapshots/cli_help.txt",
        "frontend/src/styles/fonts.css",
    ],
)
def test_is_ignored_glob_matches(rel_path: str) -> None:
    assert is_ignored_glob(Path(rel_path)) is True


def test_is_ignored_glob_does_not_match_ordinary_file() -> None:
    assert is_ignored_glob(Path("frontend/src/hooks/use-websocket.ts")) is False


def test_is_dup_ignored_true_inside_marker_range(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "ok.py",
        "def f():\n    # dup-ignore-start: shared setup pattern, intentional\n    x = 1\n    # dup-ignore-end\n",
    )
    assert is_dup_ignored(Fragment(path, 3, 3)) is True


def test_is_dup_ignored_false_outside_marker_range(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "ok.py",
        "def f():\n    # dup-ignore-start: shared setup pattern, intentional\n    x = 1\n    # dup-ignore-end\n",
    )
    assert is_dup_ignored(Fragment(path, 1, 1)) is False


def test_dup_ignore_marker_recognized_with_slash_comment_syntax(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "ok.ts",
        "function f() {\n"
        "  // dup-ignore-start: shared setup pattern, intentional\n"
        "  const x = 1;\n"
        "  // dup-ignore-end\n"
        "}\n",
    )
    assert is_dup_ignored(Fragment(path, 3, 3)) is True


def test_unbalanced_start_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("bad.py", "def f():\n    # dup-ignore-start: never closed\n    x = 1\n")
    with pytest.raises(IgnoreMarkerError, match="never closed"):
        is_dup_ignored(Fragment(path, 3, 3))


def test_dangling_end_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("bad.py", "def f():\n    x = 1\n    # dup-ignore-end\n")
    with pytest.raises(IgnoreMarkerError, match="no matching dup-ignore-start"):
        is_dup_ignored(Fragment(path, 2, 2))


def test_nested_start_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "bad.py",
        "# dup-ignore-start: outer\nx = 1\n# dup-ignore-start: inner\ny = 2\n# dup-ignore-end\n",
    )
    with pytest.raises(IgnoreMarkerError, match="nested dup-ignore-start"):
        is_dup_ignored(Fragment(path, 2, 2))


def test_empty_reason_start_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    # Regression: the marker regex used to require a non-empty reason to match at all, so
    # "# dup-ignore-start:" with nothing after the colon silently failed to register as a
    # marker — the checker error then pointed at the wrong problem ("no matching start")
    # instead of the real one (empty reason). It must now fail loudly and specifically.
    path = write_file("bad.py", "# dup-ignore-start:\nx = 1\n# dup-ignore-end\n")
    with pytest.raises(IgnoreMarkerError, match="requires a reason"):
        is_dup_ignored(Fragment(path, 2, 2))


def test_marker_not_triggered_by_prose_mention(write_file: Callable[[str, str], Path]) -> None:
    # Regression: the marker regex used to match as a plain substring anywhere on the line, so
    # prose *mentioning* the marker syntax (e.g. explaining it in a docstring) registered as a
    # real marker. It must only count as the line's actual leading comment.
    path = write_file(
        "prose.py",
        '"""See `# dup-ignore-start: reason` / `# dup-ignore-end` for the escape hatch syntax."""\n',
    )
    assert ignore_ranges(path) == ()


def test_marker_not_triggered_by_own_source_file() -> None:
    # Regression, reproduced directly against the checker's own source: tools/ is itself in
    # PYTHON_SCAN_PATHS, and this file's docstring explanation of the marker syntax plus
    # IGNORE_START_RE/IGNORE_END_RE's own literal pattern text used to trip the marker parser
    # on itself (raised "nested dup-ignore-start" scanning its own module docstring).
    self_path = Path(check_duplicate_code.__file__)
    ignore_ranges(self_path)  # must not raise IgnoreMarkerError


def test_validate_markers_raises_on_marker_never_seen_by_pmd(write_file: Callable[[str, str], Path]) -> None:
    # Regression for the gap chatgpt-codex-connector flagged on PR #1572: find_violations only
    # calls is_dup_ignored/ignore_ranges on fragments inside a 3+-occurrence PMD cluster, so a
    # malformed marker on code with no duplication at all — never seen by PMD, so never on that
    # path — used to pass the checker silently. validate_markers is the eager, PMD-independent
    # pass that closes the gap by parsing every marker in every scanned file up front.
    path = write_file("bad.py", "def f():\n    # dup-ignore-start: never closed\n    x = 1\n")
    with pytest.raises(IgnoreMarkerError, match="never closed"):
        validate_markers([path])


def test_validate_markers_passes_for_well_formed_marker(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "ok.py",
        "def f():\n    # dup-ignore-start: shared setup pattern, intentional\n    x = 1\n    # dup-ignore-end\n",
    )
    validate_markers([path])  # must not raise


def test_validate_markers_skips_ignored_glob_files(write_file: Callable[[str, str], Path]) -> None:
    # A malformed marker inside a generated file (e.g. accidental marker-like text in a codegen
    # template) must not fail the checker — IGNORE_GLOBS files are out of scope entirely.
    path = write_file("generated-types.ts", "// dup-ignore-start: never closed\nconst x = 1;\n")
    validate_markers([path])  # must not raise


def test_validate_markers_skips_generated_marker_files(write_file: Callable[[str, str], Path]) -> None:
    # is_excluded_file() already treats a "Do not edit this file directly" banner file as fully
    # out of scope for duplication checking (is_dropped short-circuits on it before is_dup_ignore_file
    # is ever reached) — a stray/malformed marker in one is never load-bearing and must not fail CI.
    path = write_file(
        "generated.py",
        "# Do not edit this file directly.\n# dup-ignore-start: never closed\nx = 1\n",
    )
    validate_markers([path])  # must not raise


def test_scanned_files_includes_python_and_typescript() -> None:
    # scanned_files() takes no arguments and always walks REPO_ROOT, so — unlike every other test
    # in this file — it can't be isolated behind the write_file/tmp_path fixture. This is a smoke
    # test against the real repo tree, not a characterization of specific file contents.
    files = scanned_files()
    assert any(f.suffix == ".py" for f in files)
    assert any(f.suffix in (".ts", ".tsx") for f in files)


def test_find_violations_below_min_occurrences_not_flagged(write_file: Callable[[str, str], Path]) -> None:
    a = write_file("a.py", "def f():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    b = write_file("b.py", "def g():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    blocks = [[Fragment(a, 1, 5), Fragment(b, 1, 5)]]
    assert find_violations(blocks) == []


def test_find_violations_at_min_occurrences_flagged(write_file: Callable[[str, str], Path]) -> None:
    a = write_file("a.py", "def f():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    b = write_file("b.py", "def g():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    c = write_file("c.py", "def h():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    blocks = [[Fragment(a, 1, 5), Fragment(b, 1, 5), Fragment(c, 1, 5)]]
    violations = find_violations(blocks)
    assert len(violations) == 1
    assert set(violations[0]) == {Fragment(a, 1, 5), Fragment(b, 1, 5), Fragment(c, 1, 5)}


def test_find_violations_suppressed_when_fully_dup_ignored(write_file: Callable[[str, str], Path]) -> None:
    marked = (
        "def f():\n"
        "    # dup-ignore-start: intentional shared shape\n"
        "    x = 1\n    y = 2\n    z = 3\n"
        "    # dup-ignore-end\n"
    )
    a = write_file("a.py", marked)
    b = write_file("b.py", marked)
    c = write_file("c.py", marked)
    blocks = [[Fragment(a, 3, 5), Fragment(b, 3, 5), Fragment(c, 3, 5)]]
    assert find_violations(blocks) == []


def test_find_violations_not_suppressed_when_partially_dup_ignored(write_file: Callable[[str, str], Path]) -> None:
    marked = (
        "def f():\n"
        "    # dup-ignore-start: intentional shared shape\n"
        "    x = 1\n    y = 2\n    z = 3\n    w = 4\n    v = 5\n"
        "    # dup-ignore-end\n"
    )
    unmarked = "def h():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n    v = 5\n"
    a = write_file("a.py", marked)
    b = write_file("b.py", marked)
    c = write_file("c.py", unmarked)
    blocks = [[Fragment(a, 3, 7), Fragment(b, 3, 7), Fragment(c, 2, 6)]]
    assert len(find_violations(blocks)) == 1


def test_build_edges_drops_too_short_fragments(write_file: Callable[[str, str], Path]) -> None:
    a = write_file("a.py", "x = 1\ny = 2\n")
    b = write_file("b.py", "x = 1\ny = 2\n")
    blocks = [[Fragment(a, 1, 2), Fragment(b, 1, 2)]]
    assert build_edges(blocks) == []


def test_build_edges_drops_boilerplate_import_only_fragment(write_file: Callable[[str, str], Path]) -> None:
    content = "import os\nimport sys\nimport json\nimport re\nimport ast\n"
    a = write_file("a.py", content)
    b = write_file("b.py", content)
    blocks = [[Fragment(a, 1, 5), Fragment(b, 1, 5)]]
    assert build_edges(blocks) == []


def test_fragment_from_file_element_parses_pmd_xml() -> None:
    xml = f"""<duplication xmlns="{CPD_NS["cpd"]}">
        <file path="/repo/tests/foo.py" line="10" endline="20"/>
    </duplication>"""
    element = ET.fromstring(xml).find("cpd:file", CPD_NS)  # noqa: S314 -- trusted literal test fixture
    assert element is not None
    fragment = fragment_from_file_element(element)
    assert fragment == Fragment(Path("/repo/tests/foo.py"), 10, 20)


def test_fragment_from_file_element_missing_attribute_raises() -> None:
    xml = f'<file xmlns="{CPD_NS["cpd"]}" path="/repo/tests/foo.py" line="10"/>'
    element = ET.fromstring(xml)  # noqa: S314 -- trusted literal test fixture
    with pytest.raises(ValueError, match="missing path/line/endline"):
        fragment_from_file_element(element)


def test_duplication_blocks_parses_multiple_occurrences() -> None:
    xml = f"""<pmd-cpd xmlns="{CPD_NS["cpd"]}">
        <duplication lines="10" tokens="50">
            <file path="/repo/a.py" line="1" endline="10"/>
            <file path="/repo/b.py" line="5" endline="14"/>
            <file path="/repo/c.py" line="8" endline="17"/>
        </duplication>
    </pmd-cpd>"""
    blocks = duplication_blocks(ET.fromstring(xml))  # noqa: S314 -- trusted literal test fixture
    assert blocks == [
        [
            Fragment(Path("/repo/a.py"), 1, 10),
            Fragment(Path("/repo/b.py"), 5, 14),
            Fragment(Path("/repo/c.py"), 8, 17),
        ]
    ]


def test_duplication_blocks_empty_report_returns_no_blocks() -> None:
    xml = f'<pmd-cpd xmlns="{CPD_NS["cpd"]}"></pmd-cpd>'
    assert duplication_blocks(ET.fromstring(xml)) == []  # noqa: S314 -- trusted literal test fixture
