"""Characterization tests for tools/check_duplicate_code.py.

Pin the pure logic — union-find clustering, the docstring/import boilerplate exemption, the
codegen-directory/marker exclusion, the `dup-ignore-start`/`dup-ignore-end` escape hatch (including
its error paths), PMD XML parsing, and the `--gate-new-code` merge-base cluster comparison —
without invoking the real PMD binary or network.
"""

import sys
import xml.etree.ElementTree as ET
from collections import Counter
from collections.abc import Callable
from pathlib import Path

import check_duplicate_code
import pytest
from check_duplicate_code import (
    CODEGEN_DIRS,
    CPD_NS,
    Fragment,
    IgnoreMarkerError,
    build_edges,
    cluster,
    cluster_file_counts,
    duplication_blocks,
    find_violations,
    fragment_from_file_element,
    ignore_ranges,
    is_codegen_dir,
    is_dup_ignore_file,
    is_dup_ignored,
    is_excluded_file,
    is_generated_marker_file,
    is_ignored_glob,
    is_too_short,
    new_code_violations,
    validate_markers,
)

from .conftest import GitRepo

REPO_ROOT_STUB = Path("/repo")


@pytest.fixture
def write_file(tmp_path: Path) -> Callable[[str, str], Path]:
    """Return a helper that writes content to a named file under tmp_path."""

    def _write(name: str, content: str) -> Path:
        target = tmp_path / name
        target.write_text(content)
        return target

    return _write


def test_cluster_chains_pairwise_edges_into_one_component() -> None:
    a, b, c = Fragment(Path("a.py"), 1, 5), Fragment(Path("b.py"), 1, 5), Fragment(Path("c.py"), 1, 5)
    components = cluster([(a, b), (b, c)])
    assert len(components) == 1
    assert set(components[0]) == {a, b, c}


def test_cluster_keeps_disjoint_edges_separate() -> None:
    a, b, c, d = (
        Fragment(Path("a.py"), 1, 5),
        Fragment(Path("b.py"), 1, 5),
        Fragment(Path("c.py"), 1, 5),
        Fragment(Path("d.py"), 1, 5),
    )
    components = cluster([(a, b), (c, d)])
    assert len(components) == 2
    assert {frozenset(comp) for comp in components} == {frozenset({a, b}), frozenset({c, d})}


def test_is_too_short_below_min_lines() -> None:
    assert is_too_short(Fragment(Path("a.py"), 1, 3)) is True


def test_is_too_short_at_min_lines() -> None:
    assert is_too_short(Fragment(Path("a.py"), 1, 5)) is False


def test_is_codegen_dir_matches_generated_model_directories() -> None:
    assert is_codegen_dir(REPO_ROOT_STUB / CODEGEN_DIRS[0] / "light.py", REPO_ROOT_STUB) is True


def test_is_codegen_dir_does_not_match_ordinary_source() -> None:
    assert is_codegen_dir(REPO_ROOT_STUB / CODEGEN_DIRS[0].parent / "app.py", REPO_ROOT_STUB) is False


def test_is_generated_marker_file_detects_banner(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("generated.py", '"""Do not edit this file directly."""\n')
    assert is_generated_marker_file(path) is True


def test_is_generated_marker_file_absent(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("normal.py", '"""A normal module."""\n')
    assert is_generated_marker_file(path) is False


def test_is_dup_ignore_file_python(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    path = write_file("ignored.py", "# dup-ignore-file: HA helper models share fields by API design\nx = 1\n")
    is_dup_ignore_file.cache_clear()
    assert is_dup_ignore_file(path, tmp_path) is True


def test_is_dup_ignore_file_typescript(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    path = write_file("ignored.ts", "// dup-ignore-file: MSW handlers mirror route structure\nexport {};\n")
    is_dup_ignore_file.cache_clear()
    assert is_dup_ignore_file(path, tmp_path) is True


def test_is_dup_ignore_file_false_for_ordinary(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    path = write_file("normal.py", "x = 1\n")
    is_dup_ignore_file.cache_clear()
    assert is_dup_ignore_file(path, tmp_path) is False


def test_is_dup_ignore_file_requires_reason(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    path = write_file("bad.py", "# dup-ignore-file:\n")
    is_dup_ignore_file.cache_clear()
    with pytest.raises(IgnoreMarkerError, match="requires a reason"):
        is_dup_ignore_file(path, tmp_path)


def test_is_excluded_file_true_for_generated_marker(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    path = write_file("generated.py", "# Do not edit this file directly\n")
    assert is_excluded_file(path, tmp_path) is True


def test_is_excluded_file_true_for_self() -> None:
    self_path = Path(check_duplicate_code.__file__)
    assert is_excluded_file(self_path, check_duplicate_code.REPO_ROOT) is True


def test_is_dup_ignore_file_false_for_self() -> None:
    """The tool's docstring contains a literal ``# dup-ignore-file: <reason>`` example.

    The regex would match it, but is_dup_ignore_file explicitly excludes its own source
    so the docstring example never accidentally suppresses the tool's own findings.
    """
    is_dup_ignore_file.cache_clear()
    self_path = Path(check_duplicate_code.__file__)
    assert is_dup_ignore_file(self_path, check_duplicate_code.REPO_ROOT) is False


def test_is_excluded_file_false_for_ordinary_file(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    path = write_file("normal.py", "x = 1\n")
    assert is_excluded_file(path, tmp_path) is False


@pytest.mark.parametrize(
    "rel_path",
    [
        "frontend/src/api/generated-types.ts",
        "frontend/src/api/ws-types.ts",
        "frontend/src/foo.d.ts",
        "frontend/src/api/foo.generated.ts",
        "tests/snapshots/cli_help.txt",
        "frontend/src/styles/fonts.css",
    ],
)
def test_is_ignored_glob_matches(rel_path: str) -> None:
    assert is_ignored_glob(Path(rel_path), REPO_ROOT_STUB) is True


def test_is_ignored_glob_does_not_match_ordinary_file() -> None:
    assert is_ignored_glob(Path("frontend/src/hooks/use-websocket.ts"), REPO_ROOT_STUB) is False


def test_is_dup_ignored_true_inside_marker_range(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "ok.py",
        "def f():\n    # dup-ignore-start: shared setup pattern, intentional\n    x = 1\n    # dup-ignore-end\n",
    )
    assert is_dup_ignored(Fragment(path, 3, 3)) is True


def test_is_dup_ignored_false_outside_marker_range(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "ok.py",
        "def f():\n    # dup-ignore-start: shared setup pattern, intentional\n    x = 1\n    # dup-ignore-end\n",
    )
    assert is_dup_ignored(Fragment(path, 1, 1)) is False


def test_dup_ignore_marker_recognized_with_slash_comment_syntax(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "ok.ts",
        "function f() {\n"
        "  // dup-ignore-start: shared setup pattern, intentional\n"
        "  const x = 1;\n"
        "  // dup-ignore-end\n"
        "}\n",
    )
    assert is_dup_ignored(Fragment(path, 3, 3)) is True


def test_unbalanced_start_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("bad.py", "def f():\n    # dup-ignore-start: never closed\n    x = 1\n")
    with pytest.raises(IgnoreMarkerError, match="never closed"):
        is_dup_ignored(Fragment(path, 3, 3))


def test_dangling_end_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    path = write_file("bad.py", "def f():\n    x = 1\n    # dup-ignore-end\n")
    with pytest.raises(IgnoreMarkerError, match="no matching dup-ignore-start"):
        is_dup_ignored(Fragment(path, 2, 2))


def test_nested_start_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    path = write_file(
        "bad.py",
        "# dup-ignore-start: outer\nx = 1\n# dup-ignore-start: inner\ny = 2\n# dup-ignore-end\n",
    )
    with pytest.raises(IgnoreMarkerError, match="nested dup-ignore-start"):
        is_dup_ignored(Fragment(path, 2, 2))


def test_empty_reason_start_marker_raises(write_file: Callable[[str, str], Path]) -> None:
    # Regression: the marker regex used to require a non-empty reason to match at all, so
    # "# dup-ignore-start:" with nothing after the colon silently failed to register as a
    # marker — the checker error then pointed at the wrong problem ("no matching start")
    # instead of the real one (empty reason). It must now fail loudly and specifically.
    path = write_file("bad.py", "# dup-ignore-start:\nx = 1\n# dup-ignore-end\n")
    with pytest.raises(IgnoreMarkerError, match="requires a reason"):
        is_dup_ignored(Fragment(path, 2, 2))


def test_marker_not_triggered_by_prose_mention(write_file: Callable[[str, str], Path]) -> None:
    # Regression: the marker regex used to match as a plain substring anywhere on the line, so
    # prose *mentioning* the marker syntax (e.g. explaining it in a docstring) registered as a
    # real marker. It must only count as the line's actual leading comment.
    path = write_file(
        "prose.py",
        '"""See `# dup-ignore-start: reason` / `# dup-ignore-end` for the escape hatch syntax."""\n',
    )
    assert ignore_ranges(path) == ()


def test_marker_not_triggered_by_own_source_file() -> None:
    # Regression, reproduced directly against the checker's own source: tools/ is itself in
    # PYTHON_SCAN_PATHS, and this file's docstring explanation of the marker syntax plus
    # IGNORE_START_RE/IGNORE_END_RE's own literal pattern text used to trip the marker parser
    # on itself (raised "nested dup-ignore-start" scanning its own module docstring).
    self_path = Path(check_duplicate_code.__file__)
    ignore_ranges(self_path)  # must not raise IgnoreMarkerError


def test_validate_markers_raises_on_marker_never_seen_by_pmd(
    write_file: Callable[[str, str], Path], tmp_path: Path
) -> None:
    # Regression for the gap chatgpt-codex-connector flagged on PR #1572: find_violations only
    # calls is_dup_ignored/ignore_ranges on fragments inside a 3+-occurrence PMD cluster, so a
    # malformed marker on code with no duplication at all — never seen by PMD, so never on that
    # path — used to pass the checker silently. validate_markers is the eager, PMD-independent
    # pass that closes the gap by parsing every marker in every scanned file up front.
    path = write_file("bad.py", "def f():\n    # dup-ignore-start: never closed\n    x = 1\n")
    with pytest.raises(IgnoreMarkerError, match="never closed"):
        validate_markers([path], tmp_path)


def test_validate_markers_passes_for_well_formed_marker(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    path = write_file(
        "ok.py",
        "def f():\n    # dup-ignore-start: shared setup pattern, intentional\n    x = 1\n    # dup-ignore-end\n",
    )
    validate_markers([path], tmp_path)  # must not raise


def test_validate_markers_skips_ignored_glob_files(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    # A malformed marker inside a generated file (e.g. accidental marker-like text in a codegen
    # template) must not fail the checker — IGNORE_GLOBS files are out of scope entirely.
    path = write_file("generated-types.ts", "// dup-ignore-start: never closed\nconst x = 1;\n")
    validate_markers([path], tmp_path)  # must not raise


def test_validate_markers_skips_generated_marker_files(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    # is_excluded_file() already treats a "Do not edit this file directly" banner file as fully
    # out of scope for duplication checking (is_dropped short-circuits on it before is_dup_ignore_file
    # is ever reached) — a stray/malformed marker in one is never load-bearing and must not fail CI.
    path = write_file(
        "generated.py",
        "# Do not edit this file directly.\n# dup-ignore-start: never closed\nx = 1\n",
    )
    validate_markers([path], tmp_path)  # must not raise


def test_scanned_files_includes_python_and_typescript() -> None:
    # scanned_files() always walks whatever repo_root it's given — this test passes the real
    # REPO_ROOT, so it's a smoke test against the real repo tree, not a characterization of
    # specific file contents.
    files = check_duplicate_code.scanned_files(check_duplicate_code.REPO_ROOT)
    assert any(f.suffix == ".py" for f in files)
    assert any(f.suffix in (".ts", ".tsx") for f in files)


def test_find_violations_below_min_occurrences_not_flagged(
    write_file: Callable[[str, str], Path], tmp_path: Path
) -> None:
    a = write_file("a.py", "def f():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    b = write_file("b.py", "def g():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    blocks = [[Fragment(a, 1, 5), Fragment(b, 1, 5)]]
    assert find_violations(blocks, tmp_path) == []


def test_find_violations_at_min_occurrences_flagged(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    a = write_file("a.py", "def f():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    b = write_file("b.py", "def g():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    c = write_file("c.py", "def h():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n")
    blocks = [[Fragment(a, 1, 5), Fragment(b, 1, 5), Fragment(c, 1, 5)]]
    violations = find_violations(blocks, tmp_path)
    assert len(violations) == 1
    assert set(violations[0]) == {Fragment(a, 1, 5), Fragment(b, 1, 5), Fragment(c, 1, 5)}


def test_find_violations_suppressed_when_fully_dup_ignored(
    write_file: Callable[[str, str], Path], tmp_path: Path
) -> None:
    marked = (
        "def f():\n"
        "    # dup-ignore-start: intentional shared shape\n"
        "    x = 1\n    y = 2\n    z = 3\n"
        "    # dup-ignore-end\n"
    )
    a = write_file("a.py", marked)
    b = write_file("b.py", marked)
    c = write_file("c.py", marked)
    blocks = [[Fragment(a, 3, 5), Fragment(b, 3, 5), Fragment(c, 3, 5)]]
    assert find_violations(blocks, tmp_path) == []


def test_find_violations_not_suppressed_when_partially_dup_ignored(
    write_file: Callable[[str, str], Path], tmp_path: Path
) -> None:
    marked = (
        "def f():\n"
        "    # dup-ignore-start: intentional shared shape\n"
        "    x = 1\n    y = 2\n    z = 3\n    w = 4\n    v = 5\n"
        "    # dup-ignore-end\n"
    )
    unmarked = "def h():\n    x = 1\n    y = 2\n    z = 3\n    w = 4\n    v = 5\n"
    a = write_file("a.py", marked)
    b = write_file("b.py", marked)
    c = write_file("c.py", unmarked)
    blocks = [[Fragment(a, 3, 7), Fragment(b, 3, 7), Fragment(c, 2, 6)]]
    assert len(find_violations(blocks, tmp_path)) == 1


def test_build_edges_drops_too_short_fragments(write_file: Callable[[str, str], Path], tmp_path: Path) -> None:
    a = write_file("a.py", "x = 1\ny = 2\n")
    b = write_file("b.py", "x = 1\ny = 2\n")
    blocks = [[Fragment(a, 1, 2), Fragment(b, 1, 2)]]
    assert build_edges(blocks, tmp_path) == []


def test_build_edges_drops_boilerplate_import_only_fragment(
    write_file: Callable[[str, str], Path], tmp_path: Path
) -> None:
    content = "import os\nimport sys\nimport json\nimport re\nimport ast\n"
    a = write_file("a.py", content)
    b = write_file("b.py", content)
    blocks = [[Fragment(a, 1, 5), Fragment(b, 1, 5)]]
    assert build_edges(blocks, tmp_path) == []


def test_fragment_from_file_element_parses_pmd_xml() -> None:
    xml = f"""<duplication xmlns="{CPD_NS["cpd"]}">
        <file path="/repo/tests/foo.py" line="10" endline="20"/>
    </duplication>"""
    element = ET.fromstring(xml).find("cpd:file", CPD_NS)  # noqa: S314 -- trusted literal test fixture
    assert element is not None
    fragment = fragment_from_file_element(element)
    assert fragment == Fragment(Path("/repo/tests/foo.py"), 10, 20)


def test_fragment_from_file_element_missing_attribute_raises() -> None:
    xml = f'<file xmlns="{CPD_NS["cpd"]}" path="/repo/tests/foo.py" line="10"/>'
    element = ET.fromstring(xml)  # noqa: S314 -- trusted literal test fixture
    with pytest.raises(ValueError, match="missing path/line/endline"):
        fragment_from_file_element(element)


def test_duplication_blocks_parses_multiple_occurrences() -> None:
    xml = f"""<pmd-cpd xmlns="{CPD_NS["cpd"]}">
        <duplication lines="10" tokens="50">
            <file path="/repo/a.py" line="1" endline="10"/>
            <file path="/repo/b.py" line="5" endline="14"/>
            <file path="/repo/c.py" line="8" endline="17"/>
        </duplication>
    </pmd-cpd>"""
    blocks = duplication_blocks(ET.fromstring(xml))  # noqa: S314 -- trusted literal test fixture
    assert blocks == [
        [
            Fragment(Path("/repo/a.py"), 1, 10),
            Fragment(Path("/repo/b.py"), 5, 14),
            Fragment(Path("/repo/c.py"), 8, 17),
        ]
    ]


def test_duplication_blocks_empty_report_returns_no_blocks() -> None:
    xml = f'<pmd-cpd xmlns="{CPD_NS["cpd"]}"></pmd-cpd>'
    assert duplication_blocks(ET.fromstring(xml)) == []  # noqa: S314 -- trusted literal test fixture


def test_cluster_file_counts_counts_fragments_per_file() -> None:
    component = [
        Fragment(REPO_ROOT_STUB / "scheduler.py", 1, 5),
        Fragment(REPO_ROOT_STUB / "scheduler.py", 20, 24),
        Fragment(REPO_ROOT_STUB / "other.py", 1, 5),
    ]
    assert cluster_file_counts(component, REPO_ROOT_STUB) == Counter({Path("scheduler.py"): 2, Path("other.py"): 1})


def test_cluster_file_counts_applies_renames() -> None:
    component = [Fragment(REPO_ROOT_STUB / "new_name.py", 1, 5)]
    renames = {Path("new_name.py"): Path("old_name.py")}
    assert cluster_file_counts(component, REPO_ROOT_STUB, renames) == Counter({Path("old_name.py"): 1})


def test_new_code_violations_flags_a_cluster_with_no_base_match() -> None:
    # A wholly new 3-way match -- nothing in the base scan covers it at all.
    a = Fragment(REPO_ROOT_STUB / "a.py", 1, 5)
    b = Fragment(REPO_ROOT_STUB / "b.py", 1, 5)
    c = Fragment(REPO_ROOT_STUB / "c.py", 1, 5)
    violations = [[a, b, c]]
    assert new_code_violations(violations, [], {}, REPO_ROOT_STUB) == violations


def test_new_code_violations_ignores_a_cluster_fully_covered_by_a_base_cluster() -> None:
    # Same three files, same per-file counts, as an existing base cluster -- e.g. a variable
    # rename or a pure reformat (which changes a fragment's Git lines without changing which
    # files it duplicates) must not count as new debt, however much of the diff it touches.
    a = Fragment(REPO_ROOT_STUB / "a.py", 1, 10)
    b = Fragment(REPO_ROOT_STUB / "b.py", 1, 10)
    c = Fragment(REPO_ROOT_STUB / "c.py", 1, 10)
    violations = [[a, b, c]]
    base_counts = [Counter({Path("a.py"): 1, Path("b.py"): 1, Path("c.py"): 1})]
    assert new_code_violations(violations, base_counts, {}, REPO_ROOT_STUB) == []


def test_new_code_violations_flags_an_extra_occurrence_added_to_existing_debt() -> None:
    # a/b/c already formed a violation at the merge-base; this PR adds a 4th copy in a new
    # file. The cluster gained a member relative to any single base cluster that covers it, so
    # it's still this PR's fault even though three of its four fragments are untouched.
    a = Fragment(REPO_ROOT_STUB / "a.py", 1, 5)
    b = Fragment(REPO_ROOT_STUB / "b.py", 1, 5)
    c = Fragment(REPO_ROOT_STUB / "c.py", 1, 5)
    new_dup = Fragment(REPO_ROOT_STUB / "new_dup.py", 1, 5)
    violations = [[a, b, c, new_dup]]
    base_counts = [Counter({Path("a.py"): 1, Path("b.py"): 1, Path("c.py"): 1})]
    assert new_code_violations(violations, base_counts, {}, REPO_ROOT_STUB) == violations


def test_new_code_violations_flags_an_extra_same_file_occurrence() -> None:
    # scheduler.py already contributes 2 fragments to an existing cluster with other.py; this PR
    # adds a 3rd near-identical block to scheduler.py itself. File-set matching alone would miss
    # this (scheduler.py was already "in" the base cluster) -- per-file *counts* catch it.
    scheduler_1 = Fragment(REPO_ROOT_STUB / "scheduler.py", 1, 5)
    scheduler_2 = Fragment(REPO_ROOT_STUB / "scheduler.py", 20, 24)
    scheduler_3 = Fragment(REPO_ROOT_STUB / "scheduler.py", 40, 44)
    other = Fragment(REPO_ROOT_STUB / "other.py", 1, 5)
    violations = [[scheduler_1, scheduler_2, scheduler_3, other]]
    base_counts = [Counter({Path("scheduler.py"): 2, Path("other.py"): 1})]
    assert new_code_violations(violations, base_counts, {}, REPO_ROOT_STUB) == violations


def test_new_code_violations_flags_a_new_cluster_formed_by_a_small_edit() -> None:
    # x/y/z weren't a 3-way match at the merge-base (each only appears in its own, unrelated
    # base cluster) -- a small edit to x that newly joins it with y and z must still be caught,
    # even though the edit itself is tiny relative to any one fragment's size.
    x = Fragment(REPO_ROOT_STUB / "x.py", 1, 10)
    y = Fragment(REPO_ROOT_STUB / "y.py", 1, 10)
    z = Fragment(REPO_ROOT_STUB / "z.py", 1, 10)
    violations = [[x, y, z]]
    base_counts = [
        Counter({Path("x.py"): 1, Path("unrelated_1.py"): 1, Path("unrelated_2.py"): 1}),
        Counter({Path("y.py"): 1, Path("z.py"): 1, Path("unrelated_3.py"): 1}),
    ]
    assert new_code_violations(violations, base_counts, {}, REPO_ROOT_STUB) == violations


def test_new_code_violations_resolves_a_head_side_rename_against_the_base_cluster() -> None:
    a_renamed = Fragment(REPO_ROOT_STUB / "a_new_name.py", 1, 5)
    b = Fragment(REPO_ROOT_STUB / "b.py", 1, 5)
    c = Fragment(REPO_ROOT_STUB / "c.py", 1, 5)
    violations = [[a_renamed, b, c]]
    renames = {Path("a_new_name.py"): Path("a.py")}
    base_counts = [Counter({Path("a.py"): 1, Path("b.py"): 1, Path("c.py"): 1})]
    assert new_code_violations(violations, base_counts, renames, REPO_ROOT_STUB) == []


def test_new_code_violations_flags_a_renamed_file_that_also_gained_an_occurrence() -> None:
    # a_new_name.py (renamed from a.py) now contributes 2 fragments to this cluster, but the base
    # cluster only had 1 fragment in a.py -- the rename resolves correctly, but the count still
    # doesn't fit, so this must be flagged (composes the rename and same-file-count-increase
    # behaviors pinned separately above).
    a_renamed_1 = Fragment(REPO_ROOT_STUB / "a_new_name.py", 1, 5)
    a_renamed_2 = Fragment(REPO_ROOT_STUB / "a_new_name.py", 20, 24)
    b = Fragment(REPO_ROOT_STUB / "b.py", 1, 5)
    c = Fragment(REPO_ROOT_STUB / "c.py", 1, 5)
    violations = [[a_renamed_1, a_renamed_2, b, c]]
    renames = {Path("a_new_name.py"): Path("a.py")}
    base_counts = [Counter({Path("a.py"): 1, Path("b.py"): 1, Path("c.py"): 1})]
    assert new_code_violations(violations, base_counts, renames, REPO_ROOT_STUB) == violations


def test_new_code_violations_leaves_untouched_clusters_out_of_a_mixed_result() -> None:
    new_a = Fragment(REPO_ROOT_STUB / "new_a.py", 1, 5)
    new_b = Fragment(REPO_ROOT_STUB / "new_b.py", 1, 5)
    new_c = Fragment(REPO_ROOT_STUB / "new_c.py", 1, 5)
    old_a = Fragment(REPO_ROOT_STUB / "old_a.py", 1, 5)
    old_b = Fragment(REPO_ROOT_STUB / "old_b.py", 1, 5)
    old_c = Fragment(REPO_ROOT_STUB / "old_c.py", 1, 5)
    new_cluster = [new_a, new_b, new_c]
    old_cluster = [old_a, old_b, old_c]
    base_counts = [Counter({Path("old_a.py"): 1, Path("old_b.py"): 1, Path("old_c.py"): 1})]
    assert new_code_violations([new_cluster, old_cluster], base_counts, {}, REPO_ROOT_STUB) == [new_cluster]


def test_scan_tree_at_ref_scans_that_refs_own_tree(git_repo: GitRepo, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(check_duplicate_code, "REPO_ROOT", git_repo.root)

    git_repo.write("marker.txt", "base content\n")
    base = git_repo.commit("base")
    git_repo.write("marker.txt", "head content, unrelated to base\n")
    git_repo.commit("head")

    seen_roots: list[Path] = []

    def fake_run_scan(repo_root: Path) -> list[list[Fragment]]:
        seen_roots.append(repo_root)
        # Prove the materialized tree really is `base`'s content, not the live head checkout.
        assert (repo_root / "marker.txt").read_text() == "base content\n"
        return [[Fragment(repo_root / "a.py", 1, 5), Fragment(repo_root / "b.py", 1, 5)]]

    monkeypatch.setattr(check_duplicate_code, "run_scan", fake_run_scan)

    result = check_duplicate_code.scan_tree_at_ref(base)

    assert result == [Counter({Path("a.py"): 1, Path("b.py"): 1})]
    assert len(seen_roots) == 1
    assert not seen_roots[0].exists()  # throwaway directory cleaned up after the call returns


def test_scan_tree_at_ref_raises_a_clear_error_for_an_unresolvable_ref(
    git_repo: GitRepo, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(check_duplicate_code, "REPO_ROOT", git_repo.root)
    git_repo.write("a.py", "x = 1\n")
    git_repo.commit("only commit")

    with pytest.raises(RuntimeError, match="couldn't materialize"):
        check_duplicate_code.scan_tree_at_ref("not-a-real-ref")


def test_main_resolves_merge_base_not_a_diverged_base_ref_tip(
    git_repo: GitRepo, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    # base_ref is the PR's raw base ref, which may have moved past the PR's actual branch point
    # by the time CI runs. main() must diff against the merge-base, not base_ref's live tip --
    # otherwise an unrelated commit on the base branch could hide this PR's own newly-introduced
    # duplicate (or wrongly blame it for someone else's).
    monkeypatch.setattr(check_duplicate_code, "REPO_ROOT", git_repo.root)

    git_repo.write("a.py", "shared\n" * 5)
    git_repo.write("b.py", "shared\n" * 5)
    git_repo.write("c.py", "shared\n" * 5)
    branch_point = git_repo.commit("branch point")

    git_repo.write("new_dup.py", "shared\n" * 5)
    head = git_repo.commit("PR introduces a new duplicate")

    # Base branch moves on, unrelated to the PR, after the branch point.
    diverged_base_tip = git_repo.diverge("unrelated.py", "noise\n", "unrelated base branch commit", branch_point)

    head_violations = [
        [
            Fragment(git_repo.root / "a.py", 1, 5),
            Fragment(git_repo.root / "b.py", 1, 5),
            Fragment(git_repo.root / "c.py", 1, 5),
            Fragment(git_repo.root / "new_dup.py", 1, 5),
        ]
    ]
    monkeypatch.setattr(check_duplicate_code, "run_scan", lambda _repo_root: head_violations)

    seen_refs: list[str] = []

    def fake_scan_tree_at_ref(ref: str) -> list[Counter[Path]]:
        seen_refs.append(ref)
        return [Counter({Path("a.py"): 1, Path("b.py"): 1, Path("c.py"): 1})]

    monkeypatch.setattr(check_duplicate_code, "scan_tree_at_ref", fake_scan_tree_at_ref)
    monkeypatch.setattr(sys, "argv", ["check_duplicate_code.py", "--gate-new-code", diverged_base_tip, head])

    exit_code = check_duplicate_code.main()

    assert exit_code == 1
    assert seen_refs == [branch_point]  # the merge-base, not diverged_base_tip
    assert "new_dup.py" in capsys.readouterr().out


def test_main_skips_the_merge_base_scan_when_head_has_no_violations(
    git_repo: GitRepo, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(check_duplicate_code, "REPO_ROOT", git_repo.root)
    monkeypatch.setattr(check_duplicate_code, "run_scan", lambda _repo_root: [])

    def fail_if_called(_ref: str) -> list[Counter[Path]]:
        raise AssertionError("scan_tree_at_ref must not run when the head scan found nothing to disambiguate")

    monkeypatch.setattr(check_duplicate_code, "scan_tree_at_ref", fail_if_called)

    git_repo.write("a.py", "x = 1\n")
    base = git_repo.commit("base")
    git_repo.write("b.py", "y = 2\n")
    head = git_repo.commit("head")
    monkeypatch.setattr(sys, "argv", ["check_duplicate_code.py", "--gate-new-code", base, head])

    assert check_duplicate_code.main() == 0
