"""Synchronous recording facade for RecordingApi.

Do not edit this file directly.

It is generated from RecordingApi by tools/generate_sync_facade.py.
"""

import copy
import typing
from collections.abc import Generator
from enum import StrEnum
from typing import Any, cast

import aiohttp
from whenever import Date, PlainDateTime, ZonedDateTime

from hassette.const.misc import FalseySentinel
from hassette.exceptions import EntityNotFoundError, FailedMessageError
from hassette.models.entities.base import BaseEntity
from hassette.models.helpers import (
    CounterRecord,
    CreateCounterParams,
    CreateInputBooleanParams,
    CreateInputButtonParams,
    CreateInputDatetimeParams,
    CreateInputNumberParams,
    CreateInputSelectParams,
    CreateInputTextParams,
    CreateTimerParams,
    InputBooleanRecord,
    InputButtonRecord,
    InputDatetimeRecord,
    InputNumberRecord,
    InputSelectRecord,
    InputTextRecord,
    TimerRecord,
    UpdateCounterParams,
    UpdateInputBooleanParams,
    UpdateInputButtonParams,
    UpdateInputDatetimeParams,
    UpdateInputNumberParams,
    UpdateInputSelectParams,
    UpdateInputTextParams,
    UpdateTimerParams,
)
from hassette.models.history import HistoryEntry
from hassette.models.services import ServiceResponse
from hassette.models.states.base import BaseState, Context
from hassette.test_utils.api_call import ApiCall

if typing.TYPE_CHECKING:
    from hassette.events import HassStateDict
    from hassette.test_utils.recording_api import RecordingApi

# ---------------------------------------------------------------------------
# Stub message templates — imported by tests to avoid brittle substring matches.
# Must stay byte-identical with the constants in tools/generate_sync_facade.py.
# ---------------------------------------------------------------------------
_STUB_MSG_STATE_CONVERSION = (
    "RecordingApi.sync.{name} is not implemented on the test facade. "
    "Call `harness.api_recorder.sync.get_state(entity_id)` and read the returned state directly."
)
_STUB_MSG_GENERIC = (
    "RecordingApi.sync.{name} is not implemented. "
    "Seed state via AppTestHarness.set_state() for read methods, "
    "or use a full integration test for methods requiring a live HA connection."
)


class _RecordingSyncFacade:  # pyright: ignore[reportUnusedClass]
    """Synchronous recording facade for RecordingApi.

    Instances are created by RecordingApi.__init__ and share the parent's
    `calls` list via the `_parent` reference. Users access it via `harness.api_recorder.sync`
    (which is `RecordingApi.sync`).

    This file is generated by tools/generate_sync_facade.py — do not edit by hand.
    """

    _parent: "RecordingApi"

    def __init__(self, parent: "RecordingApi") -> None:
        self._parent = parent

    # NOTE: __getattr__ raises AttributeError for names starting with `_`, including `_parent`.
    # If `_parent` lookup falls through here (e.g., during mock construction before __init__
    # completes, or in a subclass that skips super().__init__), the error will be
    # AttributeError: _parent — which is by design; partial construction is an error.
    def __getattr__(self, name: str) -> Any:
        """Raise NotImplementedError for public attributes not defined on _RecordingSyncFacade.

        Private attributes fall through to the default AttributeError so that Python
        machinery works correctly. All known public methods from ``ApiSyncFacade``
        are explicitly generated (either body-copied from RecordingApi or stubbed
        with NotImplementedError). This fallback catches any public attribute that
        is not a generated method — typically a typo or a brand-new method on
        ``ApiSyncFacade`` that the CI drift gate is about to flag.
        """
        if name.startswith("_"):
            raise AttributeError(name)

        raise NotImplementedError(_STUB_MSG_GENERIC.format(name=name))

    def ws_send_and_wait(self, **data: Any) -> Any:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="ws_send_and_wait"))

    def ws_send_json(self, **data: Any) -> None:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="ws_send_json"))

    def rest_request(
        self,
        method: str,
        url: str,
        params: dict[str, Any] | None = None,
        data: dict[str, Any] | None = None,
        suppress_error_message: bool = False,
        **kwargs,
    ) -> aiohttp.ClientResponse:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="rest_request"))

    def get_rest_request(self, url: str, params: dict[str, Any] | None = None, **kwargs) -> aiohttp.ClientResponse:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_rest_request"))

    def post_rest_request(self, url: str, data: dict[str, Any] | None = None, **kwargs) -> aiohttp.ClientResponse:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="post_rest_request"))

    def delete_rest_request(self, url: str, **kwargs) -> aiohttp.ClientResponse:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="delete_rest_request"))

    def get_states_raw(self) -> list["HassStateDict"]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_states_raw"))

    def get_states(self) -> list[BaseState]:
        """Return typed states for all seeded entities."""

        items = list(self._parent._state_proxy.states.items())
        return [self._parent._convert_state(raw, eid) for eid, raw in items]

    def get_states_iterator(self) -> Generator["BaseState[Any]", Any, None]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_states_iterator"))

    def get_config(self) -> dict[str, Any]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_config"))

    def get_services(self) -> dict[str, Any]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_services"))

    def get_panels(self) -> dict[str, Any]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_panels"))

    def fire_event(self, event_type: str, event_data: dict[str, Any] | None = None) -> dict[str, Any]:
        """Record a fire_event call. Returns an empty dict stub."""

        self._parent.calls.append(
            ApiCall(
                method="fire_event",
                args=(event_type,),
                kwargs={"event_type": event_type, "event_data": copy.deepcopy(event_data)},
            )
        )
        return {}

    def call_service(
        self,
        domain: str,
        service: str,
        target: dict[str, str] | dict[str, list[str]] | None = None,
        return_response: bool | None = False,
        **data,
    ) -> ServiceResponse | None:
        """Record a call_service call. Returns stub ServiceResponse when return_response=True."""

        self._parent.calls.append(
            ApiCall(
                method="call_service",
                args=(domain, service),
                kwargs={
                    "domain": domain,
                    "service": service,
                    "target": copy.deepcopy(target),
                    "return_response": return_response,
                    **data,
                },
            )
        )
        if return_response:
            return ServiceResponse(context=Context(id=None, parent_id=None, user_id=None))
        return None

    def turn_on(self, entity_id: str | StrEnum, domain: str = "homeassistant", **data) -> None:
        """Record a turn_on call directly under its own method name."""

        entity_id = str(entity_id)
        self._parent.calls.append(
            ApiCall(method="turn_on", args=(entity_id,), kwargs={"entity_id": entity_id, "domain": domain, **data})
        )

    def turn_off(self, entity_id: str | StrEnum, domain: str = "homeassistant") -> None:
        """Record a turn_off call directly under its own method name."""

        entity_id = str(entity_id)
        self._parent.calls.append(
            ApiCall(method="turn_off", args=(entity_id,), kwargs={"entity_id": entity_id, "domain": domain})
        )

    def toggle_service(self, entity_id: str | StrEnum, domain: str = "homeassistant") -> None:
        """Record a toggle_service call directly under its own method name."""

        entity_id = str(entity_id)
        self._parent.calls.append(
            ApiCall(method="toggle_service", args=(entity_id,), kwargs={"entity_id": entity_id, "domain": domain})
        )

    def get_state_raw(self, entity_id: str) -> "HassStateDict":
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_state_raw"))

    def entity_exists(self, entity_id: str) -> bool:
        """Return True if entity_id is seeded in the StateProxy."""

        return entity_id in self._parent._state_proxy.states

    def get_entity(self, entity_id: str, model: type[BaseEntity]) -> BaseEntity:
        """Return a pydantic-validated entity wrapper for entity_id.

        Matches the real ``Api.get_entity`` signature exactly — ``model`` is required
        and must be a :class:`~hassette.models.entities.base.BaseEntity` subclass.
        Callers that want registry-converted state without a specific entity model
        should call :meth:`get_state` instead.

        Raises:
            TypeError: If ``model`` is not a ``BaseEntity`` subclass.
            EntityNotFoundError: If ``entity_id`` is not seeded."""

        if not issubclass(model, BaseEntity):
            raise TypeError(f"Model {model!r} is not a valid BaseEntity subclass")
        raw = self._parent._get_raw_state(entity_id)
        return model.model_validate({"state": raw})

    def get_entity_or_none(self, entity_id: str, model: type[BaseEntity]) -> BaseEntity | None:
        """Return a pydantic-validated entity wrapper for entity_id, or None if not seeded.

        Inlines the logic from :meth:`get_entity` using sync helpers only — no peer
        ``async def`` calls on ``self`` — to satisfy the authoring constraint required
        by the ``_RecordingSyncFacade`` generator. Matches the real
        ``Api.get_entity_or_none`` signature; see :meth:`get_entity` for semantics."""

        if not issubclass(model, BaseEntity):
            raise TypeError(f"Model {model!r} is not a valid BaseEntity subclass")
        try:
            raw = self._parent._get_raw_state(entity_id)
        except EntityNotFoundError:
            return None
        return model.model_validate({"state": raw})

    def get_state(self, entity_id: str) -> BaseState:
        """Return the typed state for entity_id. Raises EntityNotFoundError if not seeded."""

        raw = self._parent._get_raw_state(entity_id)
        return self._parent._convert_state(raw, entity_id)

    def get_state_or_none(self, entity_id: str) -> BaseState | None:
        """Return the typed state for entity_id, or None if not seeded.

        Inlines the logic from :meth:`get_state` using sync helpers only — no peer
        ``async def`` calls on ``self`` — to satisfy the authoring constraint required
        by the ``_RecordingSyncFacade`` generator."""

        try:
            raw = self._parent._get_raw_state(entity_id)
        except EntityNotFoundError:
            return None
        return self._parent._convert_state(raw, entity_id)

    def get_state_value(self, entity_id: str) -> Any:
        raise NotImplementedError(_STUB_MSG_STATE_CONVERSION.format(name="get_state_value"))

    def get_state_value_typed(self, entity_id: str) -> "Any":
        raise NotImplementedError(_STUB_MSG_STATE_CONVERSION.format(name="get_state_value_typed"))

    def get_attribute(self, entity_id: str, attribute: str) -> Any | FalseySentinel:
        raise NotImplementedError(_STUB_MSG_STATE_CONVERSION.format(name="get_attribute"))

    def get_history(
        self,
        entity_id: str,
        start_time: PlainDateTime | ZonedDateTime | Date | str,
        end_time: PlainDateTime | ZonedDateTime | Date | str | None = None,
        significant_changes_only: bool = False,
        minimal_response: bool = False,
        no_attributes: bool = False,
    ) -> list[HistoryEntry]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_history"))

    def get_histories(
        self,
        entity_ids: list[str],
        start_time: PlainDateTime | ZonedDateTime | Date | str,
        end_time: PlainDateTime | ZonedDateTime | Date | str | None = None,
        significant_changes_only: bool = False,
        minimal_response: bool = False,
        no_attributes: bool = False,
    ) -> dict[str, list[HistoryEntry]]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_histories"))

    def get_logbook(
        self,
        entity_id: str,
        start_time: PlainDateTime | ZonedDateTime | Date | str,
        end_time: PlainDateTime | ZonedDateTime | Date | str,
    ) -> list[dict]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_logbook"))

    def set_state(self, entity_id: str | StrEnum, state: Any, attributes: dict[str, Any] | None = None) -> dict:
        """Record a set_state call. Returns an empty dict stub."""

        entity_id = str(entity_id)
        self._parent.calls.append(
            ApiCall(
                method="set_state",
                args=(entity_id, state),
                kwargs={"entity_id": entity_id, "state": state, "attributes": copy.deepcopy(attributes)},
            )
        )
        return {}

    def get_camera_image(
        self, entity_id: str, timestamp: PlainDateTime | ZonedDateTime | Date | str | None = None
    ) -> bytes:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_camera_image"))

    def get_calendars(self) -> list[dict]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_calendars"))

    def get_calendar_events(
        self,
        calendar_id: str,
        start_time: PlainDateTime | ZonedDateTime | Date | str,
        end_time: PlainDateTime | ZonedDateTime | Date | str,
    ) -> list[dict]:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="get_calendar_events"))

    def render_template(self, template: str, variables: dict | None = None) -> str:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="render_template"))

    def delete_entity(self, entity_id: str) -> None:
        raise NotImplementedError(_STUB_MSG_GENERIC.format(name="delete_entity"))

    def list_input_booleans(self) -> list[InputBooleanRecord]:
        """Return all seeded input_boolean helpers."""

        return cast("list[InputBooleanRecord]", list(self._parent.helper_definitions["input_boolean"].values()))

    def create_input_boolean(self, params: CreateInputBooleanParams) -> InputBooleanRecord:
        """Record the call and add a record to helper_definitions.

        Auto-suffixes on collision (mirrors HA's IDManager.generate_id)."""

        self._parent.calls.append(
            ApiCall(method="create_input_boolean", args=(), kwargs=params.model_dump(exclude_unset=True))
        )
        generated_id = self._parent._new_helper_id("input_boolean", params.name)
        record = InputBooleanRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_boolean"][record.id] = record
        return record

    def update_input_boolean(self, helper_id: str, params: UpdateInputBooleanParams) -> InputBooleanRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_input_boolean",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["input_boolean"]:
            raise FailedMessageError(
                f"input_boolean helper {helper_id!r} not found. Seed it via harness.seed_helper() first.",
                code="not_found",
            )
        existing = self._parent.helper_definitions["input_boolean"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_boolean"][helper_id] = updated
        return updated

    def delete_input_boolean(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(method="delete_input_boolean", args=(helper_id,), kwargs={"helper_id": helper_id})
        )
        if helper_id not in self._parent.helper_definitions["input_boolean"]:
            raise FailedMessageError(f"input_boolean helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["input_boolean"][helper_id]

    def list_input_numbers(self) -> list[InputNumberRecord]:
        """Return all seeded input_number helpers."""

        return cast("list[InputNumberRecord]", list(self._parent.helper_definitions["input_number"].values()))

    def create_input_number(self, params: CreateInputNumberParams) -> InputNumberRecord:
        """Record the call and add a record to helper_definitions."""

        self._parent.calls.append(
            ApiCall(method="create_input_number", args=(), kwargs=params.model_dump(exclude_unset=True))
        )
        generated_id = self._parent._new_helper_id("input_number", params.name)
        record = InputNumberRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_number"][record.id] = record
        return record

    def update_input_number(self, helper_id: str, params: UpdateInputNumberParams) -> InputNumberRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_input_number",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["input_number"]:
            raise FailedMessageError(
                f"input_number helper {helper_id!r} not found. Seed it via harness.seed_helper() first.",
                code="not_found",
            )
        existing = self._parent.helper_definitions["input_number"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_number"][helper_id] = updated
        return updated

    def delete_input_number(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(method="delete_input_number", args=(helper_id,), kwargs={"helper_id": helper_id})
        )
        if helper_id not in self._parent.helper_definitions["input_number"]:
            raise FailedMessageError(f"input_number helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["input_number"][helper_id]

    def list_input_texts(self) -> list[InputTextRecord]:
        """Return all seeded input_text helpers."""

        return cast("list[InputTextRecord]", list(self._parent.helper_definitions["input_text"].values()))

    def create_input_text(self, params: CreateInputTextParams) -> InputTextRecord:
        """Record the call and add a record to helper_definitions."""

        self._parent.calls.append(
            ApiCall(method="create_input_text", args=(), kwargs=params.model_dump(exclude_unset=True))
        )
        generated_id = self._parent._new_helper_id("input_text", params.name)
        record = InputTextRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_text"][record.id] = record
        return record

    def update_input_text(self, helper_id: str, params: UpdateInputTextParams) -> InputTextRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_input_text",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["input_text"]:
            raise FailedMessageError(
                f"input_text helper {helper_id!r} not found. Seed it via harness.seed_helper() first.", code="not_found"
            )
        existing = self._parent.helper_definitions["input_text"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_text"][helper_id] = updated
        return updated

    def delete_input_text(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(method="delete_input_text", args=(helper_id,), kwargs={"helper_id": helper_id})
        )
        if helper_id not in self._parent.helper_definitions["input_text"]:
            raise FailedMessageError(f"input_text helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["input_text"][helper_id]

    def list_input_selects(self) -> list[InputSelectRecord]:
        """Return all seeded input_select helpers."""

        return cast("list[InputSelectRecord]", list(self._parent.helper_definitions["input_select"].values()))

    def create_input_select(self, params: CreateInputSelectParams) -> InputSelectRecord:
        """Record the call and add a record to helper_definitions."""

        self._parent.calls.append(
            ApiCall(method="create_input_select", args=(), kwargs=params.model_dump(exclude_unset=True))
        )
        generated_id = self._parent._new_helper_id("input_select", params.name)
        record = InputSelectRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_select"][record.id] = record
        return record

    def update_input_select(self, helper_id: str, params: UpdateInputSelectParams) -> InputSelectRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_input_select",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["input_select"]:
            raise FailedMessageError(
                f"input_select helper {helper_id!r} not found. Seed it via harness.seed_helper() first.",
                code="not_found",
            )
        existing = self._parent.helper_definitions["input_select"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_select"][helper_id] = updated
        return updated

    def delete_input_select(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(method="delete_input_select", args=(helper_id,), kwargs={"helper_id": helper_id})
        )
        if helper_id not in self._parent.helper_definitions["input_select"]:
            raise FailedMessageError(f"input_select helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["input_select"][helper_id]

    def list_input_datetimes(self) -> list[InputDatetimeRecord]:
        """Return all seeded input_datetime helpers."""

        return cast("list[InputDatetimeRecord]", list(self._parent.helper_definitions["input_datetime"].values()))

    def create_input_datetime(self, params: CreateInputDatetimeParams) -> InputDatetimeRecord:
        """Record the call and add a record to helper_definitions."""

        self._parent.calls.append(
            ApiCall(method="create_input_datetime", args=(), kwargs=params.model_dump(exclude_unset=True))
        )
        generated_id = self._parent._new_helper_id("input_datetime", params.name)
        record = InputDatetimeRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_datetime"][record.id] = record
        return record

    def update_input_datetime(self, helper_id: str, params: UpdateInputDatetimeParams) -> InputDatetimeRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_input_datetime",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["input_datetime"]:
            raise FailedMessageError(
                f"input_datetime helper {helper_id!r} not found. Seed it via harness.seed_helper() first.",
                code="not_found",
            )
        existing = self._parent.helper_definitions["input_datetime"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_datetime"][helper_id] = updated
        return updated

    def delete_input_datetime(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(method="delete_input_datetime", args=(helper_id,), kwargs={"helper_id": helper_id})
        )
        if helper_id not in self._parent.helper_definitions["input_datetime"]:
            raise FailedMessageError(f"input_datetime helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["input_datetime"][helper_id]

    def list_input_buttons(self) -> list[InputButtonRecord]:
        """Return all seeded input_button helpers."""

        return cast("list[InputButtonRecord]", list(self._parent.helper_definitions["input_button"].values()))

    def create_input_button(self, params: CreateInputButtonParams) -> InputButtonRecord:
        """Record the call and add a record to helper_definitions."""

        self._parent.calls.append(
            ApiCall(method="create_input_button", args=(), kwargs=params.model_dump(exclude_unset=True))
        )
        generated_id = self._parent._new_helper_id("input_button", params.name)
        record = InputButtonRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_button"][record.id] = record
        return record

    def update_input_button(self, helper_id: str, params: UpdateInputButtonParams) -> InputButtonRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_input_button",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["input_button"]:
            raise FailedMessageError(
                f"input_button helper {helper_id!r} not found. Seed it via harness.seed_helper() first.",
                code="not_found",
            )
        existing = self._parent.helper_definitions["input_button"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["input_button"][helper_id] = updated
        return updated

    def delete_input_button(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(method="delete_input_button", args=(helper_id,), kwargs={"helper_id": helper_id})
        )
        if helper_id not in self._parent.helper_definitions["input_button"]:
            raise FailedMessageError(f"input_button helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["input_button"][helper_id]

    def list_counters(self) -> list[CounterRecord]:
        """Return all seeded counter helpers."""

        return cast("list[CounterRecord]", list(self._parent.helper_definitions["counter"].values()))

    def create_counter(self, params: CreateCounterParams) -> CounterRecord:
        """Record the call and add a record to helper_definitions."""

        self._parent.calls.append(
            ApiCall(method="create_counter", args=(), kwargs=params.model_dump(exclude_unset=True))
        )
        generated_id = self._parent._new_helper_id("counter", params.name)
        record = CounterRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["counter"][record.id] = record
        return record

    def update_counter(self, helper_id: str, params: UpdateCounterParams) -> CounterRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_counter",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["counter"]:
            raise FailedMessageError(
                f"counter helper {helper_id!r} not found. Seed it via harness.seed_helper() first.", code="not_found"
            )
        existing = self._parent.helper_definitions["counter"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["counter"][helper_id] = updated
        return updated

    def delete_counter(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(ApiCall(method="delete_counter", args=(helper_id,), kwargs={"helper_id": helper_id}))
        if helper_id not in self._parent.helper_definitions["counter"]:
            raise FailedMessageError(f"counter helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["counter"][helper_id]

    def list_timers(self) -> list[TimerRecord]:
        """Return all seeded timer helpers."""

        return cast("list[TimerRecord]", list(self._parent.helper_definitions["timer"].values()))

    def create_timer(self, params: CreateTimerParams) -> TimerRecord:
        """Record the call and add a record to helper_definitions."""

        self._parent.calls.append(ApiCall(method="create_timer", args=(), kwargs=params.model_dump(exclude_unset=True)))
        generated_id = self._parent._new_helper_id("timer", params.name)
        record = TimerRecord(id=generated_id, **params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["timer"][record.id] = record
        return record

    def update_timer(self, helper_id: str, params: UpdateTimerParams) -> TimerRecord:
        """Record the call and mutate the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(
            ApiCall(
                method="update_timer",
                args=(helper_id,),
                kwargs={"helper_id": helper_id, **params.model_dump(exclude_unset=True)},
            )
        )
        if helper_id not in self._parent.helper_definitions["timer"]:
            raise FailedMessageError(
                f"timer helper {helper_id!r} not found. Seed it via harness.seed_helper() first.", code="not_found"
            )
        existing = self._parent.helper_definitions["timer"][helper_id]
        updated = existing.model_copy(update=params.model_dump(exclude_unset=True))
        self._parent.helper_definitions["timer"][helper_id] = updated
        return updated

    def delete_timer(self, helper_id: str) -> None:
        """Record the call and remove the seeded record.

        Raises:
            FailedMessageError: With code='not_found' if helper_id is not seeded."""

        self._parent.calls.append(ApiCall(method="delete_timer", args=(helper_id,), kwargs={"helper_id": helper_id}))
        if helper_id not in self._parent.helper_definitions["timer"]:
            raise FailedMessageError(f"timer helper {helper_id!r} not found.", code="not_found")
        del self._parent.helper_definitions["timer"][helper_id]

    def increment_counter(self, entity_id: str) -> None:
        """Record an increment_counter call directly (not via call_service)."""

        self._parent.calls.append(
            ApiCall(method="increment_counter", args=(entity_id,), kwargs={"entity_id": entity_id})
        )

    def decrement_counter(self, entity_id: str) -> None:
        """Record a decrement_counter call directly (not via call_service)."""

        self._parent.calls.append(
            ApiCall(method="decrement_counter", args=(entity_id,), kwargs={"entity_id": entity_id})
        )

    def reset_counter(self, entity_id: str) -> None:
        """Record a reset_counter call directly (not via call_service)."""

        self._parent.calls.append(ApiCall(method="reset_counter", args=(entity_id,), kwargs={"entity_id": entity_id}))
