#!/usr/bin/env python3
"""CI guard: flag a code block copy-pasted 3+ times, in one file or across many.

This exists because the failure mode it catches keeps recurring by hand: someone adds a new
sibling file (a new `tools/check_*.py` test, a new CLI subcommand, a new page component) — or a
new case in an existing file — by copying an existing block, and the third or fourth copy is the
one nobody notices until a clean-code sweep finds it. PMD CPD (https://pmd.github.io/pmd/pmd_userdocs_cpd.html)
does the raw clone detection; this script narrows its output to the shape that's actually worth a
human look.

PMD CPD, not jscpd: jscpd's Python/TypeScript tokenizers compare literal values and identifier
names exactly, so a block repeated 8 times with different assertion values or variable names only
shows up as scattered 2-3-occurrence pairs in its clone graph — undercounting real duplication.
PMD CPD's default tokenizer for these two languages already treats differing literals and
differing identifier names as equivalent when matching (verified empirically — PMD's own
`--ignore-literals`/`--ignore-identifiers` flags are no-ops here because the default already does
this), which is what actually fixes the undercounting. `MIN_TOKENS` is intentionally lower than a
naive port of jscpd's threshold would suggest — the same-shape matches between any two given
occurrences are shorter once literal/identifier noise no longer breaks them, and a higher
threshold silently drops real findings before they ever reach the clustering step below.

Two occurrences of a block is common in this codebase *by design* — a sync facade mirrors its
async source, two CLI subcommands for parallel resource types share structure, two Resource
subclasses share lifecycle plumbing. Requiring 3+ occurrences (via connected-component
clustering over PMD's pairwise clone graph — see `cluster()`) turns out to cleanly separate
"designed parallel structure" (stays a pair) from "this should have been extracted" (spreads as
more copies get added), without a threshold this loose flagging every legitimate pair.

Two categories are excluded automatically, before clustering, because they're mechanically
unambiguous and never need a human judgment call:
  - Files whose module docstring says "Do not edit this file directly" — the marker every
    codegen'd sync-facade file in this repo carries (see codegen/src/hassette_codegen/), plus
    the two codegen'd model directories that don't carry that marker (generated from HA core
    source; see CLAUDE.md's Architecture section). A human didn't choose to duplicate this.
  - Fragments whose every non-blank line is part of a module docstring or an `import`/`from
    ... import` statement — content that necessarily repeats across sibling files without being
    copy-paste debt. Checked by content (via `ast`), not by position — a fragment right after
    the imports (e.g. shared path-hacking setup) is real logic and stays in scope. Python-only:
    a TypeScript/TSX import block is never exempted by this check.

Everything else surfaces by default, including patterns this codebase has hand-decided to keep
(e.g. the "Shape B delegate" convenience-method convention in bus.py/scheduler.py). For those,
wrap the accepted occurrence in a marker pair — mirrors this repo's `# factory-local: <reason>`
convention, but as a start/end pair since a duplicate block spans multiple lines and pinning a
single marker to one line would mean guessing which line it governs. This is the "expected
duplication" escape hatch — the mechanism for a human to say "yes, I saw this, it's fine":

    # dup-ignore-start: <reason>
    ...block...
    # dup-ignore-end

(This example is itself live input to the parser it's documenting, since this module scans its
own source — it's a balanced pair, so it's harmless, but adding a second, unbalanced example
below it would break `main()` on this file. Keep any doc examples of the marker syntax balanced.)

(`// dup-ignore-start: ...` / `// dup-ignore-end` in frontend files — same convention, `#` vs
`//`.) The marker only counts when it's the line's actual leading comment (whitespace-stripped,
the line starts with `#`/`//` immediately followed by the marker) — mentioning it in prose, like
this paragraph does, or in a regex literal, doesn't accidentally register as a real marker. A
flagged cluster is suppressed only once *every* occurrence in it is wrapped — annotating some but
not all still fails, so there's no silent partial exemption. An unbalanced start/end pair is a
checker error, not a silent no-op.

Usage:
    python tools/check_duplicate_code.py

Always does a full-repo scan (PMD CPD compares files against each other, so there is no
meaningful per-changed-file mode). Needs Java 21+ on PATH — PMD CPD is a JVM tool. The first run
downloads a pinned PMD distribution (~50MB) to a shared cache (`~/.cache/hassette-dev-tools/pmd/`,
or `$XDG_CACHE_HOME/hassette-dev-tools/pmd/`) and verifies it against a pinned sha256; later runs
and other worktrees reuse the same cached copy.

Not yet wired into `prek.toml`, deliberately: at the current threshold this surfaces ~700
clusters against the existing codebase, which is exactly the point (an exhaustive backlog for a
review pass, not an already-clean baseline) but would fail every commit if it were a live gate
today. Wire in the prek hook once that backlog has been triaged down to `dup-ignore`d or fixed.
"""

import ast
import fnmatch
import functools
import hashlib
import itertools
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.request
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path
from typing import NamedTuple

from lint_helpers import REPO_ROOT, docstring_spans

PMD_VERSION = "7.26.0"
PMD_DIST_URL = f"https://github.com/pmd/pmd/releases/download/pmd_releases/{PMD_VERSION}/pmd-dist-{PMD_VERSION}-bin.zip"
PMD_DIST_SHA256 = "9f55cb7ff0e9f9a66dd2f005eaa370e84c8a4cd971b134aa14a930c4a283ebc9"
CPD_NS = {"cpd": "https://pmd-code.org/schema/cpd-report"}

PYTHON_SCAN_PATHS = ["src/hassette", "tests", "codegen", "tools", "scripts"]
TYPESCRIPT_SCAN_PATHS = ["frontend/src"]

MIN_LINES = 5
MIN_TOKENS = 20
MIN_OCCURRENCES = 3
MARKER_HEADER_LINES = 6

DOWNLOAD_TIMEOUT_SECONDS = 30
PMD_TIMEOUT_SECONDS = 300

IGNORE_START_RE = re.compile(r"^\s*(?:#|//)\s*dup-ignore-start:\s*(.*)$")
IGNORE_END_RE = re.compile(r"^\s*(?:#|//)\s*dup-ignore-end\b")

# Generated model directories with no per-file marker to detect programmatically — see
# CLAUDE.md (typed state models generated from HA core source for 34 entity domains).
CODEGEN_DIRS = [
    REPO_ROOT / "src/hassette/models/entities",
    REPO_ROOT / "src/hassette/models/states",
]

GENERATED_MARKER = "Do not edit this file directly"

IGNORE_GLOBS = [
    "**/generated-types.ts",
    "**/ws-types.ts",
    "**/*.d.ts",
    "**/*.generated.ts",
    # Verified snapshot, not hand-duplicated — drift is caught by tools/check_cli_drift.py.
    "**/tests/snapshots/**",
    # @font-face records: family/weight/url differ, boilerplate properties don't. Data, not logic.
    "**/frontend/src/styles/fonts.css",
]


class Fragment(NamedTuple):
    file: Path
    start: int
    end: int


def is_codegen_dir(path: Path) -> bool:
    return any(codegen_dir in path.parents for codegen_dir in CODEGEN_DIRS)


def is_generated_marker_file(path: Path) -> bool:
    """Return True if the file's opening lines carry the codegen "do not edit" banner."""
    try:
        head = path.read_text().splitlines()[:MARKER_HEADER_LINES]
    except (OSError, UnicodeDecodeError):
        return False
    return any(GENERATED_MARKER in line for line in head)


def is_excluded_file(path: Path) -> bool:
    return is_codegen_dir(path) or is_generated_marker_file(path)


def is_ignored_glob(path: Path) -> bool:
    if path.is_absolute():
        try:
            rel = path.relative_to(REPO_ROOT)
        except ValueError:
            rel = path
    else:
        rel = path
    # Leading "/" so a "**/…" pattern matches a path segment sitting at the root too — a bare
    # fnmatch("tests/snapshots/x", "**/tests/snapshots/**") fails because there's no "/" before
    # "tests" to match the "**/" against, even though the intent is clearly "anywhere".
    return any(fnmatch.fnmatch(f"/{rel}", pattern) for pattern in IGNORE_GLOBS)


@functools.cache
def docstring_and_import_lines(path: Path) -> frozenset[int]:
    """Return every 1-based line number that's part of a docstring or import statement in `path`.

    Python-only (a non-.py file, or one that fails to parse, exempts nothing). Content-based
    rather than position-based, so a fragment that happens to sit right after the imports —
    e.g. shared path-hacking setup — is never mistaken for the imports themselves.
    """
    if path.suffix != ".py":
        return frozenset()
    try:
        tree = ast.parse(path.read_text())
    except (OSError, UnicodeDecodeError, SyntaxError):
        return frozenset()

    lines: set[int] = set()
    for start, end in docstring_spans(tree):
        lines.update(range(start, end + 1))
    for node in ast.walk(tree):
        if isinstance(node, ast.Import | ast.ImportFrom):
            end = node.end_lineno or node.lineno
            lines.update(range(node.lineno, end + 1))
    return frozenset(lines)


def is_boilerplate(fragment: Fragment) -> bool:
    """Return True if every non-blank line in the fragment is a docstring or import line."""
    exempt_lines = docstring_and_import_lines(fragment.file)
    try:
        file_lines = fragment.file.read_text().splitlines()
    except (OSError, UnicodeDecodeError):
        return False

    non_blank = [lineno for lineno in range(fragment.start, fragment.end + 1) if file_lines[lineno - 1].strip()]
    if not non_blank:
        return True
    return all(lineno in exempt_lines for lineno in non_blank)


def is_too_short(fragment: Fragment) -> bool:
    return (fragment.end - fragment.start + 1) < MIN_LINES


class IgnoreMarkerError(Exception):
    """Raised for an unbalanced dup-ignore-start/dup-ignore-end pair — a malformed marker must
    fail the check loudly rather than silently suppress (or fail to suppress) a finding.
    """


@functools.cache
def ignore_ranges(path: Path) -> tuple[tuple[int, int], ...]:
    """Return every (start_line, end_line) range wrapped in a dup-ignore-start/end pair.

    Marker text is matched verbatim regardless of comment syntax (# vs //), so the same
    convention works across the Python and TypeScript/TSX files this checker scans.
    """
    try:
        lines = path.read_text().splitlines()
    except (OSError, UnicodeDecodeError):
        return ()

    ranges: list[tuple[int, int]] = []
    open_start: int | None = None
    for lineno, line in enumerate(lines, start=1):
        start_match = IGNORE_START_RE.search(line)
        if start_match:
            if open_start is not None:
                raise IgnoreMarkerError(f"{path}:{lineno}: nested dup-ignore-start (already open at line {open_start})")
            if not start_match.group(1).strip():
                raise IgnoreMarkerError(
                    f"{path}:{lineno}: dup-ignore-start requires a reason, e.g. 'dup-ignore-start: <reason>'"
                )
            open_start = lineno
        elif IGNORE_END_RE.search(line):
            if open_start is None:
                raise IgnoreMarkerError(f"{path}:{lineno}: dup-ignore-end with no matching dup-ignore-start")
            ranges.append((open_start, lineno))
            open_start = None
    if open_start is not None:
        raise IgnoreMarkerError(f"{path}:{open_start}: dup-ignore-start never closed with dup-ignore-end")
    return tuple(ranges)


def is_dup_ignored(fragment: Fragment) -> bool:
    """Return True if the fragment sits fully inside a dup-ignore-start/end range in its file."""
    return any(start <= fragment.start and fragment.end <= end for start, end in ignore_ranges(fragment.file))


def pmd_cache_root() -> Path:
    base = Path(os.environ["XDG_CACHE_HOME"]) if os.environ.get("XDG_CACHE_HOME") else Path.home() / ".cache"
    return base / "hassette-dev-tools" / "pmd" / PMD_VERSION


def ensure_pmd_binary() -> Path:
    """Return a cached `pmd` executable, downloading and verifying it on first run.

    Shared across worktrees (keyed by PMD_VERSION under a user-level cache dir, not a repo-local
    one) so N parallel worktrees don't each pull their own ~50MB copy.
    """
    if shutil.which("java") is None:
        raise RuntimeError(
            "check_duplicate_code.py needs Java 21+ on PATH to run PMD CPD (the clone detector). "
            "Install it (e.g. `mise install java`) and retry."
        )

    install_dir = pmd_cache_root()
    binary = install_dir / f"pmd-bin-{PMD_VERSION}" / "bin" / "pmd"
    if binary.exists():
        return binary

    install_dir.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(suffix=".zip")
    os.close(fd)
    tmp_path = Path(tmp_name)
    try:
        with urllib.request.urlopen(PMD_DIST_URL, timeout=DOWNLOAD_TIMEOUT_SECONDS) as response:  # noqa: S310 -- trusted, pinned GitHub release URL
            tmp_path.write_bytes(response.read())
        digest = hashlib.sha256(tmp_path.read_bytes()).hexdigest()
        if digest != PMD_DIST_SHA256:
            raise RuntimeError(f"PMD download checksum mismatch: expected {PMD_DIST_SHA256}, got {digest}")
        with zipfile.ZipFile(tmp_path) as zf:
            zf.extractall(install_dir)
    finally:
        tmp_path.unlink(missing_ok=True)

    mode = binary.stat().st_mode
    binary.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return binary


def run_pmd_cpd(pmd_binary: Path, language: str, scan_paths: list[str]) -> ET.Element:
    cmd = [
        str(pmd_binary),
        "cpd",
        "--dir",
        ",".join(scan_paths),
        "--language",
        language,
        "--minimum-tokens",
        str(MIN_TOKENS),
        "--format",
        "xml",
        "--no-fail-on-violation",
    ]
    try:
        result = subprocess.run(
            cmd, cwd=REPO_ROOT, check=True, capture_output=True, text=True, timeout=PMD_TIMEOUT_SECONDS
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(
            f"PMD CPD didn't finish scanning {language} within {PMD_TIMEOUT_SECONDS}s — "
            "check for a pathological file in scope or raise PMD_TIMEOUT_SECONDS."
        ) from exc
    return ET.fromstring(result.stdout)  # noqa: S314 -- trusted local PMD output, not untrusted input


def fragment_from_file_element(element: ET.Element) -> Fragment:
    path, line, endline = element.get("path"), element.get("line"), element.get("endline")
    if path is None or line is None or endline is None:
        raise ValueError(f"PMD CPD file element missing path/line/endline: {ET.tostring(element, encoding='unicode')}")
    return Fragment(Path(path), int(line), int(endline))


def duplication_blocks(root: ET.Element) -> list[list[Fragment]]:
    blocks: list[list[Fragment]] = []
    for dup in root.findall("cpd:duplication", CPD_NS):
        fragments = [fragment_from_file_element(f) for f in dup.findall("cpd:file", CPD_NS)]
        blocks.append(fragments)
    return blocks


def build_edges(blocks: list[list[Fragment]]) -> list[tuple[Fragment, Fragment]]:
    edges: list[tuple[Fragment, Fragment]] = []
    for fragments in blocks:
        kept = [fragment for fragment in fragments if not is_dropped(fragment)]
        # Only consecutive pairs need an edge — cluster()'s union-find still connects a
        # whole N-way duplication block into one component via transitivity.
        edges.extend(itertools.pairwise(kept))
    return edges


def is_dropped(fragment: Fragment) -> bool:
    return (
        is_excluded_file(fragment.file)
        or is_boilerplate(fragment)
        or is_ignored_glob(fragment.file)
        or is_too_short(fragment)
    )


def cluster(edges: list[tuple[Fragment, Fragment]]) -> list[list[Fragment]]:
    """Union-find over the clone graph — connects every fragment PMD says duplicates another."""
    parent: dict[Fragment, Fragment] = {}

    def find(node: Fragment) -> Fragment:
        parent.setdefault(node, node)
        while parent[node] != node:
            parent[node] = parent[parent[node]]
            node = parent[node]
        return node

    def union(a: Fragment, b: Fragment) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for a, b in edges:
        union(a, b)

    components: dict[Fragment, list[Fragment]] = {}
    for node in parent:
        components.setdefault(find(node), []).append(node)
    return list(components.values())


def format_violation(component: list[Fragment]) -> str:
    lines = [
        f"    {fragment.file.relative_to(REPO_ROOT)}:{fragment.start}-{fragment.end}" for fragment in sorted(component)
    ]
    return "\n".join(lines)


def find_violations(blocks: list[list[Fragment]]) -> list[list[Fragment]]:
    edges = build_edges(blocks)
    components = cluster(edges)
    candidates = [component for component in components if len(component) >= MIN_OCCURRENCES]
    # A component is suppressed only once every fragment is dup-ignored — keep it as a
    # violation if at least one fragment still isn't.
    return [component for component in candidates if any(not is_dup_ignored(fragment) for fragment in component)]


def main() -> int:
    pmd_binary = ensure_pmd_binary()
    blocks = duplication_blocks(run_pmd_cpd(pmd_binary, "python", PYTHON_SCAN_PATHS))
    blocks += duplication_blocks(run_pmd_cpd(pmd_binary, "typescript", TYPESCRIPT_SCAN_PATHS))

    try:
        violations = find_violations(blocks)
    except IgnoreMarkerError as exc:
        print(f"ERROR: malformed dup-ignore marker: {exc}")
        return 1

    if violations:
        print(f"ERROR: {len(violations)} code block(s) copy-pasted {MIN_OCCURRENCES}+ times:")
        print()
        for component in violations:
            print(format_violation(component))
            print()
        print(
            "Extract the shared block into a fixture, helper, or shared module. If this specific\n"
            "duplication is intentional, wrap every occurrence: '# dup-ignore-start: <reason>' /\n"
            "'# dup-ignore-end' (reason required)."
        )
        return 1

    print(f"OK: no code block copy-pasted {MIN_OCCURRENCES}+ times.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
