#!/usr/bin/env python3
"""CI guard: flag a code block copy-pasted 3+ times, in one file or across many.

This exists because the failure mode it catches keeps recurring by hand: someone adds a new
sibling file (a new `tools/check_*.py` test, a new CLI subcommand, a new page component) — or a
new case in an existing file — by copying an existing block, and the third or fourth copy is the
one nobody notices until a clean-code sweep finds it. PMD CPD (https://pmd.github.io/pmd/pmd_userdocs_cpd.html)
does the raw clone detection; this script narrows its output to the shape that's actually worth a
human look.

PMD CPD, not jscpd: jscpd's Python/TypeScript tokenizers compare literal values and identifier
names exactly, so a block repeated 8 times with different assertion values or variable names only
shows up as scattered 2-3-occurrence pairs in its clone graph — undercounting real duplication.
PMD CPD's default tokenizer for these two languages already treats differing literals and
differing identifier names as equivalent when matching (verified empirically — PMD's own
`--ignore-literals`/`--ignore-identifiers` flags are no-ops here because the default already does
this), which is what actually fixes the undercounting. `MIN_TOKENS` is intentionally lower than a
naive port of jscpd's threshold would suggest — the same-shape matches between any two given
occurrences are shorter once literal/identifier noise no longer breaks them, and a higher
threshold silently drops real findings before they ever reach the clustering step below.

Two occurrences of a block is common in this codebase *by design* — a sync facade mirrors its
async source, two CLI subcommands for parallel resource types share structure, two Resource
subclasses share lifecycle plumbing. Requiring 3+ occurrences (via connected-component
clustering over PMD's pairwise clone graph — see `cluster()`) turns out to cleanly separate
"designed parallel structure" (stays a pair) from "this should have been extracted" (spreads as
more copies get added), without a threshold this loose flagging every legitimate pair.

Two categories are excluded automatically, before clustering, because they're mechanically
unambiguous and never need a human judgment call:
  - Files whose module docstring says "Do not edit this file directly" — the marker every
    codegen'd sync-facade file in this repo carries (see codegen/src/hassette_codegen/), plus
    the two codegen'd model directories that don't carry that marker (generated from HA core
    source; see CLAUDE.md's Architecture section). A human didn't choose to duplicate this.
  - Fragments whose every non-blank line is part of a module docstring or an `import`/`from
    ... import` statement — content that necessarily repeats across sibling files without being
    copy-paste debt. Checked by content (via `ast`), not by position — a fragment right after
    the imports (e.g. shared path-hacking setup) is real logic and stays in scope. Python-only:
    a TypeScript/TSX import block is never exempted by this check.

Everything else surfaces by default, including patterns this codebase has hand-decided to keep
(e.g. the "Shape B delegate" convenience-method convention in bus.py/scheduler.py). For those,
wrap the accepted occurrence in a marker pair — mirrors this repo's `# factory-local: <reason>`
convention, but as a start/end pair since a duplicate block spans multiple lines and pinning a
single marker to one line would mean guessing which line it governs. This is the "expected
duplication" escape hatch — the mechanism for a human to say "yes, I saw this, it's fine":

    # dup-ignore-start: <reason>
    ...block...
    # dup-ignore-end

(This example is itself live input to the parser it's documenting, since this module scans its
own source — it's a balanced pair, so it's harmless, but adding a second, unbalanced example
below it would break `main()` on this file. Keep any doc examples of the marker syntax balanced.)

For files where the *entire* file is intentional duplication (e.g. HA helper models whose
Create/Update/State param classes share fields by API design), a single file-level marker
excludes every fragment from that file without wrapping individual blocks:

    # dup-ignore-file: <reason>

(`// dup-ignore-file: ...` in frontend files.) Same comment-syntax convention as the range
markers. Place it once anywhere in the file (usually near the top); the reason is required.

(`// dup-ignore-start: ...` / `// dup-ignore-end` in frontend files — same convention, `#` vs
`//`.) The marker only counts when it's the line's actual leading comment (whitespace-stripped,
the line starts with `#`/`//` immediately followed by the marker) — mentioning it in prose, like
this paragraph does, or in a regex literal, doesn't accidentally register as a real marker. A
flagged cluster is suppressed only once *every* occurrence in it is wrapped — annotating some but
not all still fails, so there's no silent partial exemption. An unbalanced start/end pair is a
checker error, not a silent no-op — and that guarantee holds for every scanned file, not just
ones PMD happened to flag as duplicated: `main()` parses every marker in every scanned file
(`validate_markers()`) before clustering even starts, so a malformed marker sitting on code PMD
never reports as a clone can't sit there silently until unrelated duplication changes the cluster
and finally exercises it.

Usage:
    python tools/check_duplicate_code.py
    python tools/check_duplicate_code.py --gate-new-code <base-ref> <head-ref>

Always does a full-repo scan (PMD CPD compares files against each other, so there is no
meaningful per-changed-file mode). `--gate-new-code` scans the head tree, and — only when that
scan finds at least one violation — also scans a throwaway extraction of the PR's merge-base
tree (`scan_tree_at_ref()`), then reports only the head clusters that don't already match a
merge-base cluster (see `new_code_violations()`), leaving untouched pre-existing debt unreported.
Needs Java 21+ on PATH — PMD CPD is a JVM tool. The first run downloads a pinned PMD distribution
(~50MB) to a shared cache (`~/.cache/hassette-dev-tools/pmd/`, or
`$XDG_CACHE_HOME/hassette-dev-tools/pmd/`) and verifies it against a pinned sha256; later runs and
other worktrees reuse the same cached copy.

Wired into CI (`.github/workflows/lint.yml`) twice: a non-blocking step (`continue-on-error:
true`) that reports the full backlog, and a blocking `--gate-new-code` step (no
`continue-on-error`) that fails only when the current PR's own diff introduces a new violation.
The full-backlog step means the ~226-item backlog (#1559-#1570) never needs to hit zero for the
gate to matter — it only needs each PR to not add to it.
"""

import ast
import fnmatch
import functools
import hashlib
import itertools
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.request
import xml.etree.ElementTree as ET
import zipfile
from collections import Counter
from pathlib import Path
from typing import NamedTuple

from lint_helpers import (
    REPO_ROOT,
    docstring_spans,
    git_merge_base,
    git_renamed_from,
    iter_py_files,
    iter_ts_files,
)

PMD_VERSION = "7.26.0"
PMD_DIST_URL = f"https://github.com/pmd/pmd/releases/download/pmd_releases/{PMD_VERSION}/pmd-dist-{PMD_VERSION}-bin.zip"
PMD_DIST_SHA256 = "9f55cb7ff0e9f9a66dd2f005eaa370e84c8a4cd971b134aa14a930c4a283ebc9"
CPD_NS = {"cpd": "https://pmd-code.org/schema/cpd-report"}

PYTHON_SCAN_PATHS = ["src/hassette", "tests", "codegen", "tools", "scripts"]
TYPESCRIPT_SCAN_PATHS = ["frontend/src"]

MIN_LINES = 5
MIN_TOKENS = 20
MIN_OCCURRENCES = 3
MARKER_HEADER_LINES = 6

DOWNLOAD_TIMEOUT_SECONDS = 30
PMD_TIMEOUT_SECONDS = 300

IGNORE_START_RE = re.compile(r"^\s*(?:#|//)\s*dup-ignore-start:\s*(.*)$")
IGNORE_END_RE = re.compile(r"^\s*(?:#|//)\s*dup-ignore-end\b")
IGNORE_FILE_RE = re.compile(r"^\s*(?:#|//)\s*dup-ignore-file:\s*(.*)$")

# Generated model directories with no per-file marker to detect programmatically — see
# CLAUDE.md (typed state models generated from HA core source for 34 entity domains). Repo-root-
# relative, not absolute: --gate-new-code scans a second, throwaway checkout of the PR's
# merge-base tree (see scan_tree_at_ref()) under its own temp-directory root, so these need to
# resolve against whichever root is currently being scanned, not always the real REPO_ROOT.
CODEGEN_DIRS = [
    Path("src/hassette/models/entities"),
    Path("src/hassette/models/states"),
]

GENERATED_MARKER = "Do not edit this file directly"

IGNORE_GLOBS = [
    "**/generated-types.ts",
    "**/ws-types.ts",
    "**/*.d.ts",
    "**/*.generated.ts",
    # Verified snapshot, not hand-duplicated — drift is caught by tools/check_cli_drift.py.
    "**/tests/snapshots/**",
    # @font-face records: family/weight/url differ, boilerplate properties don't. Data, not logic.
    "**/frontend/src/styles/fonts.css",
]

# Repo-root-relative for the same reason CODEGEN_DIRS is — see that constant's comment.
_SELF_RELATIVE = Path("tools/check_duplicate_code.py")


class Fragment(NamedTuple):
    file: Path
    start: int
    end: int


def is_self(path: Path, repo_root: Path) -> bool:
    try:
        return path.resolve().relative_to(repo_root.resolve()) == _SELF_RELATIVE
    except ValueError:
        return False


def is_codegen_dir(path: Path, repo_root: Path) -> bool:
    try:
        rel = path.resolve().relative_to(repo_root.resolve())
    except ValueError:
        return False
    return any(codegen_dir in rel.parents for codegen_dir in CODEGEN_DIRS)


def is_generated_marker_file(path: Path) -> bool:
    """Return True if the file's opening lines carry the codegen "do not edit" banner."""
    try:
        head = path.read_text().splitlines()[:MARKER_HEADER_LINES]
    except (OSError, UnicodeDecodeError):
        return False
    return any(GENERATED_MARKER in line for line in head)


class IgnoreMarkerError(Exception):
    """Raised for a malformed dup-ignore marker — must fail loudly, not silently suppress."""


@functools.cache
def is_dup_ignore_file(path: Path, repo_root: Path) -> bool:
    """Return True if the file carries a ``dup-ignore-file: <reason>`` marker anywhere."""
    if is_self(path, repo_root):
        return False
    try:
        text = path.read_text()
    except (OSError, UnicodeDecodeError):
        return False
    for line in text.splitlines():
        m = IGNORE_FILE_RE.search(line)
        if m:
            if not m.group(1).strip():
                raise IgnoreMarkerError(f"{path}: dup-ignore-file requires a reason, e.g. 'dup-ignore-file: <reason>'")
            return True
    return False


def is_excluded_file(path: Path, repo_root: Path) -> bool:
    if is_self(path, repo_root):
        return True
    return is_codegen_dir(path, repo_root) or is_generated_marker_file(path)


def is_ignored_glob(path: Path, repo_root: Path) -> bool:
    if path.is_absolute():
        try:
            rel = path.relative_to(repo_root)
        except ValueError:
            rel = path
    else:
        rel = path
    # Leading "/" so a "**/…" pattern matches a path segment sitting at the root too — a bare
    # fnmatch("tests/snapshots/x", "**/tests/snapshots/**") fails because there's no "/" before
    # "tests" to match the "**/" against, even though the intent is clearly "anywhere".
    return any(fnmatch.fnmatch(f"/{rel}", pattern) for pattern in IGNORE_GLOBS)


@functools.cache
def docstring_and_import_lines(path: Path) -> frozenset[int]:
    """Return every 1-based line number that's part of a docstring or import statement in `path`.

    Python-only (a non-.py file, or one that fails to parse, exempts nothing). Content-based
    rather than position-based, so a fragment that happens to sit right after the imports —
    e.g. shared path-hacking setup — is never mistaken for the imports themselves.
    """
    if path.suffix != ".py":
        return frozenset()
    try:
        tree = ast.parse(path.read_text())
    except (OSError, UnicodeDecodeError, SyntaxError):
        return frozenset()

    lines: set[int] = set()
    for start, end in docstring_spans(tree):
        lines.update(range(start, end + 1))
    for node in ast.walk(tree):
        if isinstance(node, ast.Import | ast.ImportFrom):
            end = node.end_lineno or node.lineno
            lines.update(range(node.lineno, end + 1))
    return frozenset(lines)


def is_boilerplate(fragment: Fragment) -> bool:
    """Return True if every non-blank line in the fragment is a docstring or import line."""
    exempt_lines = docstring_and_import_lines(fragment.file)
    try:
        file_lines = fragment.file.read_text().splitlines()
    except (OSError, UnicodeDecodeError):
        return False

    non_blank = [lineno for lineno in range(fragment.start, fragment.end + 1) if file_lines[lineno - 1].strip()]
    if not non_blank:
        return True
    return all(lineno in exempt_lines for lineno in non_blank)


def is_too_short(fragment: Fragment) -> bool:
    return (fragment.end - fragment.start + 1) < MIN_LINES


@functools.cache
def ignore_ranges(path: Path) -> tuple[tuple[int, int], ...]:
    """Return every (start_line, end_line) range wrapped in a dup-ignore-start/end pair.

    Marker text is matched verbatim regardless of comment syntax (# vs //), so the same
    convention works across the Python and TypeScript/TSX files this checker scans.
    """
    try:
        lines = path.read_text().splitlines()
    except (OSError, UnicodeDecodeError):
        return ()

    ranges: list[tuple[int, int]] = []
    open_start: int | None = None
    for lineno, line in enumerate(lines, start=1):
        start_match = IGNORE_START_RE.search(line)
        if start_match:
            if open_start is not None:
                raise IgnoreMarkerError(f"{path}:{lineno}: nested dup-ignore-start (already open at line {open_start})")
            if not start_match.group(1).strip():
                raise IgnoreMarkerError(
                    f"{path}:{lineno}: dup-ignore-start requires a reason, e.g. 'dup-ignore-start: <reason>'"
                )
            open_start = lineno
        elif IGNORE_END_RE.search(line):
            if open_start is None:
                raise IgnoreMarkerError(f"{path}:{lineno}: dup-ignore-end with no matching dup-ignore-start")
            ranges.append((open_start, lineno))
            open_start = None
    if open_start is not None:
        raise IgnoreMarkerError(f"{path}:{open_start}: dup-ignore-start never closed with dup-ignore-end")
    return tuple(ranges)


def is_dup_ignored(fragment: Fragment) -> bool:
    """Return True if the fragment sits fully inside a dup-ignore-start/end range in its file."""
    return any(start <= fragment.start and fragment.end <= end for start, end in ignore_ranges(fragment.file))


def scanned_files(repo_root: Path) -> list[Path]:
    """Every file PMD CPD is asked to scan, across both languages, under `repo_root`.

    Walks PYTHON_SCAN_PATHS/TYPESCRIPT_SCAN_PATHS the same directories passed to `run_pmd_cpd`,
    via the same first-party-file filtering `iter_py_files`/`iter_ts_files` use elsewhere in this
    tools/ package — a best-effort mirror of PMD's own `--dir` scan, not a verified-identical one
    (PMD's file discovery is opaque to this script; the two could in principle diverge on an edge
    case like a symlink).
    """
    ts_files = [path for scan_dir in TYPESCRIPT_SCAN_PATHS for path in iter_ts_files(repo_root / scan_dir)]
    return iter_py_files(repo_root, PYTHON_SCAN_PATHS) + sorted(ts_files)


def validate_markers(files: list[Path], repo_root: Path) -> None:
    """Eagerly parse every dup-ignore marker in `files`, raising on the first malformed one.

    `is_dup_ignore_file`/`ignore_ranges` already raise `IgnoreMarkerError` for a malformed marker,
    but `find_violations` only calls them on fragments PMD found duplicated 3+ times. A malformed
    marker on code that PMD never flags as a clone — because the block genuinely appears only once
    or twice, or the fragment predates the marker going stale — would otherwise pass silently.
    Calling both eagerly here, over every scanned file, closes that gap; both are `functools.cache`d
    so the later calls during clustering are free.

    Skips exactly the files `is_dropped` treats as out-of-scope before it ever reaches a marker
    check (`is_ignored_glob`, `is_excluded_file` — self, codegen dirs, generated-marker files) —
    those files' duplication is never evaluated, so a marker sitting in one, malformed or not, is
    never load-bearing and shouldn't fail CI on its own.
    """
    for path in files:
        if is_ignored_glob(path, repo_root) or is_excluded_file(path, repo_root):
            continue
        is_dup_ignore_file(path, repo_root)
        ignore_ranges(path)


def pmd_cache_root() -> Path:
    base = Path(os.environ["XDG_CACHE_HOME"]) if os.environ.get("XDG_CACHE_HOME") else Path.home() / ".cache"
    return base / "hassette-dev-tools" / "pmd" / PMD_VERSION


def ensure_pmd_binary() -> Path:
    """Return a cached `pmd` executable, downloading and verifying it on first run.

    Shared across worktrees (keyed by PMD_VERSION under a user-level cache dir, not a repo-local
    one) so N parallel worktrees don't each pull their own ~50MB copy.
    """
    if shutil.which("java") is None:
        raise RuntimeError(
            "check_duplicate_code.py needs Java 21+ on PATH to run PMD CPD (the clone detector). "
            "Install it (e.g. `mise install java`) and retry."
        )

    install_dir = pmd_cache_root()
    binary = install_dir / f"pmd-bin-{PMD_VERSION}" / "bin" / "pmd"
    if binary.exists():
        return binary

    install_dir.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(suffix=".zip")
    os.close(fd)
    tmp_path = Path(tmp_name)
    try:
        with urllib.request.urlopen(PMD_DIST_URL, timeout=DOWNLOAD_TIMEOUT_SECONDS) as response:  # noqa: S310 -- trusted, pinned GitHub release URL
            tmp_path.write_bytes(response.read())
        digest = hashlib.sha256(tmp_path.read_bytes()).hexdigest()
        if digest != PMD_DIST_SHA256:
            raise RuntimeError(f"PMD download checksum mismatch: expected {PMD_DIST_SHA256}, got {digest}")
        with zipfile.ZipFile(tmp_path) as zf:
            zf.extractall(install_dir)
    finally:
        tmp_path.unlink(missing_ok=True)

    mode = binary.stat().st_mode
    binary.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return binary


def run_pmd_cpd(pmd_binary: Path, language: str, scan_paths: list[str], repo_root: Path) -> ET.Element:
    cmd = [
        str(pmd_binary),
        "cpd",
        "--dir",
        ",".join(scan_paths),
        "--language",
        language,
        "--minimum-tokens",
        str(MIN_TOKENS),
        "--format",
        "xml",
        "--no-fail-on-violation",
    ]
    try:
        result = subprocess.run(
            cmd, cwd=repo_root, check=True, capture_output=True, text=True, timeout=PMD_TIMEOUT_SECONDS
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(
            f"PMD CPD didn't finish scanning {language} within {PMD_TIMEOUT_SECONDS}s — "
            "check for a pathological file in scope or raise PMD_TIMEOUT_SECONDS."
        ) from exc
    return ET.fromstring(result.stdout)  # noqa: S314 -- trusted local PMD output, not untrusted input


def fragment_from_file_element(element: ET.Element) -> Fragment:
    path, line, endline = element.get("path"), element.get("line"), element.get("endline")
    if path is None or line is None or endline is None:
        raise ValueError(f"PMD CPD file element missing path/line/endline: {ET.tostring(element, encoding='unicode')}")
    return Fragment(Path(path), int(line), int(endline))


def duplication_blocks(root: ET.Element) -> list[list[Fragment]]:
    blocks: list[list[Fragment]] = []
    for dup in root.findall("cpd:duplication", CPD_NS):
        fragments = [fragment_from_file_element(f) for f in dup.findall("cpd:file", CPD_NS)]
        blocks.append(fragments)
    return blocks


def build_edges(blocks: list[list[Fragment]], repo_root: Path) -> list[tuple[Fragment, Fragment]]:
    edges: list[tuple[Fragment, Fragment]] = []
    for fragments in blocks:
        kept = [fragment for fragment in fragments if not is_dropped(fragment, repo_root)]
        # Only consecutive pairs need an edge — cluster()'s union-find still connects a
        # whole N-way duplication block into one component via transitivity.
        edges.extend(itertools.pairwise(kept))
    return edges


def is_dropped(fragment: Fragment, repo_root: Path) -> bool:
    return (
        is_excluded_file(fragment.file, repo_root)
        or is_dup_ignore_file(fragment.file, repo_root)
        or is_boilerplate(fragment)
        or is_ignored_glob(fragment.file, repo_root)
        or is_too_short(fragment)
    )


def cluster(edges: list[tuple[Fragment, Fragment]]) -> list[list[Fragment]]:
    """Union-find over the clone graph — connects every fragment PMD says duplicates another."""
    parent: dict[Fragment, Fragment] = {}

    def find(node: Fragment) -> Fragment:
        parent.setdefault(node, node)
        while parent[node] != node:
            parent[node] = parent[parent[node]]
            node = parent[node]
        return node

    def union(a: Fragment, b: Fragment) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for a, b in edges:
        union(a, b)

    components: dict[Fragment, list[Fragment]] = {}
    for node in parent:
        components.setdefault(find(node), []).append(node)
    return list(components.values())


def format_violation(component: list[Fragment]) -> str:
    """Format one violation for display -- always against the real REPO_ROOT, never the throwaway
    merge-base extraction (`scan_tree_at_ref()` returns per-cluster counts, not `Fragment`s, for
    exactly this reason: nothing here ever needs to format a base-tree fragment for a user).
    """
    lines = [
        f"    {fragment.file.relative_to(REPO_ROOT)}:{fragment.start}-{fragment.end}" for fragment in sorted(component)
    ]
    return "\n".join(lines)


def find_violations(blocks: list[list[Fragment]], repo_root: Path) -> list[list[Fragment]]:
    edges = build_edges(blocks, repo_root)
    components = cluster(edges)
    candidates = [component for component in components if len(component) >= MIN_OCCURRENCES]
    # A component is suppressed only once every fragment is dup-ignored — keep it as a
    # violation if at least one fragment still isn't.
    return [component for component in candidates if any(not is_dup_ignored(fragment) for fragment in component)]


def cluster_file_counts(
    component: list[Fragment], repo_root: Path, renames: dict[Path, Path] | None = None
) -> Counter[Path]:
    """Return {repo-relative file path: fragment count in this cluster} for one violation.

    `renames` (only meaningful for a head-tree cluster) maps a head-relative path to its
    merge-base-relative path, so a cluster's identity survives a plain rename between the two
    scans being compared — see `new_code_violations()`.
    """
    counts: Counter[Path] = Counter()
    for fragment in component:
        rel = fragment.file.relative_to(repo_root)
        if renames is not None:
            rel = renames.get(rel, rel)
        counts[rel] += 1
    return counts


def new_code_violations(
    head_violations: list[list[Fragment]],
    base_cluster_counts: list[Counter[Path]],
    renames: dict[Path, Path],
    repo_root: Path,
) -> list[list[Fragment]]:
    """Return the subset of `head_violations` this PR's own diff is responsible for.

    Earlier versions of this gate inferred "is this cluster new" from how much of a fragment's
    *lines* the PR's diff touched — a proxy that both false-positived (reformatting an existing
    occurrence rewrites most of its lines without changing what it duplicates) and false-
    negatived (a single-line edit can turn a previously-unrelated pair into a brand-new 3-way
    match, at near-zero line overlap). This compares actual violation sets instead: a head
    cluster is pre-existing only if some single merge-base cluster already contained every one
    of its (file, occurrence-count) pairs — comparing *counts*, not just file identity, so
    adding a new copy to a file that already contributed multiple fragments to an existing
    cluster (e.g. scheduler.py's several same-file convenience-method duplicates) still counts
    as new debt rather than being masked by the file's pre-existing membership. A cluster
    lacking a fully-covering base match is reported as PR-introduced, whether that's because it
    gained a member (an extra occurrence added to existing debt) or never existed at all (a
    wholly new match, however small the edit that created it).
    """
    introduced = []
    for component in head_violations:
        head_counts = cluster_file_counts(component, repo_root, renames)
        pre_existing = any(
            all(count <= base_counts.get(path, 0) for path, count in head_counts.items())
            for base_counts in base_cluster_counts
        )
        if not pre_existing:
            introduced.append(component)
    return introduced


def run_scan(repo_root: Path) -> list[list[Fragment]]:
    """Run the full PMD CPD scan against `repo_root` and return every violation there.

    Full-repo, no diff scoping — `repo_root` is either the real checkout (the plain-mode and
    backlog-reporting case) or a throwaway extraction of the PR's merge-base tree (see
    `scan_tree_at_ref()`, used by `--gate-new-code`).
    """
    validate_markers(scanned_files(repo_root), repo_root)
    pmd_binary = ensure_pmd_binary()
    blocks = duplication_blocks(run_pmd_cpd(pmd_binary, "python", PYTHON_SCAN_PATHS, repo_root))
    blocks += duplication_blocks(run_pmd_cpd(pmd_binary, "typescript", TYPESCRIPT_SCAN_PATHS, repo_root))
    return find_violations(blocks, repo_root)


def scan_tree_at_ref(ref: str) -> list[Counter[Path]]:
    """Materialize `ref`'s tree into a throwaway directory, scan it, and return each violation
    cluster's per-file fragment counts (see `cluster_file_counts()`).

    Used to compute the PR's merge-base violation "shape" for `--gate-new-code`: `new_code_
    violations()` only needs to know, per cluster, which files contributed how many fragments —
    not the fragments' exact text or line ranges — so returning counts here (rather than raw
    `Fragment`s tied to a temp directory that's about to be deleted) keeps the caller from ever
    needing to know this function's throwaway root path.

    Reads module-level `REPO_ROOT` directly, unlike every other function in this file's
    `repo_root`-threading chain: `git archive` needs a real git repository as its *source*, which
    is always the actual checkout regardless of which tree is being scanned -- only the
    *destination* (the temp directory) varies, and that's the `repo_root` this function hands to
    `run_scan()`.
    """
    with tempfile.TemporaryDirectory(prefix="check-duplicate-code-base-") as tmp_name:
        tmp_root = Path(tmp_name)
        try:
            archive = subprocess.run(["git", "archive", ref], cwd=REPO_ROOT, capture_output=True, check=True)
            subprocess.run(["tar", "-x"], cwd=tmp_root, input=archive.stdout, check=True)
        except subprocess.CalledProcessError as exc:
            raise RuntimeError(
                f"couldn't materialize {ref}'s tree for the merge-base scan "
                f"({exc.cmd} exited {exc.returncode}): {exc.stderr!r}"
            ) from exc
        violations = run_scan(tmp_root)
        return [cluster_file_counts(component, tmp_root) for component in violations]


def report_full_backlog(violations: list[list[Fragment]]) -> int:
    if violations:
        print(f"ERROR: {len(violations)} code block(s) copy-pasted {MIN_OCCURRENCES}+ times:")
        print()
        for component in violations:
            print(format_violation(component))
            print()
        print(
            "Extract the shared block into a fixture, helper, or shared module. If this specific\n"
            "duplication is intentional, wrap every occurrence: '# dup-ignore-start: <reason>' /\n"
            "'# dup-ignore-end' (reason required)."
        )
        return 1

    print(f"OK: no code block copy-pasted {MIN_OCCURRENCES}+ times.")
    return 0


def report_new_code_gate(introduced: list[list[Fragment]]) -> int:
    """Report the clusters `new_code_violations()` determined this PR is responsible for."""
    if introduced:
        print(f"ERROR: this PR introduces {len(introduced)} code block(s) copy-pasted {MIN_OCCURRENCES}+ times:")
        print()
        for component in introduced:
            print(format_violation(component))
            print()
        print(
            "This exact combination of occurrences didn't exist as a match at this PR's merge-\n"
            "base. Extract the shared block into a fixture, helper, or shared module, or wrap\n"
            "every occurrence with '# dup-ignore-start: <reason>' / '# dup-ignore-end' if this\n"
            "duplication is intentional. Pre-existing duplication this PR didn't touch isn't\n"
            "blocked here — see the informational 'duplicate-code' job for the full backlog."
        )
        return 1

    print(f"OK: this PR introduces no new {MIN_OCCURRENCES}+-way duplicate code blocks.")
    return 0


def parse_gate_refs(argv: list[str]) -> tuple[str, str] | None:
    """Parse `[--gate-new-code <base-ref> <head-ref>]` from CLI args, or None for plain mode.

    Raises ValueError with a usage message on anything else — `main()` turns that into the
    process's stderr + exit code 2.
    """
    if not argv:
        return None
    if len(argv) == 3 and argv[0] == "--gate-new-code":
        return (argv[1], argv[2])
    raise ValueError("Usage: check_duplicate_code.py [--gate-new-code <base-ref> <head-ref>]")


def main() -> int:
    try:
        gate_refs = parse_gate_refs(sys.argv[1:])
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 2

    try:
        head_violations = run_scan(REPO_ROOT)
    except IgnoreMarkerError as exc:
        print(f"ERROR: malformed dup-ignore marker: {exc}")
        return 1

    if gate_refs is None:
        return report_full_backlog(head_violations)

    # Two reports from one head-tree scan: the backlog is printed for context but never
    # determines this call's exit code — only the new-code gate below does.
    print("--- Existing backlog (informational; does not affect this check's pass/fail) ---")
    _ = report_full_backlog(head_violations)  # return value intentionally unused, see comment above
    print()
    print("--- This PR's new duplicate code (this determines pass/fail) ---")

    base_ref, head_ref = gate_refs
    if not head_violations:
        # Nothing to disambiguate against a merge-base scan -- skip that second PMD invocation.
        return report_new_code_gate([])

    merge_base = git_merge_base(REPO_ROOT, base_ref, head_ref)
    renames = git_renamed_from(REPO_ROOT, merge_base, head_ref)
    try:
        base_cluster_counts = scan_tree_at_ref(merge_base)
    except IgnoreMarkerError as exc:
        print(f"ERROR: malformed dup-ignore marker in merge-base tree ({merge_base}): {exc}")
        return 1
    introduced = new_code_violations(head_violations, base_cluster_counts, renames, REPO_ROOT)
    return report_new_code_gate(introduced)


if __name__ == "__main__":
    sys.exit(main())
