#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
import argparse
import ast
import builtins
import contextlib
import copy
import itertools
import py_compile
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# Stub message templates — defined as module-level constants so generated code
# and generator share the same strings. The generated file re-emits these
# verbatim so downstream imports work without sys.path tricks.
# ---------------------------------------------------------------------------
_STUB_MSG_STATE_CONVERSION = (
    "RecordingApi.sync.{name} is not implemented on the test facade. "
    "Call `harness.api_recorder.sync.get_state(entity_id)` and read the returned state directly."
)
_STUB_MSG_GENERIC = (
    "RecordingApi.sync.{name} is not implemented. "
    "Seed state via AppTestHarness.set_state() for read methods, "
    "or use a full integration test for methods requiring a live HA connection."
)
_STATE_CONVERSION_METHODS = frozenset({"get_state_value", "get_state_value_typed", "get_attribute"})

# Module-level sets for filtering body-referenced Name nodes during import derivation.
# Use the `builtins` module directly rather than `__builtins__`, which is a dict when
# this file is imported as a module (e.g., under pytest) and returns dict methods instead
# of the 159 actual Python builtins.
_BUILTIN_NAMES: frozenset[str] = frozenset(dir(builtins))
_WELL_KNOWN_NAMES: frozenset[str] = frozenset(
    {"self", "None", "True", "False", "NotImplementedError", "RuntimeError", "TypeError"}
)


HEADER = '''"""Auto-generated synchronous facade for `Api`.

Do not edit this file directly.

It is generated from `api.Api` by `tools/generate_sync_facade.py`.
"""

import typing
from collections.abc import Generator
from enum import StrEnum
from typing import Any

import aiohttp
from whenever import Date, PlainDateTime, ZonedDateTime

from hassette.const.misc import FalseySentinel
from hassette.models.helpers import (
    CounterRecord,
    CreateCounterParams,
    CreateInputBooleanParams,
    CreateInputButtonParams,
    CreateInputDatetimeParams,
    CreateInputNumberParams,
    CreateInputSelectParams,
    CreateInputTextParams,
    CreateTimerParams,
    InputBooleanRecord,
    InputButtonRecord,
    InputDatetimeRecord,
    InputNumberRecord,
    InputSelectRecord,
    InputTextRecord,
    TimerRecord,
    UpdateCounterParams,
    UpdateInputBooleanParams,
    UpdateInputButtonParams,
    UpdateInputDatetimeParams,
    UpdateInputNumberParams,
    UpdateInputSelectParams,
    UpdateInputTextParams,
    UpdateTimerParams,
)
from hassette.models.history import HistoryEntry
from hassette.models.services import ServiceResponse
from hassette.resources.base import Resource
from hassette.types.types import LOG_LEVEL_TYPE

if typing.TYPE_CHECKING:
    from hassette import Api, Hassette
    from hassette.events.hass.raw import HassStateDict
    from hassette.models.entities import EntityT
    from hassette.models.states.base import BaseState

'''


CLASS_HEADER = '''
class ApiSyncFacade(Resource):
    """Synchronous facade for the API service.

    This class provides synchronous methods that wrap the asynchronous methods of the Api class,
    allowing for blocking calls in a synchronous context.

    It is important to note that these methods should not be called from within an existing event loop,
    as they will raise a RuntimeError in such cases. Use the asynchronous methods directly when operating
    within an event loop.
    """

    _api: "Api"

    def __init__(self, hassette: "Hassette", *, api: "Api", parent: Resource | None = None) -> None:
        super().__init__(hassette, parent=parent)
        self._api = api

    async def on_initialize(self) -> None:
        self.mark_ready(reason="Synchronous API facade initialized")

    @property
    def config_log_level(self) -> LOG_LEVEL_TYPE:
        """Return the log level from the config for this resource."""
        return self.hassette.config.api_log_level

'''


# ---------------------------------------------------------------------------
# Recording facade class header template — pinned verbatim from design.md
# "Class header template (pinned)" subsection.
# ---------------------------------------------------------------------------
_RECORDING_CLASS_HEADER = '''\
class _RecordingSyncFacade:  # pyright: ignore[reportUnusedClass]
    """Synchronous recording facade for RecordingApi.

    Instances are created by RecordingApi.__init__ and share the parent's
    `calls` list via the `_parent` reference. Users access it via `harness.api_recorder.sync`
    (which is `RecordingApi.sync`).

    This file is generated by tools/generate_sync_facade.py — do not edit by hand.
    """

    _parent: "RecordingApi"

    def __init__(self, parent: "RecordingApi") -> None:
        self._parent = parent

    # NOTE: __getattr__ raises AttributeError for names starting with `_`, including `_parent`.
    # If `_parent` lookup falls through here (e.g., during mock construction before __init__
    # completes, or in a subclass that skips super().__init__), the error will be
    # AttributeError: _parent — which is by design; partial construction is an error.
    def __getattr__(self, name: str) -> Any:
        """Raise NotImplementedError for public attributes not defined on _RecordingSyncFacade.

        Private attributes fall through to the default AttributeError so that Python
        machinery works correctly. All known public methods from ``ApiSyncFacade``
        are explicitly generated (either body-copied from RecordingApi or stubbed
        with NotImplementedError). This fallback catches any public attribute that
        is not a generated method — typically a typo or a brand-new method on
        ``ApiSyncFacade`` that the CI drift gate is about to flag.
        """
        if name.startswith("_"):
            raise AttributeError(name)

        raise NotImplementedError(_STUB_MSG_GENERIC.format(name=name))
'''

# Template for the module header of the generated recording facade file.
# {imports} is replaced with the dynamically-derived import block.
# {type_checking_imports} is replaced with the TYPE_CHECKING import block.
_RECORDING_MODULE_HEADER_TEMPLATE = '''\
"""Synchronous recording facade for RecordingApi.

Do not edit this file directly.

It is generated from RecordingApi by tools/generate_sync_facade.py.
"""

import typing
from typing import Any

{imports}

if typing.TYPE_CHECKING:
    from hassette.test_utils.recording_api import RecordingApi
{type_checking_imports}
# ---------------------------------------------------------------------------
# Stub message templates — imported by tests to avoid brittle substring matches.
# Must stay byte-identical with the constants in tools/generate_sync_facade.py.
# ---------------------------------------------------------------------------
_STUB_MSG_STATE_CONVERSION = (
    "RecordingApi.sync.{{name}} is not implemented on the test facade. "
    "Call `harness.api_recorder.sync.get_state(entity_id)` and read the returned state directly."
)
_STUB_MSG_GENERIC = (
    "RecordingApi.sync.{{name}} is not implemented. "
    "Seed state via AppTestHarness.set_state() for read methods, "
    "or use a full integration test for methods requiring a live HA connection."
)

'''


LIFECYCLE_METHODS = frozenset(
    {
        "initialize",
        "shutdown",
        "restart",
        "cleanup",
        "before_initialize",
        "on_initialize",
        "after_initialize",
        "before_shutdown",
        "on_shutdown",
        "after_shutdown",
    }
)
"""Resource lifecycle hooks that should NOT be wrapped as sync facades."""


def _safe_parse(source: str, filename: str) -> ast.Module:
    """Parse Python source, raising SystemExit with a clean message on SyntaxError."""
    try:
        return ast.parse(source, filename=filename)
    except SyntaxError as e:
        raise SystemExit(f"Syntax error in {filename}: {e}") from e


def is_overload(func: ast.AsyncFunctionDef) -> bool:
    """Return True if this function is an @overload stub."""
    for deco in func.decorator_list:
        if isinstance(deco, ast.Name) and deco.id == "overload":
            return True
        if isinstance(deco, ast.Attribute) and deco.attr == "overload":
            return True
    return False


def format_signature_and_call(func: ast.AsyncFunctionDef) -> tuple[str, str]:
    """Return (signature_source, call_arguments_source) for a function.

    - Signature includes `self` exactly as in the original.
    - Call string omits `self` and preserves positional, varargs, kwonly, and kwargs.
    """
    args = func.args

    parts: list[str] = []
    call_parts: list[str] = []

    # Positional-only + regular args
    total_pos = args.posonlyargs + args.args
    defaults = list(args.defaults)

    # Map defaults to the last N positional args
    defaults_map: dict[int, ast.expr] = {}
    if defaults:
        for arg, default in zip(total_pos[-len(defaults) :], defaults, strict=False):
            defaults_map[id(arg)] = default

    # Positional-only args
    for arg in args.posonlyargs:
        name = arg.arg
        annotation = f": {ast.unparse(arg.annotation)}" if arg.annotation else ""
        default = ""
        if id(arg) in defaults_map:
            default = f" = {ast.unparse(defaults_map[id(arg)])}"
        parts.append(f"{name}{annotation}{default}")
        call_parts.append(name)

    if args.posonlyargs:
        parts.append("/")

    # Regular positional args (includes self)
    for arg in args.args:
        name = arg.arg
        annotation = f": {ast.unparse(arg.annotation)}" if arg.annotation else ""
        default = ""
        if id(arg) in defaults_map:
            default = f" = {ast.unparse(defaults_map[id(arg)])}"
        parts.append(f"{name}{annotation}{default}")
        if name != "self":
            call_parts.append(name)

    # *vararg
    if args.vararg:
        name = args.vararg.arg
        annotation = f": {ast.unparse(args.vararg.annotation)}" if args.vararg.annotation else ""
        parts.append(f"*{name}{annotation}")
        call_parts.append(f"*{name}")

    # kwonly args
    if args.kwonlyargs:
        # If there was no *vararg we need a bare * to start kw-only section
        if not args.vararg:
            parts.append("*")

        for arg, default in itertools.zip_longest(args.kwonlyargs, args.kw_defaults):
            assert arg is not None
            name = arg.arg
            annotation = f": {ast.unparse(arg.annotation)}" if arg.annotation else ""
            if default is not None:
                parts.append(f"{name}{annotation} = {ast.unparse(default)}")
            else:
                parts.append(f"{name}{annotation}")
            call_parts.append(f"{name}={name}")

    # **kwargs
    if args.kwarg:
        name = args.kwarg.arg
        annotation = f": {ast.unparse(args.kwarg.annotation)}" if args.kwarg.annotation else ""
        parts.append(f"**{name}{annotation}")
        call_parts.append(f"**{name}")

    sig_str = ", ".join(parts)
    call_str = ", ".join(call_parts)
    return sig_str, call_str


def gen_wrapper(func: ast.AsyncFunctionDef) -> str:
    """Emit a sync wrapper method that delegates to self._api via run_sync."""
    sig, call = format_signature_and_call(func)
    name = func.name
    returns = f" -> {ast.unparse(func.returns)}" if func.returns else ""

    doc = ast.get_docstring(func)
    if doc:
        doc_str = textwrap.indent('"""' + doc + '"""', " " * 8)
        doc_block = f"\n{doc_str}\n\n"
    else:
        doc_block = "\n"

    body = (
        f"    def {name}({sig}){returns}:{doc_block}"
        f"        return self.task_bucket.run_sync(self._api.{name}({call}))\n"
    )
    return body


def generate_sync(api_path: Path) -> str:
    """Generate the ApiSyncFacade source from api.py."""
    source = api_path.read_text(encoding="utf8")
    module = _safe_parse(source, str(api_path))

    api_class: ast.ClassDef | None = None
    for node in module.body:
        if isinstance(node, ast.ClassDef) and node.name == "Api":
            api_class = node
            break

    if api_class is None:
        raise SystemExit("Could not find class `Api` in api.py")

    wrappers: list[str] = [
        gen_wrapper(node)
        for node in api_class.body
        if isinstance(node, ast.AsyncFunctionDef) and not is_overload(node) and node.name not in LIFECYCLE_METHODS
    ]

    wrappers_str = "\n".join(wrappers)

    return HEADER + CLASS_HEADER + wrappers_str


def _run_ruff_step(cmd: list[str], step_name: str) -> None:
    """Run a single ruff subprocess step, converting expected failure modes to ``SystemExit``.

    Wraps ``subprocess.run(..., check=True)`` with handlers for ``FileNotFoundError``
    (missing ruff binary), ``TimeoutExpired`` (30s cap exceeded), and
    ``CalledProcessError`` (ruff exited non-zero on e.g. invalid syntax in the generated
    output), so callers never surface a raw Python traceback to the pre-commit hook or
    CI log. The ruff process is run with stdout/stderr streaming to the terminal, so on
    a ``CalledProcessError`` the human-readable diagnostic is already visible above the
    ``SystemExit`` message — we just tell the user to look up.
    """
    try:
        subprocess.run(cmd, check=True, timeout=30)
    except FileNotFoundError as exc:
        raise SystemExit("ruff not found on PATH. Install with: uv tool install ruff") from exc
    except subprocess.TimeoutExpired as exc:
        raise SystemExit(f"ruff {step_name} timed out after 30s — check for filesystem stall") from exc
    except subprocess.CalledProcessError as exc:
        raise SystemExit(
            f"ruff {step_name} failed with exit code {exc.returncode}. See the ruff output above for details."
        ) from exc


def _format_via_ruff(content: str) -> str:
    """Write content to a temp file, normalize it through ruff, return the result.

    The temp file is placed in tempfile.gettempdir() (outside the repo) so that
    --check mode never leaves files inside the worktree that would confuse git.

    Applies the **byte-affecting** subset of ``run_ruff``'s steps — ``ruff
    format`` and the import-sort fix (``ruff check --fix --select I``) — so
    that --check-mode comparison and the on-disk write path produce
    byte-identical output. The third step ``run_ruff`` runs (``ruff check``
    validation, no --fix) is intentionally skipped here because it does not
    modify file bytes; running it would only slow check mode without
    affecting the comparison.

    Without the isort step here, the generator's raw output (with unsorted
    imports) would never byte-equal the on-disk committed file (which was
    sorted by ``run_ruff`` at write time), producing a false drift signal.
    """
    tmp_path: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".py",
            dir=tempfile.gettempdir(),
            delete=False,
            encoding="utf-8",
        ) as tmp:
            tmp.write(content)
            tmp_path = tmp.name

        _run_ruff_step(["ruff", "format", tmp_path], "format")
        # Apply the same isort step as run_ruff() so the comparison is
        # symmetric — the on-disk committed file was sorted at write time.
        _run_ruff_step(["ruff", "check", "--fix", "--select", "I", tmp_path], "isort")

        return Path(tmp_path).read_text(encoding="utf-8")
    finally:
        if tmp_path is not None:
            with contextlib.suppress(OSError):
                Path(tmp_path).unlink()


def run_ruff(path: Path) -> None:
    """Run ruff format + import-sort fix + ruff check on path, raising SystemExit on any failure."""
    _run_ruff_step(["ruff", "format", str(path)], "format")
    # auto-fix import ordering (I001 / isort) — safe fixable-only rule
    _run_ruff_step(["ruff", "check", "--fix", "--select", "I", str(path)], "isort")
    # validate (all rules, no --fix)
    _run_ruff_step(["ruff", "check", str(path)], "check")


def _atomic_write_generated(out_path: Path, content: str) -> None:
    """Atomically write generated source, run ruff + py_compile, then rename into place.

    A previous non-atomic implementation wrote the raw output in-place and then ran ruff
    over the committed file. A Ctrl-C, OOM kill, or ruff timeout between those steps left
    the committed file in an unformatted or partially-written state — which the CI drift
    gate then flagged spuriously on the next push.

    This helper writes to a temp file in the same directory (so ``Path.replace`` is
    atomic on the same filesystem), runs the full ``ruff`` pipeline and a ``py_compile``
    safety net against the temp file, and only atomically replaces the committed file
    if every step succeeds. If anything fails, the temp file is removed and the
    committed file is left untouched.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        # delete=False so we can close, run ruff on the path, then os.replace it.
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf8",
            dir=out_path.parent,
            prefix=f".{out_path.name}.",
            suffix=".tmp",
            delete=False,
        ) as fp:
            fp.write(content)
            tmp_path = Path(fp.name)

        run_ruff(tmp_path)

        # Post-generation safety net: verify the output compiles. Catches missing imports
        # for type-annotation-only symbols that slip past ``ruff check`` but would fail
        # at import/type-check time.
        try:
            py_compile.compile(str(tmp_path), doraise=True)
        except py_compile.PyCompileError as exc:
            raise SystemExit(f"Generated file failed py_compile (target: {out_path}): {exc}") from exc

        tmp_path.replace(out_path)
        tmp_path = None
    finally:
        if tmp_path is not None:
            with contextlib.suppress(OSError):
                tmp_path.unlink()


# ---------------------------------------------------------------------------
# AST body rewriter for RecordingApi → _RecordingSyncFacade
# ---------------------------------------------------------------------------


class _RecordingBodyRewriter(ast.NodeTransformer):
    """Rewrite async body nodes for use in a synchronous facade.

    Two transforms:
    1. ``self.X`` → ``self._parent.X`` — only at the outermost position.
       ``self.hassette.foo`` becomes ``self._parent.hassette.foo``;
       the chain is left intact.
    2. ``await expr`` → ``expr`` — strips the Await wrapper.

    The transformer must be dispatched on individual ``FunctionDef.body``
    statements via ``self.visit(stmt)``, never on the whole FunctionDef node.
    This ensures default-argument expressions (which live in ``func.args``,
    not ``func.body``) are never rewritten.
    """

    def visit_Attribute(self, node: ast.Attribute) -> ast.AST:
        """Rewrite only the outermost self.X reference in attribute chains."""
        # First, recurse into all children so nested chains get rewritten.
        self.generic_visit(node)

        # After generic_visit, check if the direct value of THIS attribute
        # node is a plain `self` name — if so, insert `_parent` one level up.
        if isinstance(node.value, ast.Name) and node.value.id == "self":
            # Replace self.X with self._parent.X
            new_value = ast.Attribute(
                value=ast.Name(id="self", ctx=ast.Load()),
                attr="_parent",
                ctx=ast.Load(),
            )
            ast.copy_location(new_value, node.value)
            node.value = new_value
        return node

    def visit_Await(self, node: ast.Await) -> ast.AST:
        """Strip the await, returning the inner expression."""
        # Recurse into the inner value first so self refs inside are rewritten.
        return self.visit(node.value)


# ---------------------------------------------------------------------------
# Generator-time async-peer-call static check
# ---------------------------------------------------------------------------


def _check_no_async_peer_calls(
    method_name: str,
    body_nodes: list[ast.stmt],
    async_method_names: set[str],
) -> None:
    """Walk the rewritten body and raise SystemExit if any call targets an async peer.

    After self→self._parent rewriting, peer calls look like
    ``self._parent.foo(...)`` where ``foo`` is async. These would return
    a coroutine instead of a value in the sync facade.

    Args:
        method_name: Name of the method being body-copied (for error messages).
        body_nodes: Rewritten body statement list.
        async_method_names: Set of async method names on RecordingApi.
    """
    for stmt in body_nodes:
        for node in ast.walk(stmt):
            if not isinstance(node, ast.Call):
                continue
            callee = node.func
            # We're looking for self._parent.X(...)
            if not isinstance(callee, ast.Attribute):
                continue
            callee_value = callee.value
            if not (
                isinstance(callee_value, ast.Attribute)
                and isinstance(callee_value.value, ast.Name)
                and callee_value.value.id == "self"
                and callee_value.attr == "_parent"
            ):
                continue
            peer_name = callee.attr
            if peer_name in async_method_names:
                lineno = getattr(node, "lineno", "?")
                raise SystemExit(
                    f"Generator error: method `{method_name}` body-copies a call to "
                    f"`self._parent.{peer_name}()` at line {lineno}, but `{peer_name}` is "
                    f"an async def on RecordingApi. "
                    f"Refactor `RecordingApi.{method_name}` to call a sync helper "
                    f"(e.g. `_get_raw_state`, `_convert_state`) directly, or document "
                    f"why this method should be in the NotImplementedError stub tier."
                )


# ---------------------------------------------------------------------------
# Dynamic import derivation
# ---------------------------------------------------------------------------


def _collect_type_checking_import_map(source: str) -> dict[str, str]:
    """Build a symbol → import-statement-source map from TYPE_CHECKING blocks only.

    These symbols are only available at type-check time and must be placed in
    ``if typing.TYPE_CHECKING:`` blocks in the generated file.
    """
    module = _safe_parse(source, "<source>")
    symbol_map: dict[str, str] = {}

    for node in module.body:
        if isinstance(node, ast.If):
            test = node.test
            is_type_checking = (isinstance(test, ast.Attribute) and test.attr == "TYPE_CHECKING") or (
                isinstance(test, ast.Name) and test.id == "TYPE_CHECKING"
            )
            if not is_type_checking:
                continue
            # This IS a TYPE_CHECKING block — collect all imports inside
            for child in ast.walk(node):
                if child is node:
                    continue
                if isinstance(child, ast.ImportFrom):
                    stmt_source = ast.unparse(child)
                    for alias in child.names:
                        alias_name = alias.asname if alias.asname else alias.name
                        symbol_map[alias_name] = stmt_source

    return symbol_map


def _collect_module_level_import_map(source: str) -> dict[str, str]:
    """Build a symbol → import-statement-source map from only module-level imports.

    For ``from X import A, B, C`` lines, each symbol is mapped individually to
    the whole import line. However, ``_build_precise_import_block`` should be
    used when you need only the symbols actually required (to avoid emitting
    unused imports from multi-symbol import lines).

    This skips TYPE_CHECKING blocks and only includes imports at the module
    top level (not inside functions or classes).
    """
    module = _safe_parse(source, "<source>")
    symbol_map: dict[str, str] = {}

    def _add_import_node(import_node: ast.ImportFrom | ast.Import) -> None:
        stmt_source = ast.unparse(import_node)
        for alias in import_node.names:
            alias_name = alias.asname if alias.asname else alias.name
            symbol_map[alias_name] = stmt_source

    for node in module.body:
        # Skip TYPE_CHECKING conditional blocks
        if isinstance(node, ast.If):
            test = node.test
            is_type_checking = (isinstance(test, ast.Attribute) and test.attr == "TYPE_CHECKING") or (
                isinstance(test, ast.Name) and test.id == "TYPE_CHECKING"
            )
            if is_type_checking:
                continue
            # Non-TYPE_CHECKING if blocks: recurse one level for both
            # `from X import Y` and bare `import X` statements (e.g., a future
            # `if sys.version_info >= (3, 11): import tomllib`).
            for child in ast.walk(node):
                if child is node:
                    continue
                if isinstance(child, (ast.ImportFrom, ast.Import)):
                    _add_import_node(child)
        elif isinstance(node, (ast.ImportFrom, ast.Import)):
            _add_import_node(node)

    return symbol_map


def _build_precise_import_block(
    needed_symbols: set[str],
    symbol_map: dict[str, str],
) -> str:
    """Build a minimal import block for exactly the needed_symbols.

    Unlike using the raw symbol_map (which emits entire multi-symbol import lines),
    this function reconstructs each import statement with ONLY the symbols that
    are actually needed. This avoids emitting unused imports from lines like
    ``from typing import TYPE_CHECKING, Any, ClassVar, Never, Protocol, cast``.

    For ``from X import A, B`` style: groups needed symbols by module path,
    emits one ``from X import <needed>`` per module.
    For bare ``import X`` style: emits the full line as-is.
    """
    # Parse each unique import line once to determine module path and names
    # key: module_path, value: set of (name, asname_or_None) tuples needed
    from_imports: dict[str, list[tuple[str, str | None]]] = {}
    bare_imports: set[str] = set()

    # Build a mapping from module path → {all_symbols → alias} from the symbol_map
    module_to_aliases: dict[str, dict[str, str | None]] = {}  # module_path → {name: asname}

    # Parse unique import lines
    seen_lines: set[str] = set()
    for sym, line in symbol_map.items():
        if sym not in needed_symbols:
            continue
        if line in seen_lines:
            continue
        seen_lines.add(line)
        try:
            parsed = ast.parse(line, mode="single")
        except SyntaxError:
            continue
        for stmt in ast.walk(parsed):
            if isinstance(stmt, ast.ImportFrom) and stmt.module:
                module = stmt.module
                if module not in module_to_aliases:
                    module_to_aliases[module] = {}
                for alias in stmt.names:
                    module_to_aliases[module][alias.name] = alias.asname
            elif isinstance(stmt, ast.Import):
                for _alias in stmt.names:
                    bare_imports.add(ast.unparse(stmt))

    # Now build precise from-imports: only emit the symbols we actually need
    for module_path, all_aliases in module_to_aliases.items():
        needed_for_module = [
            (name, asname)
            for name, asname in sorted(all_aliases.items())
            if (asname if asname else name) in needed_symbols
        ]
        if needed_for_module:
            if module_path not in from_imports:
                from_imports[module_path] = []
            from_imports[module_path].extend(needed_for_module)

    lines: list[str] = list(sorted(bare_imports))
    for module_path in sorted(from_imports.keys()):
        names_part = ", ".join(
            f"{name} as {asname}" if asname else name for name, asname in sorted(from_imports[module_path])
        )
        lines.append(f"from {module_path} import {names_part}")

    return "\n".join(lines)


def _collect_referenced_symbols(body_nodes: list[ast.stmt]) -> set[str]:
    """Walk body_nodes and collect all ast.Name ids, excluding builtins."""
    referenced: set[str] = set()
    for stmt in body_nodes:
        for node in ast.walk(stmt):
            if isinstance(node, ast.Name):
                referenced.add(node.id)
    referenced -= _BUILTIN_NAMES
    referenced -= _WELL_KNOWN_NAMES
    return referenced


def _derive_recording_imports_strict(
    body_nodes: list[ast.stmt],
    symbol_map: dict[str, str],
    method_name: str = "<unknown>",
) -> str:
    """Strict variant of import derivation: raises on unknown type-like symbols.

    A "type-like symbol" is one that starts with an uppercase letter (classes,
    exceptions, type aliases), indicating it is likely an import rather than a
    local variable. Lowercase names are assumed to be local variables/parameters
    and are silently skipped.

    Used **only by the unit test for the error case**. Production generation
    uses ``_build_precise_import_block`` directly (which is silently lenient
    about unknown symbols and emits only the lines for symbols it can resolve)
    because method bodies reference many lowercase symbols that are local
    variables, parameters, or comprehension targets — not imports.
    """
    referenced_symbols = _collect_referenced_symbols(body_nodes)
    # Only check uppercase-starting symbols (likely type/class references)
    type_like_symbols = {s for s in referenced_symbols if s and s[0].isupper()}

    import_lines: set[str] = set()
    for sym in type_like_symbols:
        if sym in symbol_map:
            import_lines.add(symbol_map[sym])
        else:
            raise SystemExit(
                f"Method `{method_name}` uses symbol `{sym}` with no known import path; "
                f"add `{sym}` to `recording_api.py`'s imports"
            )

    return "\n".join(sorted(import_lines))


# ---------------------------------------------------------------------------
# gen_recording_method: body-copy a single RecordingApi async method to sync
# ---------------------------------------------------------------------------


def gen_recording_method(func: ast.AsyncFunctionDef, async_method_names: set[str]) -> tuple[str, list[ast.stmt]]:
    """Generate a sync method by body-copying and rewriting a RecordingApi async method.

    The function:
    1. Deep-copies the function AST (to avoid mutating the source).
    2. Dispatches _RecordingBodyRewriter on each BODY statement individually
       (never on func itself, preserving default-argument expressions).
    3. Checks for surviving ast.Await nodes (invariant).
    4. Checks for async peer calls (static check).
    5. Emits a sync def using the original signature + rewritten body.

    Args:
        func: The RecordingApi async function node.
        async_method_names: All async method names on RecordingApi (for peer-call check).

    Returns:
        Tuple of (generated_source_string, rewritten_body_nodes).
    """
    # Clone via deep copy to avoid mutating the parsed AST
    func_copy = copy.deepcopy(func)

    # Dispatch rewriter on each body statement individually — never on func_copy itself.
    rewriter = _RecordingBodyRewriter()
    rewritten_body: list[ast.stmt] = []
    for stmt in func_copy.body:
        new_stmt = rewriter.visit(stmt)
        ast.fix_missing_locations(new_stmt)
        rewritten_body.append(new_stmt)

    # Invariant check: no surviving ast.Await nodes
    for stmt in rewritten_body:
        for node in ast.walk(stmt):
            if isinstance(node, ast.Await):
                raise SystemExit(
                    f"Generator error: method `{func.name}` still contains an `await` expression "
                    f"after body rewriting. Add explicit `_get_raw_state`/`_convert_state` "
                    f"sync helpers to `RecordingApi.{func.name}` instead of awaiting async peers."
                )

    # Generator-time async-peer-call static check
    _check_no_async_peer_calls(func.name, rewritten_body, async_method_names)

    # Build the sync def source
    name = func.name
    returns = f" -> {ast.unparse(func.returns)}" if func.returns else ""

    # Build signature from the original (pre-copy) func so defaults stay as-is
    sig, _ = format_signature_and_call(func)

    doc = ast.get_docstring(func)
    if doc:
        doc_str = textwrap.indent('"""' + doc + '"""', " " * 8)
        doc_block = f"\n{doc_str}\n\n"
    else:
        doc_block = "\n"

    # Emit the body statements via ast.unparse
    body_lines = []
    # Skip the docstring (first stmt if it's an Expr/Constant) since we already handled it
    body_start = 1 if doc else 0
    for stmt in rewritten_body[body_start:]:
        unparsed = ast.unparse(stmt)
        body_lines.append(textwrap.indent(unparsed, " " * 8))

    if not body_lines:
        body_lines = ["        pass"]

    body_str = "\n".join(body_lines)

    method_src = f"    def {name}({sig}){returns}:{doc_block}{body_str}\n"

    return method_src, rewritten_body


# ---------------------------------------------------------------------------
# gen_recording_stub: emit a NotImplementedError stub for unimplemented methods
# ---------------------------------------------------------------------------


def gen_recording_stub(func: ast.AsyncFunctionDef) -> str:
    """Emit a sync stub method raising NotImplementedError with tiered message.

    Args:
        func: The Api async function node (used for the signature).

    Returns:
        The generated method source string. Unlike ``gen_recording_method``,
        no rewritten body nodes are returned — stubs do not contribute body
        statements that the import-derivation pass needs to inspect.
    """
    name = func.name
    returns = f" -> {ast.unparse(func.returns)}" if func.returns else ""
    sig, _ = format_signature_and_call(func)

    # Emit a NotImplementedError using the module-level _STUB_MSG_* constant name.
    # We reference the constant by name (not value) so the generated file uses the
    # same constant that tests import, making message changes a single-location edit.
    msg_const = "_STUB_MSG_STATE_CONVERSION" if name in _STATE_CONVERSION_METHODS else "_STUB_MSG_GENERIC"

    return f'    def {name}({sig}){returns}:\n        raise NotImplementedError({msg_const}.format(name="{name}"))\n'


# ---------------------------------------------------------------------------
# generate_sync_recording: full generation pass for _RecordingSyncFacade
# ---------------------------------------------------------------------------


def _is_not_implemented_only(func: ast.AsyncFunctionDef) -> bool:
    """Return True if the function body only calls _not_implemented (plus optional docstring/raise).

    Such methods in RecordingApi exist solely to satisfy the async protocol —
    they should be treated as stubs in the generated facade, not body-copied.
    The rewriter would turn ``_not_implemented(name)`` into ``self._parent._not_implemented(name)``
    which doesn't exist in the generated file.
    """
    body = func.body
    for stmt in body:
        # Skip docstrings
        if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str):
            continue
        # Skip ``raise RuntimeError("unreachable")``
        if isinstance(stmt, ast.Raise):
            continue
        # A call to _not_implemented(name) is an ast.Expr wrapping an ast.Call
        if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call):
            call = stmt.value
            if isinstance(call.func, ast.Name) and call.func.id == "_not_implemented":
                continue
        # Anything else means the body is more complex
        return False
    return True


def _collect_annotation_symbols(func: ast.AsyncFunctionDef) -> tuple[set[str], set[str]]:
    """Collect Name ids from all type annotations in a function's signature and return type.

    Returns:
        Tuple of (runtime_symbols, string_ref_symbols):
        - runtime_symbols: Names used in non-quoted annotations (need direct imports).
        - string_ref_symbols: Names inside quoted string annotations (need TYPE_CHECKING imports).
    """
    runtime_symbols: set[str] = set()
    string_ref_symbols: set[str] = set()

    def _walk_annotation(annotation: ast.expr) -> None:
        for node in ast.walk(annotation):
            if isinstance(node, ast.Name):
                runtime_symbols.add(node.id)
            elif isinstance(node, ast.Constant) and isinstance(node.value, str):
                # Quoted annotation — parse the string and collect names from it
                try:
                    inner = ast.parse(node.value, mode="eval")
                    for inner_node in ast.walk(inner):
                        if isinstance(inner_node, ast.Name):
                            string_ref_symbols.add(inner_node.id)
                except SyntaxError:
                    pass

    args = func.args
    all_args = args.posonlyargs + args.args + args.kwonlyargs
    if args.vararg:
        all_args = [*all_args, args.vararg]
    if args.kwarg:
        all_args = [*all_args, args.kwarg]

    for arg in all_args:
        if arg.annotation:
            _walk_annotation(arg.annotation)

    if func.returns:
        _walk_annotation(func.returns)

    return runtime_symbols, string_ref_symbols


def generate_sync_recording(api_path: Path, recording_api_path: Path) -> str:
    """Generate the full _RecordingSyncFacade source.

    Imports are derived via ``_collect_referenced_symbols`` +
    ``_build_precise_import_block`` directly. This pair is **lenient** about
    unknown symbols (it skips any name that doesn't appear in the symbol map)
    because body-copied method bodies reference many lowercase symbols that are
    local variables, parameters, or comprehension targets — not imports. The
    strict variant ``_derive_recording_imports_strict`` is reserved for unit
    tests that need to assert the error path; the post-generation
    ``ruff check`` + ``py_compile`` steps are the safety net for genuinely
    missing imports in production.

    Args:
        api_path: Path to src/hassette/api/api.py (source of truth for method list).
        recording_api_path: Path to src/hassette/test_utils/recording_api.py.

    Returns:
        Complete Python source string for the generated sync_facade.py.
    """
    # Parse Api to get the ordered method list
    api_source = api_path.read_text(encoding="utf8")
    api_module = _safe_parse(api_source, str(api_path))

    api_class: ast.ClassDef | None = None
    for node in api_module.body:
        if isinstance(node, ast.ClassDef) and node.name == "Api":
            api_class = node
            break
    if api_class is None:
        raise SystemExit("Could not find class `Api` in api.py")

    # Collect all public async methods on Api (ordered, no overloads, no lifecycle)
    api_methods: list[ast.AsyncFunctionDef] = [
        node
        for node in api_class.body
        if isinstance(node, ast.AsyncFunctionDef) and not is_overload(node) and node.name not in LIFECYCLE_METHODS
    ]

    # Parse RecordingApi
    recording_source = recording_api_path.read_text(encoding="utf8")
    recording_module = _safe_parse(recording_source, str(recording_api_path))

    recording_class: ast.ClassDef | None = None
    for node in recording_module.body:
        if isinstance(node, ast.ClassDef) and node.name == "RecordingApi":
            recording_class = node
            break
    if recording_class is None:
        raise SystemExit("Could not find class `RecordingApi` in recording_api.py")

    # Build map of async method name → AST node for RecordingApi
    recording_async_map: dict[str, ast.AsyncFunctionDef] = {}
    for node in recording_class.body:
        if isinstance(node, ast.AsyncFunctionDef):
            recording_async_map[node.name] = node

    # Collect ALL async method names (for the peer-call static check)
    async_method_names: set[str] = set(recording_async_map.keys())

    # Build the symbol map from both recording_api.py and api.py imports.
    # api.py imports cover stub signatures (PlainDateTime, ZonedDateTime, StrEnum, etc.)
    recording_symbol_map = _collect_module_level_import_map(recording_source)
    api_symbol_map = _collect_module_level_import_map(api_source)
    # Merge: recording_api takes precedence (it's the primary source)
    combined_symbol_map = {**api_symbol_map, **recording_symbol_map}

    # Also collect TYPE_CHECKING imports from both files (symbols only available at type-check time)
    recording_tc_map = _collect_type_checking_import_map(recording_source)
    api_tc_map = _collect_type_checking_import_map(api_source)
    combined_tc_map = {**api_tc_map, **recording_tc_map}

    # Symbols that are always provided by the fixed header (no need to derive dynamically)
    fixed_header_symbols: frozenset[str] = frozenset({"Any", "typing", "TYPE_CHECKING", "RecordingApi"})

    # Generate each method; track body nodes for import derivation.
    generated_methods: list[str] = []
    all_body_nodes: list[ast.stmt] = []
    all_runtime_annotation_symbols: set[str] = set()
    all_string_ref_symbols: set[str] = set()

    for api_func in api_methods:
        method_name = api_func.name
        rec_func = recording_async_map.get(method_name)

        # Determine whether to body-copy or stub.
        # RecordingApi methods that only call _not_implemented are treated as stubs.
        use_body_copy = rec_func is not None and not _is_not_implemented_only(rec_func)

        if use_body_copy:
            assert rec_func is not None
            # Collect annotation symbols from the recording_api signature
            runtime_syms, string_syms = _collect_annotation_symbols(rec_func)
            all_runtime_annotation_symbols |= runtime_syms
            all_string_ref_symbols |= string_syms
            # Body-copy from RecordingApi
            method_src, body_nodes = gen_recording_method(rec_func, async_method_names)
            generated_methods.append(method_src)
            all_body_nodes.extend(body_nodes)
        else:
            # Stub — use the Api signature for the stub type annotations
            runtime_syms, string_syms = _collect_annotation_symbols(api_func)
            all_runtime_annotation_symbols |= runtime_syms
            all_string_ref_symbols |= string_syms
            method_src = gen_recording_stub(api_func)
            generated_methods.append(method_src)

    # Collect all symbols that need to be imported at runtime
    body_symbols = _collect_referenced_symbols(all_body_nodes)
    needed_symbols = (body_symbols | all_runtime_annotation_symbols) - fixed_header_symbols

    # Build a precise import block — only the symbols actually needed, not whole multi-symbol lines
    import_block = _build_precise_import_block(needed_symbols, combined_symbol_map)

    # Build the TYPE_CHECKING block for forward-reference symbols not available at runtime.
    # These are string annotations (quoted types) that only need to be resolvable for type checkers.
    # Also handle symbols from TYPE_CHECKING blocks in source files (like HassStateDict, EntityT).
    # RecordingApi is always included (needed for the class header forward ref, handled in template).
    type_checking_symbols = all_string_ref_symbols - fixed_header_symbols - needed_symbols
    # Build additional TYPE_CHECKING lines from the TC symbol maps
    type_checking_extra_lines: list[str] = []
    for sym in sorted(type_checking_symbols):
        if sym in combined_tc_map:
            # Build a single-symbol import line for this type-checking-only symbol
            precise = _build_precise_import_block({sym}, combined_tc_map)
            if precise:
                type_checking_extra_lines.append(f"    {precise}")
        elif sym in combined_symbol_map:
            # Fall back to runtime symbol map (might be a type not tagged as TC-only)
            precise = _build_precise_import_block({sym}, combined_symbol_map)
            if precise:
                type_checking_extra_lines.append(f"    {precise}")
    type_checking_imports = ("\n" + "\n".join(type_checking_extra_lines) + "\n") if type_checking_extra_lines else "\n"

    # Optional: warn about signature default mismatches. Only applies to body-copied
    # methods — stub-tier methods inherit their signature from Api and never carry
    # RecordingApi defaults, so a "mismatch" there is a false positive that trains
    # developers to ignore the warning entirely.
    for api_func in api_methods:
        if api_func.name in recording_async_map:
            rec_func_check = recording_async_map[api_func.name]
            if _is_not_implemented_only(rec_func_check):
                continue
            api_defaults = [ast.unparse(d) for d in api_func.args.defaults]
            rec_defaults = [ast.unparse(d) for d in rec_func_check.args.defaults]
            if api_defaults != rec_defaults:
                print(
                    f"Warning: default mismatch for `{api_func.name}`: "
                    f"Api defaults={api_defaults!r}, RecordingApi defaults={rec_defaults!r}",
                    file=sys.stderr,
                )

    methods_str = "\n".join(generated_methods)

    return (
        _RECORDING_MODULE_HEADER_TEMPLATE.format(
            imports=import_block,
            type_checking_imports=type_checking_imports,
        )
        + _RECORDING_CLASS_HEADER
        + "\n"
        + methods_str
    )


def _check_drift(target_path: Path, generated_content: str, label: str) -> bool:
    """Check if target_path content matches generated_content after ruff normalization.

    Args:
        target_path: Path to the committed file.
        generated_content: Freshly generated content.
        label: Human-readable label for the error message (e.g. "ApiSyncFacade").

    Returns:
        True if in-sync, False if drift detected.
    """
    if not target_path.exists():
        print(
            f"{label} is out of date (target file does not exist).\nRe-run: uv run tools/generate_sync_facade.py",
            file=sys.stderr,
        )
        return False

    committed_content = target_path.read_text(encoding="utf-8")
    normalized_committed = _format_via_ruff(committed_content)
    normalized_generated = _format_via_ruff(generated_content)

    if normalized_committed == normalized_generated:
        return True

    if label == "ApiSyncFacade":
        rerun_cmd = "uv run tools/generate_sync_facade.py --target api"
    else:
        rerun_cmd = "uv run tools/generate_sync_facade.py --target recording"

    print(
        f"{label} is out of date.\nRe-run: {rerun_cmd}",
        file=sys.stderr,
    )
    return False


def main() -> None:
    """CLI entry point for generate_sync_facade.py."""
    parser = argparse.ArgumentParser(description="Generate sync facade(s) from api.py and recording_api.py")
    parser.add_argument(
        "--api-path",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "src" / "hassette" / "api" / "api.py",
        help="Path to api.py (default: hassette/api.py relative to repo root)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path for sync.py (default: alongside api.py as sync.py)",
    )
    parser.add_argument(
        "--recording-api-path",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "src" / "hassette" / "test_utils" / "recording_api.py",
        help="Path to recording_api.py (default: hassette/test_utils/recording_api.py)",
    )
    parser.add_argument(
        "--recording-out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "src" / "hassette" / "test_utils" / "sync_facade.py",
        help="Output path for the generated recording sync facade",
    )
    parser.add_argument(
        "--target",
        choices=["api", "recording", "both"],
        default="both",
        help="Which facade to generate (default: both)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check mode: exit 1 if generated content differs from committed file",
    )

    args = parser.parse_args()

    api_path: Path = args.api_path
    if not api_path.exists():
        raise SystemExit(f"api.py not found at {api_path}")

    recording_api_path: Path = args.recording_api_path
    recording_out: Path = args.recording_out
    out_path: Path = args.out or api_path.with_name("sync.py")

    run_api = args.target in ("api", "both")
    run_recording = args.target in ("recording", "both")

    any_drift = False

    if run_api:
        api_code = generate_sync(api_path)
        if args.check:
            if not _check_drift(out_path, api_code, "ApiSyncFacade"):
                any_drift = True
        else:
            _atomic_write_generated(out_path, api_code)
            print(f"Wrote {out_path}")

    if run_recording:
        if not recording_api_path.exists():
            raise SystemExit(f"recording_api.py not found at {recording_api_path}")
        recording_code = generate_sync_recording(api_path, recording_api_path)
        if args.check:
            if not _check_drift(recording_out, recording_code, "_RecordingSyncFacade"):
                any_drift = True
        else:
            _atomic_write_generated(recording_out, recording_code)
            print(f"Wrote {recording_out}")

    if args.check and any_drift:
        sys.exit(1)


if __name__ == "__main__":
    main()
