"""Tests for Scheduler job name uniqueness validation."""

import pytest

from hassette.scheduler.triggers import Cron, Every
from hassette.test_utils.factories import make_scheduled_job, make_scheduler


class TestJobNameUniqueness:
    async def test_duplicate_name_raises(self) -> None:
        scheduler = make_scheduler()
        await scheduler.add_job(make_scheduled_job(name="daily_backup"))

        with pytest.raises(ValueError, match="daily_backup"):
            await scheduler.add_job(make_scheduled_job(name="daily_backup"))

    async def test_different_names_ok(self) -> None:
        scheduler = make_scheduler()
        await scheduler.add_job(make_scheduled_job(name="job_a"))
        await scheduler.add_job(make_scheduled_job(name="job_b"))

        assert set(scheduler._jobs_by_name) == {"job_a", "job_b"}

    async def test_auto_named_jobs_also_enforce_uniqueness(self) -> None:
        """Jobs with auto-derived names (from callable) are still subject to uniqueness checks."""
        scheduler = make_scheduler()
        # Both jobs use lambda, so __post_init__ auto-names them "<lambda>".
        job1 = make_scheduled_job(name="")
        job2 = make_scheduled_job(name="")

        await scheduler.add_job(job1)

        with pytest.raises(ValueError, match="<lambda>"):
            await scheduler.add_job(job2)

    async def test_removal_allows_reuse(self) -> None:
        scheduler = make_scheduler()
        job = make_scheduled_job(name="ephemeral")
        await scheduler.add_job(job)
        assert "ephemeral" in scheduler._jobs_by_name

        # Simulate callback-based removal (as fired by scheduler_service.dequeue_job)
        scheduler._on_job_removed(job)
        assert "ephemeral" not in scheduler._jobs_by_name

        # Re-adding with the same name should now succeed
        await scheduler.add_job(make_scheduled_job(name="ephemeral"))
        assert "ephemeral" in scheduler._jobs_by_name

    async def test_remove_all_clears_names(self) -> None:
        scheduler = make_scheduler()
        await scheduler.add_job(make_scheduled_job(name="a"))
        await scheduler.add_job(make_scheduled_job(name="b"))
        assert set(scheduler._jobs_by_name) == {"a", "b"}

        scheduler._remove_all_jobs()
        assert scheduler._jobs_by_name == {}


class TestAutoGeneratedNamesWithTrigger:
    def test_same_callable_different_intervals_get_distinct_names(self) -> None:
        """Two jobs with the same callable but different Every triggers get unique auto-names."""

        def my_handler() -> None:
            pass

        job_60s = make_scheduled_job(name="", job=my_handler, trigger=Every(seconds=60))
        job_300s = make_scheduled_job(name="", job=my_handler, trigger=Every(seconds=300))

        assert job_60s.name != job_300s.name
        assert "my_handler" in job_60s.name
        # Auto-name uses trigger_id() — "every:60" and "every:300"
        assert "every" in job_60s.name
        assert "every" in job_300s.name

    def test_same_callable_different_cron_expressions_get_distinct_names(self) -> None:
        """Two jobs with the same callable but different Cron triggers get unique auto-names."""

        def my_handler() -> None:
            pass

        job_hourly = make_scheduled_job(name="", job=my_handler, trigger=Cron("0 * * * *"))
        job_daily = make_scheduled_job(name="", job=my_handler, trigger=Cron("0 0 * * *"))

        assert job_hourly.name != job_daily.name
        assert "cron" in job_hourly.name
        assert "cron" in job_daily.name

    async def test_same_callable_same_trigger_collide(self) -> None:
        """Two jobs with the same callable AND same trigger correctly collide."""

        def my_handler() -> None:
            pass

        scheduler = make_scheduler()
        job1 = make_scheduled_job(name="", job=my_handler, trigger=Every(seconds=60))
        job2 = make_scheduled_job(name="", job=my_handler, trigger=Every(seconds=60))

        await scheduler.add_job(job1)
        with pytest.raises(ValueError, match="my_handler"):
            await scheduler.add_job(job2)

    def test_no_trigger_uses_callable_name_only(self) -> None:
        """Jobs without a trigger use only the callable name."""

        def my_handler() -> None:
            pass

        job = make_scheduled_job(name="", job=my_handler, trigger=None)
        assert job.name == "my_handler"


class TestIfExistsSkip:
    async def test_skip_returns_existing_when_matching(self) -> None:
        """if_exists='skip' returns the existing job when everything matches."""
        scheduler = make_scheduler()
        fn = lambda: None  # noqa: E731
        job1 = make_scheduled_job(name="poll", job=fn)
        added = await scheduler.add_job(job1)

        job2 = make_scheduled_job(name="poll", job=fn)
        result = await scheduler.add_job(job2, if_exists="skip")

        assert result is added

    async def test_skip_raises_when_config_differs(self) -> None:
        """if_exists='skip' still raises when the name matches but config differs."""
        scheduler = make_scheduler()
        fn_a = lambda: None  # noqa: E731
        fn_b = lambda: None  # noqa: E731
        await scheduler.add_job(make_scheduled_job(name="poll", job=fn_a))

        with pytest.raises(ValueError, match="poll"):
            await scheduler.add_job(make_scheduled_job(name="poll", job=fn_b), if_exists="skip")

    async def test_skip_checks_trigger_equality(self) -> None:
        """if_exists='skip' considers trigger type and value."""
        scheduler = make_scheduler()
        fn = lambda: None  # noqa: E731
        trigger_30s = Every(seconds=30)
        trigger_60s = Every(seconds=60)

        await scheduler.add_job(make_scheduled_job(name="poll", job=fn, trigger=trigger_30s))

        # Same trigger config → skip
        same_trigger = Every(seconds=30)
        result = await scheduler.add_job(
            make_scheduled_job(name="poll", job=fn, trigger=same_trigger), if_exists="skip"
        )
        assert result is scheduler._jobs_by_name["poll"]

        # Different trigger config → error
        with pytest.raises(ValueError, match="poll"):
            await scheduler.add_job(make_scheduled_job(name="poll", job=fn, trigger=trigger_60s), if_exists="skip")

    async def test_error_mode_always_raises_on_duplicate(self) -> None:
        """Default if_exists='error' raises even when config matches."""
        scheduler = make_scheduler()
        fn = lambda: None  # noqa: E731
        await scheduler.add_job(make_scheduled_job(name="poll", job=fn))

        with pytest.raises(ValueError, match="poll"):
            await scheduler.add_job(make_scheduled_job(name="poll", job=fn))


class TestIfExistsReplace:
    async def test_replace_cancels_old_and_registers_new(self) -> None:
        """if_exists='replace' cancels the existing job and registers the new one."""
        scheduler = make_scheduler(wire_dequeue=True)
        fn_old = lambda: None  # noqa: E731
        fn_new = lambda: None  # noqa: E731
        old_job = await scheduler.add_job(make_scheduled_job(name="sensor_check", job=fn_old))

        new_job = make_scheduled_job(name="sensor_check", job=fn_new)
        result = await scheduler.add_job(new_job, if_exists="replace")

        assert result is new_job
        assert scheduler._jobs_by_name["sensor_check"] is new_job
        assert old_job._dequeued is True

    async def test_replace_with_no_existing_job(self) -> None:
        """if_exists='replace' with no pre-existing job behaves like a normal add."""
        scheduler = make_scheduler(wire_dequeue=True)
        fn = lambda: None  # noqa: E731
        job = make_scheduled_job(name="fresh_job", job=fn)

        result = await scheduler.add_job(job, if_exists="replace")

        assert result is job
        assert scheduler._jobs_by_name["fresh_job"] is job

    async def test_replace_preserves_group_membership_of_new_job(self) -> None:
        """if_exists='replace' cleans up old job's group and adds new job to its group."""
        scheduler = make_scheduler(wire_dequeue=True)
        fn_old = lambda: None  # noqa: E731
        fn_new = lambda: None  # noqa: E731
        old_job = make_scheduled_job(name="check", job=fn_old, group="monitors")
        await scheduler.add_job(old_job)

        new_job = make_scheduled_job(name="check", job=fn_new, group="monitors")
        await scheduler.add_job(new_job, if_exists="replace")

        assert new_job in scheduler._jobs_by_group["monitors"]
        assert old_job not in scheduler._jobs_by_group["monitors"]

    async def test_replace_returns_new_job_not_old(self) -> None:
        """if_exists='replace' returns the newly registered job object."""
        scheduler = make_scheduler(wire_dequeue=True)
        fn = lambda: None  # noqa: E731
        old_job = await scheduler.add_job(make_scheduled_job(name="poller", job=fn))

        new_job = make_scheduled_job(name="poller", job=fn, trigger=Every(seconds=120))
        result = await scheduler.add_job(new_job, if_exists="replace")

        assert result is new_job
        assert result is not old_job

    async def test_replace_cross_group(self) -> None:
        """if_exists='replace' moves from old group to new group correctly."""
        scheduler = make_scheduler(wire_dequeue=True)
        fn_old = lambda: None  # noqa: E731
        fn_new = lambda: None  # noqa: E731
        old_job = make_scheduled_job(name="check", job=fn_old, group="old_group")
        await scheduler.add_job(old_job)

        new_job = make_scheduled_job(name="check", job=fn_new, group="new_group")
        await scheduler.add_job(new_job, if_exists="replace")

        assert "old_group" not in scheduler._jobs_by_group or scheduler._jobs_by_group["old_group"] == set()
        assert new_job in scheduler._jobs_by_group["new_group"]
