"""Tests for Scheduler job name uniqueness validation."""

from collections.abc import Callable
from unittest.mock import Mock

import pytest

from hassette.scheduler.classes import CronTrigger, IntervalTrigger, ScheduledJob
from hassette.scheduler.scheduler import Scheduler
from hassette.scheduler.triggers import Every
from hassette.utils.date_utils import now


def _make_scheduler() -> Scheduler:
    """Create a minimal Scheduler instance with mocked internals."""
    scheduler = Scheduler.__new__(Scheduler)
    scheduler.scheduler_service = Mock()
    scheduler._jobs_by_name = {}
    # owner_id is a property on Resource that reads parent.unique_name
    type(scheduler).owner_id = property(lambda _self: "test_owner")
    return scheduler


def _make_job(
    name: str = "",
    *,
    job: Callable[..., None] | None = None,
    trigger: object = None,
) -> ScheduledJob:
    """Create a minimal ScheduledJob."""
    return ScheduledJob(
        owner_id="test_owner",
        next_run=now(),
        job=job or (lambda: None),
        name=name,
        trigger=trigger,
    )


class TestJobNameUniqueness:
    def test_duplicate_name_raises(self) -> None:
        scheduler = _make_scheduler()
        scheduler.add_job(_make_job("daily_backup"))

        with pytest.raises(ValueError, match="daily_backup"):
            scheduler.add_job(_make_job("daily_backup"))

    def test_different_names_ok(self) -> None:
        scheduler = _make_scheduler()
        scheduler.add_job(_make_job("job_a"))
        scheduler.add_job(_make_job("job_b"))

        assert set(scheduler._jobs_by_name) == {"job_a", "job_b"}

    def test_auto_named_jobs_also_enforce_uniqueness(self) -> None:
        """Jobs with auto-derived names (from callable) are still subject to uniqueness checks."""
        scheduler = _make_scheduler()
        # Both jobs use lambda, so __post_init__ auto-names them "<lambda>".
        job1 = _make_job("")
        job2 = _make_job("")

        scheduler.add_job(job1)

        with pytest.raises(ValueError, match="<lambda>"):
            scheduler.add_job(job2)

    def test_removal_allows_reuse(self) -> None:
        scheduler = _make_scheduler()
        job = _make_job("ephemeral")
        scheduler.add_job(job)
        assert "ephemeral" in scheduler._jobs_by_name

        scheduler.remove_job(job)
        assert "ephemeral" not in scheduler._jobs_by_name

        # Re-adding with the same name should now succeed
        scheduler.add_job(_make_job("ephemeral"))
        assert "ephemeral" in scheduler._jobs_by_name

    def test_remove_all_clears_names(self) -> None:
        scheduler = _make_scheduler()
        scheduler.add_job(_make_job("a"))
        scheduler.add_job(_make_job("b"))
        assert set(scheduler._jobs_by_name) == {"a", "b"}

        scheduler.remove_all_jobs()
        assert scheduler._jobs_by_name == {}


class TestAutoGeneratedNamesWithTrigger:
    def test_same_callable_different_intervals_get_distinct_names(self) -> None:
        """Two jobs with the same callable but different IntervalTriggers get unique auto-names."""
        from whenever import TimeDelta

        def my_handler() -> None:
            pass

        job_60s = _make_job("", job=my_handler, trigger=IntervalTrigger(TimeDelta(seconds=60)))
        job_300s = _make_job("", job=my_handler, trigger=IntervalTrigger(TimeDelta(seconds=300)))

        assert job_60s.name != job_300s.name
        assert "my_handler" in job_60s.name
        assert "interval:60s" in job_60s.name
        assert "interval:300s" in job_300s.name

    def test_same_callable_different_cron_expressions_get_distinct_names(self) -> None:
        """Two jobs with the same callable but different CronTriggers get unique auto-names."""

        def my_handler() -> None:
            pass

        job_hourly = _make_job("", job=my_handler, trigger=CronTrigger("0 * * * *"))
        job_daily = _make_job("", job=my_handler, trigger=CronTrigger("0 0 * * *"))

        assert job_hourly.name != job_daily.name
        assert "cron:0 * * * *" in job_hourly.name
        assert "cron:0 0 * * *" in job_daily.name

    def test_same_callable_same_trigger_collide(self) -> None:
        """Two jobs with the same callable AND same trigger correctly collide."""
        from whenever import TimeDelta

        def my_handler() -> None:
            pass

        scheduler = _make_scheduler()
        job1 = _make_job("", job=my_handler, trigger=IntervalTrigger(TimeDelta(seconds=60)))
        job2 = _make_job("", job=my_handler, trigger=IntervalTrigger(TimeDelta(seconds=60)))

        scheduler.add_job(job1)
        with pytest.raises(ValueError, match="my_handler"):
            scheduler.add_job(job2)

    def test_no_trigger_uses_callable_name_only(self) -> None:
        """Jobs without a trigger use only the callable name."""

        def my_handler() -> None:
            pass

        job = _make_job("", job=my_handler, trigger=None)
        assert job.name == "my_handler"

    def test_interval_trigger_str_uses_g_format(self) -> None:
        """IntervalTrigger.__str__ uses :g format (no trailing .0)."""
        from whenever import TimeDelta

        trigger = IntervalTrigger(TimeDelta(seconds=300))
        assert str(trigger) == "interval:300s"

        trigger_frac = IntervalTrigger(TimeDelta(seconds=1, milliseconds=500))
        assert str(trigger_frac) == "interval:1.5s"


class TestIfExistsSkip:
    def test_skip_returns_existing_when_matching(self) -> None:
        """if_exists='skip' returns the existing job when everything matches."""
        scheduler = _make_scheduler()
        fn = lambda: None  # noqa: E731
        job1 = _make_job("poll", job=fn)
        added = scheduler.add_job(job1)

        job2 = _make_job("poll", job=fn)
        result = scheduler.add_job(job2, if_exists="skip")

        assert result is added

    def test_skip_raises_when_config_differs(self) -> None:
        """if_exists='skip' still raises when the name matches but config differs."""
        scheduler = _make_scheduler()
        fn_a = lambda: None  # noqa: E731
        fn_b = lambda: None  # noqa: E731
        scheduler.add_job(_make_job("poll", job=fn_a))

        with pytest.raises(ValueError, match="poll"):
            scheduler.add_job(_make_job("poll", job=fn_b), if_exists="skip")

    def test_skip_checks_trigger_equality(self) -> None:
        """if_exists='skip' considers trigger type and value."""
        scheduler = _make_scheduler()
        fn = lambda: None  # noqa: E731
        trigger_30s = Every(seconds=30)
        trigger_60s = Every(seconds=60)

        scheduler.add_job(_make_job("poll", job=fn, trigger=trigger_30s))

        # Same trigger config → skip
        same_trigger = Every(seconds=30)
        result = scheduler.add_job(_make_job("poll", job=fn, trigger=same_trigger), if_exists="skip")
        assert result is scheduler._jobs_by_name["poll"]

        # Different trigger config → error
        with pytest.raises(ValueError, match="poll"):
            scheduler.add_job(_make_job("poll", job=fn, trigger=trigger_60s), if_exists="skip")

    def test_error_mode_always_raises_on_duplicate(self) -> None:
        """Default if_exists='error' raises even when config matches."""
        scheduler = _make_scheduler()
        fn = lambda: None  # noqa: E731
        scheduler.add_job(_make_job("poll", job=fn))

        with pytest.raises(ValueError, match="poll"):
            scheduler.add_job(_make_job("poll", job=fn))
