"""Tests for Scheduler job name uniqueness validation."""

from collections.abc import Callable
from unittest.mock import Mock

import pytest

from hassette.scheduler.classes import ScheduledJob
from hassette.scheduler.scheduler import Scheduler
from hassette.scheduler.triggers import Cron, Every
from hassette.utils.date_utils import now


def _make_scheduler(*, wire_dequeue: bool = False) -> Scheduler:
    """Create a minimal Scheduler instance with mocked internals.

    Uses a unique per-call subclass so that property overrides for owner_id do
    NOT mutate the shared Scheduler class — which would break parallel test
    workers that create real Scheduler instances concurrently.

    Args:
        wire_dequeue: If True, configure scheduler_service.dequeue_job to mimic
            real behavior (set _dequeued=True and fire _on_job_removed callback).
            Required for tests that exercise cancel_job paths.
    """
    # Fresh subclass per call: property assignments stay on _TestScheduler, not Scheduler.
    _TestScheduler = type("_TestScheduler", (Scheduler,), {})  # noqa: N806
    _TestScheduler.owner_id = property(lambda _self: "test_owner")  # pyright: ignore[reportAttributeAccessIssue]

    scheduler = _TestScheduler.__new__(_TestScheduler)
    scheduler.scheduler_service = Mock()
    scheduler._jobs_by_name = {}
    scheduler._jobs_by_group = {}
    scheduler._error_handler = None
    scheduler.logger = Mock()

    # Base behavior: always set _dequeued=True (matches test_scheduler_resource.py)
    scheduler.scheduler_service.dequeue_job = Mock(side_effect=lambda job: setattr(job, "_dequeued", True) or True)

    if wire_dequeue:

        def _mock_dequeue(job: "ScheduledJob") -> bool:
            job._dequeued = True
            scheduler._on_job_removed(job)
            return True

        scheduler.scheduler_service.dequeue_job.side_effect = _mock_dequeue

    return scheduler


def _make_job(
    name: str = "",
    *,
    job: Callable[..., None] | None = None,
    trigger: object = None,
    group: str | None = None,
) -> ScheduledJob:
    """Create a minimal ScheduledJob."""
    return ScheduledJob(
        owner_id="test_owner",
        next_run=now(),
        job=job or (lambda: None),
        name=name,
        trigger=trigger,
        group=group,
    )


class TestJobNameUniqueness:
    def test_duplicate_name_raises(self) -> None:
        scheduler = _make_scheduler()
        scheduler.add_job(_make_job("daily_backup"))

        with pytest.raises(ValueError, match="daily_backup"):
            scheduler.add_job(_make_job("daily_backup"))

    def test_different_names_ok(self) -> None:
        scheduler = _make_scheduler()
        scheduler.add_job(_make_job("job_a"))
        scheduler.add_job(_make_job("job_b"))

        assert set(scheduler._jobs_by_name) == {"job_a", "job_b"}

    def test_auto_named_jobs_also_enforce_uniqueness(self) -> None:
        """Jobs with auto-derived names (from callable) are still subject to uniqueness checks."""
        scheduler = _make_scheduler()
        # Both jobs use lambda, so __post_init__ auto-names them "<lambda>".
        job1 = _make_job("")
        job2 = _make_job("")

        scheduler.add_job(job1)

        with pytest.raises(ValueError, match="<lambda>"):
            scheduler.add_job(job2)

    def test_removal_allows_reuse(self) -> None:
        scheduler = _make_scheduler()
        job = _make_job("ephemeral")
        scheduler.add_job(job)
        assert "ephemeral" in scheduler._jobs_by_name

        # Simulate callback-based removal (as fired by scheduler_service.dequeue_job)
        scheduler._on_job_removed(job)
        assert "ephemeral" not in scheduler._jobs_by_name

        # Re-adding with the same name should now succeed
        scheduler.add_job(_make_job("ephemeral"))
        assert "ephemeral" in scheduler._jobs_by_name

    def test_remove_all_clears_names(self) -> None:
        scheduler = _make_scheduler()
        scheduler.add_job(_make_job("a"))
        scheduler.add_job(_make_job("b"))
        assert set(scheduler._jobs_by_name) == {"a", "b"}

        scheduler._remove_all_jobs()
        assert scheduler._jobs_by_name == {}


class TestAutoGeneratedNamesWithTrigger:
    def test_same_callable_different_intervals_get_distinct_names(self) -> None:
        """Two jobs with the same callable but different Every triggers get unique auto-names."""

        def my_handler() -> None:
            pass

        job_60s = _make_job("", job=my_handler, trigger=Every(seconds=60))
        job_300s = _make_job("", job=my_handler, trigger=Every(seconds=300))

        assert job_60s.name != job_300s.name
        assert "my_handler" in job_60s.name
        # Auto-name uses trigger_id() — "every:60" and "every:300"
        assert "every" in job_60s.name
        assert "every" in job_300s.name

    def test_same_callable_different_cron_expressions_get_distinct_names(self) -> None:
        """Two jobs with the same callable but different Cron triggers get unique auto-names."""

        def my_handler() -> None:
            pass

        job_hourly = _make_job("", job=my_handler, trigger=Cron("0 * * * *"))
        job_daily = _make_job("", job=my_handler, trigger=Cron("0 0 * * *"))

        assert job_hourly.name != job_daily.name
        assert "cron" in job_hourly.name
        assert "cron" in job_daily.name

    def test_same_callable_same_trigger_collide(self) -> None:
        """Two jobs with the same callable AND same trigger correctly collide."""

        def my_handler() -> None:
            pass

        scheduler = _make_scheduler()
        job1 = _make_job("", job=my_handler, trigger=Every(seconds=60))
        job2 = _make_job("", job=my_handler, trigger=Every(seconds=60))

        scheduler.add_job(job1)
        with pytest.raises(ValueError, match="my_handler"):
            scheduler.add_job(job2)

    def test_no_trigger_uses_callable_name_only(self) -> None:
        """Jobs without a trigger use only the callable name."""

        def my_handler() -> None:
            pass

        job = _make_job("", job=my_handler, trigger=None)
        assert job.name == "my_handler"


class TestIfExistsSkip:
    def test_skip_returns_existing_when_matching(self) -> None:
        """if_exists='skip' returns the existing job when everything matches."""
        scheduler = _make_scheduler()
        fn = lambda: None  # noqa: E731
        job1 = _make_job("poll", job=fn)
        added = scheduler.add_job(job1)

        job2 = _make_job("poll", job=fn)
        result = scheduler.add_job(job2, if_exists="skip")

        assert result is added

    def test_skip_raises_when_config_differs(self) -> None:
        """if_exists='skip' still raises when the name matches but config differs."""
        scheduler = _make_scheduler()
        fn_a = lambda: None  # noqa: E731
        fn_b = lambda: None  # noqa: E731
        scheduler.add_job(_make_job("poll", job=fn_a))

        with pytest.raises(ValueError, match="poll"):
            scheduler.add_job(_make_job("poll", job=fn_b), if_exists="skip")

    def test_skip_checks_trigger_equality(self) -> None:
        """if_exists='skip' considers trigger type and value."""
        scheduler = _make_scheduler()
        fn = lambda: None  # noqa: E731
        trigger_30s = Every(seconds=30)
        trigger_60s = Every(seconds=60)

        scheduler.add_job(_make_job("poll", job=fn, trigger=trigger_30s))

        # Same trigger config → skip
        same_trigger = Every(seconds=30)
        result = scheduler.add_job(_make_job("poll", job=fn, trigger=same_trigger), if_exists="skip")
        assert result is scheduler._jobs_by_name["poll"]

        # Different trigger config → error
        with pytest.raises(ValueError, match="poll"):
            scheduler.add_job(_make_job("poll", job=fn, trigger=trigger_60s), if_exists="skip")

    def test_error_mode_always_raises_on_duplicate(self) -> None:
        """Default if_exists='error' raises even when config matches."""
        scheduler = _make_scheduler()
        fn = lambda: None  # noqa: E731
        scheduler.add_job(_make_job("poll", job=fn))

        with pytest.raises(ValueError, match="poll"):
            scheduler.add_job(_make_job("poll", job=fn))


class TestIfExistsReplace:
    def test_replace_cancels_old_and_registers_new(self) -> None:
        """if_exists='replace' cancels the existing job and registers the new one."""
        scheduler = _make_scheduler(wire_dequeue=True)
        fn_old = lambda: None  # noqa: E731
        fn_new = lambda: None  # noqa: E731
        old_job = scheduler.add_job(_make_job("sensor_check", job=fn_old))

        new_job = _make_job("sensor_check", job=fn_new)
        result = scheduler.add_job(new_job, if_exists="replace")

        assert result is new_job
        assert scheduler._jobs_by_name["sensor_check"] is new_job
        assert old_job._dequeued is True

    def test_replace_with_no_existing_job(self) -> None:
        """if_exists='replace' with no pre-existing job behaves like a normal add."""
        scheduler = _make_scheduler(wire_dequeue=True)
        fn = lambda: None  # noqa: E731
        job = _make_job("fresh_job", job=fn)

        result = scheduler.add_job(job, if_exists="replace")

        assert result is job
        assert scheduler._jobs_by_name["fresh_job"] is job

    def test_replace_preserves_group_membership_of_new_job(self) -> None:
        """if_exists='replace' cleans up old job's group and adds new job to its group."""
        scheduler = _make_scheduler(wire_dequeue=True)
        fn_old = lambda: None  # noqa: E731
        fn_new = lambda: None  # noqa: E731
        old_job = _make_job("check", job=fn_old, group="monitors")
        scheduler.add_job(old_job)

        new_job = _make_job("check", job=fn_new, group="monitors")
        scheduler.add_job(new_job, if_exists="replace")

        assert new_job in scheduler._jobs_by_group["monitors"]
        assert old_job not in scheduler._jobs_by_group["monitors"]

    def test_replace_returns_new_job_not_old(self) -> None:
        """if_exists='replace' returns the newly registered job object."""
        scheduler = _make_scheduler(wire_dequeue=True)
        fn = lambda: None  # noqa: E731
        old_job = scheduler.add_job(_make_job("poller", job=fn))

        new_job = _make_job("poller", job=fn, trigger=Every(seconds=120))
        result = scheduler.add_job(new_job, if_exists="replace")

        assert result is new_job
        assert result is not old_job

    def test_replace_cross_group(self) -> None:
        """if_exists='replace' moves from old group to new group correctly."""
        scheduler = _make_scheduler(wire_dequeue=True)
        fn_old = lambda: None  # noqa: E731
        fn_new = lambda: None  # noqa: E731
        old_job = _make_job("check", job=fn_old, group="old_group")
        scheduler.add_job(old_job)

        new_job = _make_job("check", job=fn_new, group="new_group")
        scheduler.add_job(new_job, if_exists="replace")

        assert "old_group" not in scheduler._jobs_by_group or scheduler._jobs_by_group["old_group"] == set()
        assert new_job in scheduler._jobs_by_group["new_group"]
