name: Build & Publish Image

on:
    push:
        tags: ["v*"] # only versioned releases
    workflow_dispatch: # manual trigger

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        env:
            IMAGE_NAME: hassette
            REGISTRY: ghcr.io
            OWNER: ${{ github.repository_owner }}
            PYTHON_VERSION: ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                  activate-environment: true
                  enable-cache: true

            - name: Classify release tag
              if: github.event_name == 'push'
              run: uv run ./tools/check_tag_version.py --ref-name ${{ github.ref_name }} --project-version $(uv version --short)

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}
                  flavor: |
                      latest=false
                  tags: |
                      type=sha,prefix=sha-,format=short,suffix=-py${{ env.PYTHON_VERSION }}
                      type=pep440,pattern={{version}},suffix=-py${{ env.PYTHON_VERSION }},enable=${{ github.event_name == 'push' }}
                      type=raw,value=latest-py${{ env.PYTHON_VERSION }},enable=${{ github.event_name == 'push' && env.IS_STABLE_RELEASE == 'true' }}

            - name: Build & Push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64,linux/arm64
                  build-args: |
                      PYTHON_VERSION=${{ matrix.python-version }}
