name: Lint

on:
    push:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv and set the Python version
              uses: astral-sh/setup-uv@v6
              with:
                  python-version: "3.13"

            - run: uv sync

            - name: Install fd-find
              run: sudo apt-get update && sudo apt-get install -y fd-find

            - name: Run lint checks
              run: |
                  uv tool install ruff==0.14.9
                  uvx ruff format --check --diff .
                  uvx ruff check .
                  uvx pre-commit run --all-files --hook-stage pre-push
